#pragma once

/*
* SDK generated by Dumper-7
*
* https://github.com/Encryqed/Dumper-7
*/

// Package: AbleCore

#include "Basic.hpp"

#include "CoreUObject_structs.hpp"
#include "Engine_structs.hpp"


SDK_NAMESPACE_START

// Enum AbleCore.EAblAbilityPassiveBehavior
// NumValues: 0x0005
enum class EAblAbilityPassiveBehavior : uint8
{
	CannotBePassive                          = 0,
	RefreshDuration                          = 1,
	IncreaseStackCount                       = 2,
	IncreaseAndRefresh                       = 3,
	EAblAbilityPassiveBehavior_MAX           = 4,
};

// Enum AbleCore.EAblAbilityStartResult
// NumValues: 0x000C
enum class EAblAbilityStartResult : uint8
{
	InvalidTarget                            = 0,
	FailedCustomCheck                        = 1,
	CooldownNotExpired                       = 2,
	CannotInterruptCurrentAbility            = 3,
	NotAllowedAsPassive                      = 4,
	PassiveMaxStacksReached                  = 5,
	InternalSystemsError                     = 6,
	AsyncProcessing                          = 7,
	ForwardedToServer                        = 8,
	InvalidParameter                         = 9,
	Success                                  = 10,
	EAblAbilityStartResult_MAX               = 11,
};

// Enum AbleCore.EAblAbilityTargetType
// NumValues: 0x0006
enum class EAblAbilityTargetType : uint8
{
	Self                                     = 0,
	Owner                                    = 1,
	Instigator                               = 2,
	TargetActor                              = 3,
	Camera                                   = 4,
	EAblAbilityTargetType_MAX                = 5,
};

// Enum AbleCore.EAblCollisionFilterSort
// NumValues: 0x0003
enum class EAblCollisionFilterSort : uint8
{
	AblFitlerSort_Ascending                  = 0,
	AblFilterSort_Descending                 = 1,
	EAblCollisionFilterSort_MAX              = 2,
};

// Enum AbleCore.EAblPlayAnimationTaskAnimMode
// NumValues: 0x0004
enum class EAblPlayAnimationTaskAnimMode : uint8
{
	SingleNode                               = 0,
	AbilityAnimationNode                     = 1,
	DynamicMontage                           = 2,
	EAblPlayAnimationTaskAnimMode_MAX        = 3,
};

// Enum AbleCore.EAblTargetingFilterSort
// NumValues: 0x0003
enum class EAblTargetingFilterSort : uint8
{
	AblTargetFilterSort_Ascending            = 0,
	AblTargetFilterSort_Descending           = 1,
	AblTargetFilterSort_MAX                  = 2,
};

// Enum AbleCore.EAblAbilityTaskRealm
// NumValues: 0x0005
enum class EAblAbilityTaskRealm : uint8
{
	Client                                   = 0,
	Server                                   = 1,
	ClientAndServer                          = 2,
	TotalRealms                              = 3,
	EAblAbilityTaskRealm_MAX                 = 4,
};

// Enum AbleCore.EAblAbilityTaskResult
// NumValues: 0x0004
enum class EAblAbilityTaskResult : uint8
{
	Successful                               = 0,
	Branched                                 = 1,
	Interrupted                              = 2,
	EAblAbilityTaskResult_MAX                = 3,
};

// ScriptStruct AbleCore.AblAbilityCooldown
// 0x0010 (0x0010 - 0x0000)
struct alignas(0x04) FAblAbilityCooldown final
{
public:
	uint8                                         Pad_0[0x10];                                       // 0x0000(0x0010)(Fixing Struct Size After Last Property [ Dumper-7 ])
};
DUMPER7_ASSERTS_FAblAbilityCooldown;

// ScriptStruct AbleCore.AnimNode_AbilityAnimPlayer
// 0x0070 (0x00A8 - 0x0038)
struct FAnimNode_AbilityAnimPlayer final : public FAnimNode_AssetPlayerBase
{
public:
	uint8                                         Pad_38[0x70];                                      // 0x0038(0x0070)(Fixing Struct Size After Last Property [ Dumper-7 ])
};
DUMPER7_ASSERTS_FAnimNode_AbilityAnimPlayer;

// ScriptStruct AbleCore.AblAbilityNetworkContext
// 0x0038 (0x0038 - 0x0000)
struct FAblAbilityNetworkContext final
{
public:
	TWeakObjectPtr<class UAblAbility>             m_Ability;                                         // 0x0000(0x0008)(ZeroConstructor, IsPlainOldData, NoDestructor, UObjectWrapper, HasGetValueTypeHash, NativeAccessSpecifierPrivate)
	TWeakObjectPtr<class UAblAbilityComponent>    m_AbilityComponent;                                // 0x0008(0x0008)(ExportObject, ZeroConstructor, InstancedReference, IsPlainOldData, NoDestructor, UObjectWrapper, HasGetValueTypeHash, NativeAccessSpecifierPrivate)
	TWeakObjectPtr<class AActor>                  m_Owner;                                           // 0x0010(0x0008)(ZeroConstructor, IsPlainOldData, NoDestructor, UObjectWrapper, HasGetValueTypeHash, NativeAccessSpecifierPrivate)
	TWeakObjectPtr<class AActor>                  m_Instigator;                                      // 0x0018(0x0008)(ZeroConstructor, IsPlainOldData, NoDestructor, UObjectWrapper, HasGetValueTypeHash, NativeAccessSpecifierPrivate)
	TArray<TWeakObjectPtr<class AActor>>          m_TargetActors;                                    // 0x0020(0x0010)(ZeroConstructor, UObjectWrapper, HasGetValueTypeHash, NativeAccessSpecifierPrivate)
	int8                                          m_CurrentStacks;                                   // 0x0030(0x0001)(ZeroConstructor, IsPlainOldData, NoDestructor, HasGetValueTypeHash, NativeAccessSpecifierPrivate)
	bool                                          m_IsRefreshAbilityTime;                            // 0x0031(0x0001)(ZeroConstructor, IsPlainOldData, NoDestructor, HasGetValueTypeHash, NativeAccessSpecifierPrivate)
	uint8                                         Pad_32[0x2];                                       // 0x0032(0x0002)(Fixing Size After Last Property [ Dumper-7 ])
	float                                         m_TimeStamp;                                       // 0x0034(0x0004)(ZeroConstructor, IsPlainOldData, NoDestructor, HasGetValueTypeHash, NativeAccessSpecifierPrivate)
};
DUMPER7_ASSERTS_FAblAbilityNetworkContext;

// ScriptStruct AbleCore.AblQueryResult
// 0x0010 (0x0010 - 0x0000)
struct FAblQueryResult final
{
public:
	TWeakObjectPtr<class UPrimitiveComponent>     PrimitiveComponent;                                // 0x0000(0x0008)(BlueprintVisible, ExportObject, BlueprintReadOnly, ZeroConstructor, Transient, InstancedReference, IsPlainOldData, NoDestructor, UObjectWrapper, HasGetValueTypeHash, NativeAccessSpecifierPublic)
	TWeakObjectPtr<class AActor>                  Actor;                                             // 0x0008(0x0008)(BlueprintVisible, BlueprintReadOnly, ZeroConstructor, Transient, IsPlainOldData, NoDestructor, UObjectWrapper, HasGetValueTypeHash, NativeAccessSpecifierPublic)
};
DUMPER7_ASSERTS_FAblQueryResult;

// ScriptStruct AbleCore.AblBlendTimes
// 0x0008 (0x0008 - 0x0000)
struct FAblBlendTimes final
{
public:
	float                                         m_BlendIn;                                         // 0x0000(0x0004)(Edit, ZeroConstructor, DisableEditOnTemplate, IsPlainOldData, NoDestructor, HasGetValueTypeHash, NativeAccessSpecifierPublic)
	float                                         m_BlendOut;                                        // 0x0004(0x0004)(Edit, ZeroConstructor, DisableEditOnTemplate, IsPlainOldData, NoDestructor, HasGetValueTypeHash, NativeAccessSpecifierPublic)
};
DUMPER7_ASSERTS_FAblBlendTimes;

// ScriptStruct AbleCore.CollisionLayerResponseEntry
// 0x0010 (0x0010 - 0x0000)
struct alignas(0x04) FCollisionLayerResponseEntry final
{
public:
	uint8                                         Pad_0[0x10];                                       // 0x0000(0x0010)(Fixing Struct Size After Last Property [ Dumper-7 ])
};
DUMPER7_ASSERTS_FCollisionLayerResponseEntry;

// ScriptStruct AbleCore.AblAbilityTargetTypeLocation
// 0x0028 (0x0028 - 0x0000)
struct FAblAbilityTargetTypeLocation final
{
public:
	EAblAbilityTargetType                         m_Source;                                          // 0x0000(0x0001)(Edit, ZeroConstructor, DisableEditOnTemplate, IsPlainOldData, NoDestructor, Protected, HasGetValueTypeHash, NativeAccessSpecifierProtected)
	uint8                                         Pad_1[0x3];                                        // 0x0001(0x0003)(Fixing Size After Last Property [ Dumper-7 ])
	struct FVector                                m_Offset;                                          // 0x0004(0x000C)(Edit, ZeroConstructor, DisableEditOnTemplate, IsPlainOldData, NoDestructor, Protected, HasGetValueTypeHash, NativeAccessSpecifierProtected)
	struct FRotator                               m_Rotation;                                        // 0x0010(0x000C)(Edit, ZeroConstructor, DisableEditOnTemplate, IsPlainOldData, NoDestructor, Protected, NativeAccessSpecifierProtected)
	class FName                                   m_Socket;                                          // 0x001C(0x0008)(Edit, ZeroConstructor, DisableEditOnTemplate, IsPlainOldData, NoDestructor, Protected, HasGetValueTypeHash, NativeAccessSpecifierProtected)
	bool                                          m_UseSocketRotation;                               // 0x0024(0x0001)(Edit, ZeroConstructor, DisableEditOnTemplate, IsPlainOldData, NoDestructor, Protected, HasGetValueTypeHash, NativeAccessSpecifierProtected)
	uint8                                         Pad_25[0x3];                                       // 0x0025(0x0003)(Fixing Struct Size After Last Property [ Dumper-7 ])
};
DUMPER7_ASSERTS_FAblAbilityTargetTypeLocation;

// ScriptStruct AbleCore.TurnToTaskEntry
// 0x0014 (0x0014 - 0x0000)
struct alignas(0x04) FTurnToTaskEntry final
{
public:
	uint8                                         Pad_0[0x14];                                       // 0x0000(0x0014)(Fixing Struct Size After Last Property [ Dumper-7 ])
};
DUMPER7_ASSERTS_FTurnToTaskEntry;

SDK_NAMESPACE_END
