#pragma once

/*
* SDK generated by Dumper-7
*
* https://github.com/Encryqed/Dumper-7
*/

// Package: Actuator_P_Huixing

#include "Basic.hpp"

#include "Actuator_P_Huixing_classes.hpp"
#include "Actuator_P_Huixing_parameters.hpp"


SDK_NAMESPACE_START

// Function Actuator_P_Huixing.Actuator_P_Huixing_C.ExecuteUbergraph_Actuator_P_Huixing
// (Final, UbergraphFunction)
// Parameters:
// int32                                   EntryPoint                                             (BlueprintVisible, BlueprintReadOnly, Parm, ZeroConstructor, IsPlainOldData, NoDestructor, HasGetValueTypeHash)

void Actuator_P_Huixing::AActuator_P_Huixing_C::ExecuteUbergraph_Actuator_P_Huixing(int32 EntryPoint)
{
	static class UFunction* Func = nullptr;

	if (Func == nullptr)
		Func = Class->GetFunction("Actuator_P_Huixing_C", "ExecuteUbergraph_Actuator_P_Huixing");

	Params::Actuator_P_Huixing_C_ExecuteUbergraph_Actuator_P_Huixing Parms{};

	Parms.EntryPoint = EntryPoint;

	UObject::ProcessEvent(Func, &Parms);
}


// Function Actuator_P_Huixing.Actuator_P_Huixing_C.ReceiveTick
// (Event, Public, BlueprintEvent)
// Parameters:
// float                                   DeltaSeconds                                           (BlueprintVisible, BlueprintReadOnly, Parm, ZeroConstructor, IsPlainOldData, NoDestructor, HasGetValueTypeHash)

void Actuator_P_Huixing::AActuator_P_Huixing_C::ReceiveTick(float DeltaSeconds)
{
	static class UFunction* Func = nullptr;

	if (Func == nullptr)
		Func = Class->GetFunction("Actuator_P_Huixing_C", "ReceiveTick");

	Params::Actuator_P_Huixing_C_ReceiveTick Parms{};

	Parms.DeltaSeconds = DeltaSeconds;

	UObject::ProcessEvent(Func, &Parms);
}


// Function Actuator_P_Huixing.Actuator_P_Huixing_C.ReceiveBeginPlay
// (Event, Protected, BlueprintEvent)

void Actuator_P_Huixing::AActuator_P_Huixing_C::ReceiveBeginPlay()
{
	static class UFunction* Func = nullptr;

	if (Func == nullptr)
		Func = Class->GetFunction("Actuator_P_Huixing_C", "ReceiveBeginPlay");

	UObject::ProcessEvent(Func, nullptr);
}


SDK_NAMESPACE_END
