#pragma once

/*
* SDK generated by Dumper-7
*
* https://github.com/Encryqed/Dumper-7
*/

// Package: BP_ActivatorSwitchWeapon_E_Maddelena_0

#include "Basic.hpp"

#include "PMGame_classes.hpp"


SDK_NAMESPACE_START

// BlueprintGeneratedClass BP_ActivatorSwitchWeapon_E_Maddelena.BP_ActivatorSwitchWeapon_E_Maddelena_C
// 0x0000 (0x0230 - 0x0230)
class BP_ActivatorSwitchWeapon_E_Maddelena_0::UBP_ActivatorSwitchWeapon_E_Maddelena_C final : public UCyGASwitchWeapon
{
public:
	static class UClass* StaticClass()
	{
		BP_STATIC_CLASS_IMPL_FULLNAME("BlueprintGeneratedClass BP_ActivatorSwitchWeapon_E_Maddelena.BP_ActivatorSwitchWeapon_E_Maddelena_C")
	}
	static const class FName& StaticName()
	{
		STATIC_NAME_IMPL(L"BP_ActivatorSwitchWeapon_E_Maddelena_C")
	}
	static class BP_ActivatorSwitchWeapon_E_Maddelena_0::UBP_ActivatorSwitchWeapon_E_Maddelena_C* GetDefaultObj()
	{
		return GetDefaultObjImpl<BP_ActivatorSwitchWeapon_E_Maddelena_0::UBP_ActivatorSwitchWeapon_E_Maddelena_C>();
	}
};
DUMPER7_ASSERTS_BP_ActivatorSwitchWeapon_E_Maddelena_0__UBP_ActivatorSwitchWeapon_E_Maddelena_C;

SDK_NAMESPACE_END
