#pragma once

/*
* SDK generated by Dumper-7
*
* https://github.com/Encryqed/Dumper-7
*/

// Package: BP_Atom_ChangeComponentScale

#include "Basic.hpp"

#include "PMGame_classes.hpp"


SDK_NAMESPACE_START

// BlueprintGeneratedClass BP_Atom_ChangeComponentScale.BP_Atom_ChangeComponentScale_C
// 0x0000 (0x0690 - 0x0690)
class BP_Atom_ChangeComponentScale::UBP_Atom_ChangeComponentScale_C final : public UCySAtomChangeComponentScale
{
public:
	static class UClass* StaticClass()
	{
		BP_STATIC_CLASS_IMPL_FULLNAME("BlueprintGeneratedClass BP_Atom_ChangeComponentScale.BP_Atom_ChangeComponentScale_C")
	}
	static const class FName& StaticName()
	{
		STATIC_NAME_IMPL(L"BP_Atom_ChangeComponentScale_C")
	}
	static class BP_Atom_ChangeComponentScale::UBP_Atom_ChangeComponentScale_C* GetDefaultObj()
	{
		return GetDefaultObjImpl<BP_Atom_ChangeComponentScale::UBP_Atom_ChangeComponentScale_C>();
	}
};
DUMPER7_ASSERTS_BP_Atom_ChangeComponentScale__UBP_Atom_ChangeComponentScale_C;

SDK_NAMESPACE_END
