#pragma once

/*
* SDK generated by Dumper-7
*
* https://github.com/Encryqed/Dumper-7
*/

// Package: BP_Atom_AddAmmo

#include "Basic.hpp"

#include "PMGame_classes.hpp"


SDK_NAMESPACE_START

// BlueprintGeneratedClass BP_Atom_AddAmmo.BP_Atom_AddAmmo_C
// 0x0000 (0x0600 - 0x0600)
class BP_Atom_AddAmmo::UBP_Atom_AddAmmo_C final : public UCySAtomAddAmmo
{
public:
	static class UClass* StaticClass()
	{
		BP_STATIC_CLASS_IMPL_FULLNAME("BlueprintGeneratedClass BP_Atom_AddAmmo.BP_Atom_AddAmmo_C")
	}
	static const class FName& StaticName()
	{
		STATIC_NAME_IMPL(L"BP_Atom_AddAmmo_C")
	}
	static class BP_Atom_AddAmmo::UBP_Atom_AddAmmo_C* GetDefaultObj()
	{
		return GetDefaultObjImpl<BP_Atom_AddAmmo::UBP_Atom_AddAmmo_C>();
	}
};
DUMPER7_ASSERTS_BP_Atom_AddAmmo__UBP_Atom_AddAmmo_C;

SDK_NAMESPACE_END
