#pragma once

/*
* SDK generated by Dumper-7
*
* https://github.com/Encryqed/Dumper-7
*/

// Package: BP_AddTags_ForCanCancel_X_3

#include "Basic.hpp"

#include "PMGame_classes.hpp"


SDK_NAMESPACE_START

// BlueprintGeneratedClass BP_AddTags_ForCanCancel_X.BP_AddTags_ForCanCancel_X_C
// 0x0000 (0x0670 - 0x0670)
class BP_AddTags_ForCanCancel_X_3::UBP_AddTags_ForCanCancel_X_C final : public UCySAtomAddLooseTags
{
public:
	static class UClass* StaticClass()
	{
		BP_STATIC_CLASS_IMPL_FULLNAME("BlueprintGeneratedClass BP_AddTags_ForCanCancel_X.BP_AddTags_ForCanCancel_X_C")
	}
	static const class FName& StaticName()
	{
		STATIC_NAME_IMPL(L"BP_AddTags_ForCanCancel_X_C")
	}
	static class BP_AddTags_ForCanCancel_X_3::UBP_AddTags_ForCanCancel_X_C* GetDefaultObj()
	{
		return GetDefaultObjImpl<BP_AddTags_ForCanCancel_X_3::UBP_AddTags_ForCanCancel_X_C>();
	}
};
DUMPER7_ASSERTS_BP_AddTags_ForCanCancel_X_3__UBP_AddTags_ForCanCancel_X_C;

SDK_NAMESPACE_END
