#pragma once

/*
* SDK generated by Dumper-7
*
* https://github.com/Encryqed/Dumper-7
*/

// Package: BP_ActivatorUIEvent

#include "Basic.hpp"

#include "PMGame_classes.hpp"


SDK_NAMESPACE_START

// BlueprintGeneratedClass BP_ActivatorUIEvent.BP_ActivatorUIEvent_C
// 0x0000 (0x02E8 - 0x02E8)
class UBP_ActivatorUIEvent_C final : public UCyGAActivateUIEvent
{
public:
	static class UClass* StaticClass()
	{
		BP_STATIC_CLASS_IMPL("BP_ActivatorUIEvent_C")
	}
	static const class FName& StaticName()
	{
		STATIC_NAME_IMPL(L"BP_ActivatorUIEvent_C")
	}
	static class UBP_ActivatorUIEvent_C* GetDefaultObj()
	{
		return GetDefaultObjImpl<UBP_ActivatorUIEvent_C>();
	}
};
DUMPER7_ASSERTS_UBP_ActivatorUIEvent_C;

SDK_NAMESPACE_END
