#pragma once

/*
* SDK generated by Dumper-7
*
* https://github.com/Encryqed/Dumper-7
*/

// Package: BP_Activator_AddEffects_Q_Fissioner1

#include "Basic.hpp"

#include "PMGame_classes.hpp"


SDK_NAMESPACE_START

// BlueprintGeneratedClass BP_Activator_AddEffects_Q_Fissioner1.BP_Activator_AddEffects_Q_Fissioner1_C
// 0x0000 (0x0268 - 0x0268)
class BP_Activator_AddEffects_Q_Fissioner1::UBP_Activator_AddEffects_Q_Fissioner1_C final : public UCyGAActivateEffects
{
public:
	static class UClass* StaticClass()
	{
		BP_STATIC_CLASS_IMPL_FULLNAME("BlueprintGeneratedClass BP_Activator_AddEffects_Q_Fissioner1.BP_Activator_AddEffects_Q_Fissioner1_C")
	}
	static const class FName& StaticName()
	{
		STATIC_NAME_IMPL(L"BP_Activator_AddEffects_Q_Fissioner1_C")
	}
	static class BP_Activator_AddEffects_Q_Fissioner1::UBP_Activator_AddEffects_Q_Fissioner1_C* GetDefaultObj()
	{
		return GetDefaultObjImpl<BP_Activator_AddEffects_Q_Fissioner1::UBP_Activator_AddEffects_Q_Fissioner1_C>();
	}
};
DUMPER7_ASSERTS_BP_Activator_AddEffects_Q_Fissioner1__UBP_Activator_AddEffects_Q_Fissioner1_C;

SDK_NAMESPACE_END
