#pragma once

/*
* SDK generated by Dumper-7
*
* https://github.com/Encryqed/Dumper-7
*/

// Package: BP_Activator_SetSlideWallRenderState

#include "Basic.hpp"

#include "PMGame_classes.hpp"


SDK_NAMESPACE_START

// BlueprintGeneratedClass BP_Activator_SetSlideWallRenderState.BP_Activator_SetSlideWallRenderState_C
// 0x0000 (0x0230 - 0x0230)
class UBP_Activator_SetSlideWallRenderState_C final : public UCyGASetSlideWallRenderState
{
public:
	static class UClass* StaticClass()
	{
		BP_STATIC_CLASS_IMPL("BP_Activator_SetSlideWallRenderState_C")
	}
	static const class FName& StaticName()
	{
		STATIC_NAME_IMPL(L"BP_Activator_SetSlideWallRenderState_C")
	}
	static class UBP_Activator_SetSlideWallRenderState_C* GetDefaultObj()
	{
		return GetDefaultObjImpl<UBP_Activator_SetSlideWallRenderState_C>();
	}
};
DUMPER7_ASSERTS_UBP_Activator_SetSlideWallRenderState_C;

SDK_NAMESPACE_END
