#pragma once

/*
* SDK generated by Dumper-7
*
* https://github.com/Encryqed/Dumper-7
*/

// Package: BP_Atom_DisableCollision

#include "Basic.hpp"

#include "PMGame_classes.hpp"


SDK_NAMESPACE_START

// BlueprintGeneratedClass BP_Atom_DisableCollision.BP_Atom_DisableCollision_C
// 0x0000 (0x0590 - 0x0590)
class BP_Atom_DisableCollision::UBP_Atom_DisableCollision_C final : public UCySAtomDisableCollision
{
public:
	static class UClass* StaticClass()
	{
		BP_STATIC_CLASS_IMPL_FULLNAME("BlueprintGeneratedClass BP_Atom_DisableCollision.BP_Atom_DisableCollision_C")
	}
	static const class FName& StaticName()
	{
		STATIC_NAME_IMPL(L"BP_Atom_DisableCollision_C")
	}
	static class BP_Atom_DisableCollision::UBP_Atom_DisableCollision_C* GetDefaultObj()
	{
		return GetDefaultObjImpl<BP_Atom_DisableCollision::UBP_Atom_DisableCollision_C>();
	}
};
DUMPER7_ASSERTS_BP_Atom_DisableCollision__UBP_Atom_DisableCollision_C;

SDK_NAMESPACE_END
