#pragma once

/*
* SDK generated by Dumper-7
*
* https://github.com/Encryqed/Dumper-7
*/

// Package: BP_AbilityDamageType_E_Cielle

#include "Basic.hpp"

#include "PMGame_classes.hpp"


SDK_NAMESPACE_START

// BlueprintGeneratedClass BP_AbilityDamageType_E_Cielle.BP_AbilityDamageType_E_Cielle_C
// 0x0000 (0x0548 - 0x0548)
class UBP_AbilityDamageType_E_Cielle_C final : public UPMAbilityDamageType
{
public:
	static class UClass* StaticClass()
	{
		BP_STATIC_CLASS_IMPL("BP_AbilityDamageType_E_Cielle_C")
	}
	static const class FName& StaticName()
	{
		STATIC_NAME_IMPL(L"BP_AbilityDamageType_E_Cielle_C")
	}
	static class UBP_AbilityDamageType_E_Cielle_C* GetDefaultObj()
	{
		return GetDefaultObjImpl<UBP_AbilityDamageType_E_Cielle_C>();
	}
};
DUMPER7_ASSERTS_UBP_AbilityDamageType_E_Cielle_C;

SDK_NAMESPACE_END
