#pragma once

/*
* SDK generated by Dumper-7
*
* https://github.com/Encryqed/Dumper-7
*/

// Package: BP_BulletTrajectoryAR_208

#include "Basic.hpp"

#include "PMGame_classes.hpp"


SDK_NAMESPACE_START

// BlueprintGeneratedClass BP_BulletTrajectoryAR_208.BP_BulletTrajectoryAR_208_C
// 0x0008 (0x0330 - 0x0328)
class ABP_BulletTrajectoryAR_208_C final : public ACyBulletTrajectory
{
public:
	class USceneComponent*                        DefaultSceneRoot;                                  // 0x0328(0x0008)(BlueprintVisible, ZeroConstructor, InstancedReference, IsPlainOldData, NonTransactional, NoDestructor, HasGetValueTypeHash)

public:
	static class UClass* StaticClass()
	{
		BP_STATIC_CLASS_IMPL("BP_BulletTrajectoryAR_208_C")
	}
	static const class FName& StaticName()
	{
		STATIC_NAME_IMPL(L"BP_BulletTrajectoryAR_208_C")
	}
	static class ABP_BulletTrajectoryAR_208_C* GetDefaultObj()
	{
		return GetDefaultObjImpl<ABP_BulletTrajectoryAR_208_C>();
	}
};
DUMPER7_ASSERTS_ABP_BulletTrajectoryAR_208_C;

SDK_NAMESPACE_END
