#pragma once

/*
* SDK generated by Dumper-7
*
* https://github.com/Encryqed/Dumper-7
*/

// Package: BP_Character_Yvette

#include "Basic.hpp"


SDK_NAMESPACE_START
SDK_PARAM_NAMESPACE_START

// Function BP_Character_Yvette.BP_Character_Yvette_C.ExecuteUbergraph_BP_Character_Yvette
// 0x0004 (0x0004 - 0x0000)
struct BP_Character_Yvette_C_ExecuteUbergraph_BP_Character_Yvette final
{
public:
	int32                                         EntryPoint;                                        // 0x0000(0x0004)(BlueprintVisible, BlueprintReadOnly, Parm, ZeroConstructor, IsPlainOldData, NoDestructor, HasGetValueTypeHash)
};
DUMPER7_ASSERTS_BP_Character_Yvette_C_ExecuteUbergraph_BP_Character_Yvette;

SDK_PARAM_NAMESPACE_END
SDK_NAMESPACE_END
