#pragma once

/*
* SDK generated by Dumper-7
*
* https://github.com/Encryqed/Dumper-7
*/

// Package: BP_CheckInitializeLocationWithTarget

#include "Basic.hpp"

#include "PMGame_classes.hpp"


SDK_NAMESPACE_START

// BlueprintGeneratedClass BP_CheckInitializeLocationWithTarget.BP_CheckInitializeLocationWithTarget_C
// 0x0000 (0x0060 - 0x0060)
class UBP_CheckInitializeLocationWithTarget_C final : public UCyCheckInitializeLocation
{
public:
	static class UClass* StaticClass()
	{
		BP_STATIC_CLASS_IMPL("BP_CheckInitializeLocationWithTarget_C")
	}
	static const class FName& StaticName()
	{
		STATIC_NAME_IMPL(L"BP_CheckInitializeLocationWithTarget_C")
	}
	static class UBP_CheckInitializeLocationWithTarget_C* GetDefaultObj()
	{
		return GetDefaultObjImpl<UBP_CheckInitializeLocationWithTarget_C>();
	}
};
DUMPER7_ASSERTS_UBP_CheckInitializeLocationWithTarget_C;

SDK_NAMESPACE_END
