#pragma once

/*
* SDK generated by Dumper-7
*
* https://github.com/Encryqed/Dumper-7
*/

// Package: BP_Character_Fissioner2

#include "Basic.hpp"

#include "Engine_structs.hpp"
#include "BP_Character_Zombie_classes.hpp"


SDK_NAMESPACE_START

// BlueprintGeneratedClass BP_Character_Fissioner2.BP_Character_Fissioner2_C
// 0x0010 (0x1E70 - 0x1E60)
class ABP_Character_Fissioner2_C final : public ABP_Character_Zombie_C
{
public:
	struct FPointerToUberGraphFrame               UberGraphFrame;                                    // 0x1E58(0x0008)(ZeroConstructor, Transient, DuplicateTransient)
	class UBP_WeaponManager_Fissioner2_C*         BP_WeaponManager_Fissioner2;                       // 0x1E60(0x0008)(BlueprintVisible, ZeroConstructor, InstancedReference, IsPlainOldData, NonTransactional, NoDestructor, HasGetValueTypeHash)

public:
	void ReceiveBeginPlay();
	void ExecuteUbergraph_BP_Character_Fissioner2(int32 EntryPoint);

public:
	static class UClass* StaticClass()
	{
		BP_STATIC_CLASS_IMPL("BP_Character_Fissioner2_C")
	}
	static const class FName& StaticName()
	{
		STATIC_NAME_IMPL(L"BP_Character_Fissioner2_C")
	}
	static class ABP_Character_Fissioner2_C* GetDefaultObj()
	{
		return GetDefaultObjImpl<ABP_Character_Fissioner2_C>();
	}
};
DUMPER7_ASSERTS_ABP_Character_Fissioner2_C;

SDK_NAMESPACE_END
