#pragma once

/*
* SDK generated by Dumper-7
*
* https://github.com/Encryqed/Dumper-7
*/

// Package: BP_CheckSummonCount_Q_Yvette_0

#include "Basic.hpp"

#include "PMGame_classes.hpp"


SDK_NAMESPACE_START

// BlueprintGeneratedClass BP_CheckSummonCount_Q_Yvette.BP_CheckSummonCount_Q_Yvette_C
// 0x0000 (0x00C0 - 0x00C0)
class BP_CheckSummonCount_Q_Yvette_0::UBP_CheckSummonCount_Q_Yvette_C final : public UCyCheckSummonCount
{
public:
	static class UClass* StaticClass()
	{
		BP_STATIC_CLASS_IMPL_FULLNAME("BlueprintGeneratedClass BP_CheckSummonCount_Q_Yvette.BP_CheckSummonCount_Q_Yvette_C")
	}
	static const class FName& StaticName()
	{
		STATIC_NAME_IMPL(L"BP_CheckSummonCount_Q_Yvette_C")
	}
	static class BP_CheckSummonCount_Q_Yvette_0::UBP_CheckSummonCount_Q_Yvette_C* GetDefaultObj()
	{
		return GetDefaultObjImpl<BP_CheckSummonCount_Q_Yvette_0::UBP_CheckSummonCount_Q_Yvette_C>();
	}
};
DUMPER7_ASSERTS_BP_CheckSummonCount_Q_Yvette_0__UBP_CheckSummonCount_Q_Yvette_C;

SDK_NAMESPACE_END
