#pragma once

/*
* SDK generated by Dumper-7
*
* https://github.com/Encryqed/Dumper-7
*/

// Package: BP_Character_Chiyo

#include "Basic.hpp"

#include "Engine_structs.hpp"
#include "BP_PMCharacterBase_V3_classes.hpp"


SDK_NAMESPACE_START

// BlueprintGeneratedClass BP_Character_Chiyo.BP_Character_Chiyo_C
// 0x0020 (0x1E70 - 0x1E50)
class ABP_Character_Chiyo_C final : public ABP_PMCharacterBase_V3_C
{
public:
	struct FPointerToUberGraphFrame               UberGraphFrame;                                    // 0x1E48(0x0008)(ZeroConstructor, Transient, DuplicateTransient)
	class UCySearchTargetsComponent*              CySearchTargets;                                   // 0x1E50(0x0008)(BlueprintVisible, ZeroConstructor, InstancedReference, IsPlainOldData, NonTransactional, NoDestructor, HasGetValueTypeHash)
	class UBP_WeaponManager_Chiyo_C*              BP_WeaponManager_Chiyo;                            // 0x1E58(0x0008)(BlueprintVisible, ZeroConstructor, InstancedReference, IsPlainOldData, NonTransactional, NoDestructor, HasGetValueTypeHash)
	float                                         Blinking______0_6D509F4E4638B0CA2F67FDAD77A8A1BE;  // 0x1E60(0x0004)(ZeroConstructor, IsPlainOldData, NoDestructor, HasGetValueTypeHash)
	ETimelineDirection                            Blinking__Direction_6D509F4E4638B0CA2F67FDAD77A8A1BE; // 0x1E64(0x0001)(ZeroConstructor, IsPlainOldData, NoDestructor, HasGetValueTypeHash)
	uint8                                         Pad_1E65[0x3];                                     // 0x1E65(0x0003)(Fixing Size After Last Property [ Dumper-7 ])
	class UTimelineComponent*                     Blinking;                                          // 0x1E68(0x0008)(BlueprintVisible, ZeroConstructor, InstancedReference, IsPlainOldData, NoDestructor, HasGetValueTypeHash)

public:
	void Blinking__FinishedFunc();
	void Blinking__UpdateFunc();
	void ExecuteUbergraph_BP_Character_Chiyo(int32 EntryPoint);

public:
	static class UClass* StaticClass()
	{
		BP_STATIC_CLASS_IMPL("BP_Character_Chiyo_C")
	}
	static const class FName& StaticName()
	{
		STATIC_NAME_IMPL(L"BP_Character_Chiyo_C")
	}
	static class ABP_Character_Chiyo_C* GetDefaultObj()
	{
		return GetDefaultObjImpl<ABP_Character_Chiyo_C>();
	}
};
DUMPER7_ASSERTS_ABP_Character_Chiyo_C;

SDK_NAMESPACE_END
