#pragma once

/*
* SDK generated by Dumper-7
*
* https://github.com/Encryqed/Dumper-7
*/

// Package: BP_ChallengeStartPoint

#include "Basic.hpp"

#include "PMGame_classes.hpp"


SDK_NAMESPACE_START

// BlueprintGeneratedClass BP_ChallengeStartPoint.BP_ChallengeStartPoint_C
// 0x0008 (0x0318 - 0x0310)
class ABP_ChallengeStartPoint_C final : public ACyChallengeStartPoint
{
public:
	class USceneComponent*                        DefaultSceneRoot;                                  // 0x0310(0x0008)(BlueprintVisible, ZeroConstructor, InstancedReference, IsPlainOldData, NonTransactional, NoDestructor, HasGetValueTypeHash)

public:
	static class UClass* StaticClass()
	{
		BP_STATIC_CLASS_IMPL("BP_ChallengeStartPoint_C")
	}
	static const class FName& StaticName()
	{
		STATIC_NAME_IMPL(L"BP_ChallengeStartPoint_C")
	}
	static class ABP_ChallengeStartPoint_C* GetDefaultObj()
	{
		return GetDefaultObjImpl<ABP_ChallengeStartPoint_C>();
	}
};
DUMPER7_ASSERTS_ABP_ChallengeStartPoint_C;

SDK_NAMESPACE_END
