#pragma once

/*
* SDK generated by Dumper-7
*
* https://github.com/Encryqed/Dumper-7
*/

// Package: BP_Character_Zombie

#include "Basic.hpp"

#include "BP_PMCharacterBase_V3_classes.hpp"


SDK_NAMESPACE_START

// BlueprintGeneratedClass BP_Character_Zombie.BP_Character_Zombie_C
// 0x0010 (0x1E60 - 0x1E50)
#pragma pack(push, 0x1)
class SDK_ALIGN(0x10) ABP_Character_Zombie_C : public ABP_PMCharacterBase_V3_C
{
public:
	class UCySearchTargetsComponent*              CySearchTargets;                                   // 0x1E48(0x0008)(BlueprintVisible, ZeroConstructor, InstancedReference, IsPlainOldData, NonTransactional, NoDestructor, HasGetValueTypeHash)
	class UCyCStateMonitor*                       CyCMonitorNormal3D;                                // 0x1E50(0x0008)(BlueprintVisible, ZeroConstructor, InstancedReference, IsPlainOldData, NonTransactional, NoDestructor, HasGetValueTypeHash)

public:
	static class UClass* StaticClass()
	{
		BP_STATIC_CLASS_IMPL("BP_Character_Zombie_C")
	}
	static const class FName& StaticName()
	{
		STATIC_NAME_IMPL(L"BP_Character_Zombie_C")
	}
	static class ABP_Character_Zombie_C* GetDefaultObj()
	{
		return GetDefaultObjImpl<ABP_Character_Zombie_C>();
	}
};
#pragma pack(pop)
DUMPER7_ASSERTS_ABP_Character_Zombie_C;

SDK_NAMESPACE_END
