#pragma once

/*
* SDK generated by Dumper-7
*
* https://github.com/Encryqed/Dumper-7
*/

// Package: BP_Check2DEnergyFly

#include "Basic.hpp"

#include "PMGame_classes.hpp"


SDK_NAMESPACE_START

// BlueprintGeneratedClass BP_Check2DEnergyFly.BP_Check2DEnergyFly_C
// 0x0000 (0x0060 - 0x0060)
class UBP_Check2DEnergyFly_C final : public UCyCheck2DEnergy
{
public:
	static class UClass* StaticClass()
	{
		BP_STATIC_CLASS_IMPL("BP_Check2DEnergyFly_C")
	}
	static const class FName& StaticName()
	{
		STATIC_NAME_IMPL(L"BP_Check2DEnergyFly_C")
	}
	static class UBP_Check2DEnergyFly_C* GetDefaultObj()
	{
		return GetDefaultObjImpl<UBP_Check2DEnergyFly_C>();
	}
};
DUMPER7_ASSERTS_UBP_Check2DEnergyFly_C;

SDK_NAMESPACE_END
