#pragma once

/*
* SDK generated by Dumper-7
*
* https://github.com/Encryqed/Dumper-7
*/

// Package: BP_CheckSummon_Has_4

#include "Basic.hpp"

#include "PMGame_classes.hpp"


SDK_NAMESPACE_START

// BlueprintGeneratedClass BP_CheckSummon_Has.BP_CheckSummon_Has_C
// 0x0000 (0x00C0 - 0x00C0)
class BP_CheckSummon_Has_4::UBP_CheckSummon_Has_C final : public UCyCheckSummonCount
{
public:
	static class UClass* StaticClass()
	{
		BP_STATIC_CLASS_IMPL_FULLNAME("BlueprintGeneratedClass BP_CheckSummon_Has.BP_CheckSummon_Has_C")
	}
	static const class FName& StaticName()
	{
		STATIC_NAME_IMPL(L"BP_CheckSummon_Has_C")
	}
	static class BP_CheckSummon_Has_4::UBP_CheckSummon_Has_C* GetDefaultObj()
	{
		return GetDefaultObjImpl<BP_CheckSummon_Has_4::UBP_CheckSummon_Has_C>();
	}
};
DUMPER7_ASSERTS_BP_CheckSummon_Has_4__UBP_CheckSummon_Has_C;

SDK_NAMESPACE_END
