#pragma once

/*
* SDK generated by Dumper-7
*
* https://github.com/Encryqed/Dumper-7
*/

// Package: BP_CalculationStealArmor_Ming_ArousalTwo

#include "Basic.hpp"

#include "PMGame_classes.hpp"


SDK_NAMESPACE_START

// BlueprintGeneratedClass BP_CalculationStealArmor_Ming_ArousalTwo.BP_CalculationStealArmor_Ming_ArousalTwo_C
// 0x0000 (0x0050 - 0x0050)
class BP_CalculationStealArmor_Ming_ArousalTwo::UBP_CalculationStealArmor_Ming_ArousalTwo_C final : public UCyCalculationStealArmor
{
public:
	static class UClass* StaticClass()
	{
		BP_STATIC_CLASS_IMPL_FULLNAME("BlueprintGeneratedClass BP_CalculationStealArmor_Ming_ArousalTwo.BP_CalculationStealArmor_Ming_ArousalTwo_C")
	}
	static const class FName& StaticName()
	{
		STATIC_NAME_IMPL(L"BP_CalculationStealArmor_Ming_ArousalTwo_C")
	}
	static class BP_CalculationStealArmor_Ming_ArousalTwo::UBP_CalculationStealArmor_Ming_ArousalTwo_C* GetDefaultObj()
	{
		return GetDefaultObjImpl<BP_CalculationStealArmor_Ming_ArousalTwo::UBP_CalculationStealArmor_Ming_ArousalTwo_C>();
	}
};
DUMPER7_ASSERTS_BP_CalculationStealArmor_Ming_ArousalTwo__UBP_CalculationStealArmor_Ming_ArousalTwo_C;

SDK_NAMESPACE_END
