#pragma once

/*
* SDK generated by Dumper-7
*
* https://github.com/Encryqed/Dumper-7
*/

// Package: BP_CheckCanWall

#include "Basic.hpp"

#include "PMGame_classes.hpp"


SDK_NAMESPACE_START

// BlueprintGeneratedClass BP_CheckCanWall.BP_CheckCanWall_C
// 0x0000 (0x0058 - 0x0058)
class UBP_CheckCanWall_C final : public UCyCheckWall
{
public:
	static class UClass* StaticClass()
	{
		BP_STATIC_CLASS_IMPL("BP_CheckCanWall_C")
	}
	static const class FName& StaticName()
	{
		STATIC_NAME_IMPL(L"BP_CheckCanWall_C")
	}
	static class UBP_CheckCanWall_C* GetDefaultObj()
	{
		return GetDefaultObjImpl<UBP_CheckCanWall_C>();
	}
};
DUMPER7_ASSERTS_UBP_CheckCanWall_C;

SDK_NAMESPACE_END
