#pragma once

/*
* SDK generated by Dumper-7
*
* https://github.com/Encryqed/Dumper-7
*/

// Package: BP_CalculationTakeDamage_ArousalOne_Kanami_0

#include "Basic.hpp"

#include "PMGame_classes.hpp"


SDK_NAMESPACE_START

// BlueprintGeneratedClass BP_CalculationTakeDamage_ArousalOne_Kanami.BP_CalculationTakeDamage_ArousalOne_Kanami_C
// 0x0000 (0x0110 - 0x0110)
class BP_CalculationTakeDamage_ArousalOne_Kanami_0::UBP_CalculationTakeDamage_ArousalOne_Kanami_C final : public UCyCalculationTakeDamage
{
public:
	static class UClass* StaticClass()
	{
		BP_STATIC_CLASS_IMPL_FULLNAME("BlueprintGeneratedClass BP_CalculationTakeDamage_ArousalOne_Kanami.BP_CalculationTakeDamage_ArousalOne_Kanami_C")
	}
	static const class FName& StaticName()
	{
		STATIC_NAME_IMPL(L"BP_CalculationTakeDamage_ArousalOne_Kanami_C")
	}
	static class BP_CalculationTakeDamage_ArousalOne_Kanami_0::UBP_CalculationTakeDamage_ArousalOne_Kanami_C* GetDefaultObj()
	{
		return GetDefaultObjImpl<BP_CalculationTakeDamage_ArousalOne_Kanami_0::UBP_CalculationTakeDamage_ArousalOne_Kanami_C>();
	}
};
DUMPER7_ASSERTS_BP_CalculationTakeDamage_ArousalOne_Kanami_0__UBP_CalculationTakeDamage_ArousalOne_Kanami_C;

SDK_NAMESPACE_END
