#pragma once

/*
* SDK generated by Dumper-7
*
* https://github.com/Encryqed/Dumper-7
*/

// Package: BP_CheatSkillXConsume

#include "Basic.hpp"

#include "PMGame_classes.hpp"


SDK_NAMESPACE_START

// BlueprintGeneratedClass BP_CheatSkillXConsume.BP_CheatSkillXConsume_C
// 0x0000 (0x00B0 - 0x00B0)
class UBP_CheatSkillXConsume_C final : public UCyCheatSkillConsume
{
public:
	static class UClass* StaticClass()
	{
		BP_STATIC_CLASS_IMPL("BP_CheatSkillXConsume_C")
	}
	static const class FName& StaticName()
	{
		STATIC_NAME_IMPL(L"BP_CheatSkillXConsume_C")
	}
	static class UBP_CheatSkillXConsume_C* GetDefaultObj()
	{
		return GetDefaultObjImpl<UBP_CheatSkillXConsume_C>();
	}
};
DUMPER7_ASSERTS_UBP_CheatSkillXConsume_C;

SDK_NAMESPACE_END
