#pragma once

/*
* SDK generated by Dumper-7
*
* https://github.com/Encryqed/Dumper-7
*/

// Package: BP_CheatAmmoConsume

#include "Basic.hpp"

#include "PMGame_classes.hpp"


SDK_NAMESPACE_START

// BlueprintGeneratedClass BP_CheatAmmoConsume.BP_CheatAmmoConsume_C
// 0x0000 (0x00B0 - 0x00B0)
class UBP_CheatAmmoConsume_C final : public UCyCheatAmmoConsume
{
public:
	static class UClass* StaticClass()
	{
		BP_STATIC_CLASS_IMPL("BP_CheatAmmoConsume_C")
	}
	static const class FName& StaticName()
	{
		STATIC_NAME_IMPL(L"BP_CheatAmmoConsume_C")
	}
	static class UBP_CheatAmmoConsume_C* GetDefaultObj()
	{
		return GetDefaultObjImpl<UBP_CheatAmmoConsume_C>();
	}
};
DUMPER7_ASSERTS_UBP_CheatAmmoConsume_C;

SDK_NAMESPACE_END
