#pragma once

/*
* SDK generated by Dumper-7
*
* https://github.com/Encryqed/Dumper-7
*/

// Package: BP_CheckFly

#include "Basic.hpp"

#include "PMGame_classes.hpp"


SDK_NAMESPACE_START

// BlueprintGeneratedClass BP_CheckFly.BP_CheckFly_C
// 0x0000 (0x0058 - 0x0058)
class UBP_CheckFly_C final : public UCyCheckFly
{
public:
	static class UClass* StaticClass()
	{
		BP_STATIC_CLASS_IMPL("BP_CheckFly_C")
	}
	static const class FName& StaticName()
	{
		STATIC_NAME_IMPL(L"BP_CheckFly_C")
	}
	static class UBP_CheckFly_C* GetDefaultObj()
	{
		return GetDefaultObjImpl<UBP_CheckFly_C>();
	}
};
DUMPER7_ASSERTS_UBP_CheckFly_C;

SDK_NAMESPACE_END
