#pragma once

/*
* SDK generated by Dumper-7
*
* https://github.com/Encryqed/Dumper-7
*/

// Package: BP_DetectorLocationAlwaysTrue

#include "Basic.hpp"

#include "PMGame_classes.hpp"


SDK_NAMESPACE_START

// BlueprintGeneratedClass BP_DetectorLocationAlwaysTrue.BP_DetectorLocationAlwaysTrue_C
// 0x0000 (0x01D8 - 0x01D8)
class UBP_DetectorLocationAlwaysTrue_C final : public UCyLocationDetectorAlwaysTrue
{
public:
	static class UClass* StaticClass()
	{
		BP_STATIC_CLASS_IMPL("BP_DetectorLocationAlwaysTrue_C")
	}
	static const class FName& StaticName()
	{
		STATIC_NAME_IMPL(L"BP_DetectorLocationAlwaysTrue_C")
	}
	static class UBP_DetectorLocationAlwaysTrue_C* GetDefaultObj()
	{
		return GetDefaultObjImpl<UBP_DetectorLocationAlwaysTrue_C>();
	}
};
DUMPER7_ASSERTS_UBP_DetectorLocationAlwaysTrue_C;

SDK_NAMESPACE_END
