#pragma once

/*
* SDK generated by Dumper-7
*
* https://github.com/Encryqed/Dumper-7
*/

// Package: BP_DetectorTargets_Vertigo

#include "Basic.hpp"

#include "PMGame_classes.hpp"


SDK_NAMESPACE_START

// BlueprintGeneratedClass BP_DetectorTargets_Vertigo.BP_DetectorTargets_Vertigo_C
// 0x0000 (0x05B8 - 0x05B8)
class UBP_DetectorTargets_Vertigo_C final : public UCyTargetDetectorOverlap
{
public:
	static class UClass* StaticClass()
	{
		BP_STATIC_CLASS_IMPL("BP_DetectorTargets_Vertigo_C")
	}
	static const class FName& StaticName()
	{
		STATIC_NAME_IMPL(L"BP_DetectorTargets_Vertigo_C")
	}
	static class UBP_DetectorTargets_Vertigo_C* GetDefaultObj()
	{
		return GetDefaultObjImpl<UBP_DetectorTargets_Vertigo_C>();
	}
};
DUMPER7_ASSERTS_UBP_DetectorTargets_Vertigo_C;

SDK_NAMESPACE_END
