#pragma once

/*
* SDK generated by Dumper-7
*
* https://github.com/Encryqed/Dumper-7
*/

// Package: BP_DetectorSphere_All_0

#include "Basic.hpp"

#include "PMGame_classes.hpp"


SDK_NAMESPACE_START

// BlueprintGeneratedClass BP_DetectorSphere_All.BP_DetectorSphere_All_C
// 0x0000 (0x0618 - 0x0618)
class BP_DetectorSphere_All_0::UBP_DetectorSphere_All_C final : public UCyTargetDetectorSphere
{
public:
	static class UClass* StaticClass()
	{
		BP_STATIC_CLASS_IMPL_FULLNAME("BlueprintGeneratedClass BP_DetectorSphere_All.BP_DetectorSphere_All_C")
	}
	static const class FName& StaticName()
	{
		STATIC_NAME_IMPL(L"BP_DetectorSphere_All_C")
	}
	static class BP_DetectorSphere_All_0::UBP_DetectorSphere_All_C* GetDefaultObj()
	{
		return GetDefaultObjImpl<BP_DetectorSphere_All_0::UBP_DetectorSphere_All_C>();
	}
};
DUMPER7_ASSERTS_BP_DetectorSphere_All_0__UBP_DetectorSphere_All_C;

SDK_NAMESPACE_END
