#pragma once

/*
* SDK generated by Dumper-7
*
* https://github.com/Encryqed/Dumper-7
*/

// Package: BP_DamageType_Q_CrystalloidBeta1

#include "Basic.hpp"

#include "PMGame_classes.hpp"


SDK_NAMESPACE_START

// BlueprintGeneratedClass BP_DamageType_Q_CrystalloidBeta1.BP_DamageType_Q_CrystalloidBeta1_C
// 0x0000 (0x0548 - 0x0548)
class BP_DamageType_Q_CrystalloidBeta1::UBP_DamageType_Q_CrystalloidBeta1_C final : public UPMDamageType
{
public:
	static class UClass* StaticClass()
	{
		BP_STATIC_CLASS_IMPL_FULLNAME("BlueprintGeneratedClass BP_DamageType_Q_CrystalloidBeta1.BP_DamageType_Q_CrystalloidBeta1_C")
	}
	static const class FName& StaticName()
	{
		STATIC_NAME_IMPL(L"BP_DamageType_Q_CrystalloidBeta1_C")
	}
	static class BP_DamageType_Q_CrystalloidBeta1::UBP_DamageType_Q_CrystalloidBeta1_C* GetDefaultObj()
	{
		return GetDefaultObjImpl<BP_DamageType_Q_CrystalloidBeta1::UBP_DamageType_Q_CrystalloidBeta1_C>();
	}
};
DUMPER7_ASSERTS_BP_DamageType_Q_CrystalloidBeta1__UBP_DamageType_Q_CrystalloidBeta1_C;

SDK_NAMESPACE_END
