#pragma once

/*
* SDK generated by Dumper-7
*
* https://github.com/Encryqed/Dumper-7
*/

// Package: BP_Execution_RecoveryHeath_Fuchsia_P_0

#include "Basic.hpp"

#include "PMGame_classes.hpp"


SDK_NAMESPACE_START

// BlueprintGeneratedClass BP_Execution_RecoveryHeath_Fuchsia_P.BP_Execution_RecoveryHeath_Fuchsia_P_C
// 0x0000 (0x0270 - 0x0270)
class BP_Execution_RecoveryHeath_Fuchsia_P_0::UBP_Execution_RecoveryHeath_Fuchsia_P_C final : public UCyExecutionRecoverHealth
{
public:
	static class UClass* StaticClass()
	{
		BP_STATIC_CLASS_IMPL_FULLNAME("BlueprintGeneratedClass BP_Execution_RecoveryHeath_Fuchsia_P.BP_Execution_RecoveryHeath_Fuchsia_P_C")
	}
	static const class FName& StaticName()
	{
		STATIC_NAME_IMPL(L"BP_Execution_RecoveryHeath_Fuchsia_P_C")
	}
	static class BP_Execution_RecoveryHeath_Fuchsia_P_0::UBP_Execution_RecoveryHeath_Fuchsia_P_C* GetDefaultObj()
	{
		return GetDefaultObjImpl<BP_Execution_RecoveryHeath_Fuchsia_P_0::UBP_Execution_RecoveryHeath_Fuchsia_P_C>();
	}
};
DUMPER7_ASSERTS_BP_Execution_RecoveryHeath_Fuchsia_P_0__UBP_Execution_RecoveryHeath_Fuchsia_P_C;

SDK_NAMESPACE_END
