#pragma once

/*
* SDK generated by Dumper-7
*
* https://github.com/Encryqed/Dumper-7
*/

// Package: BP_FilterFaceAngle_Arousal2_Cielle

#include "Basic.hpp"

#include "PMGame_classes.hpp"


SDK_NAMESPACE_START

// BlueprintGeneratedClass BP_FilterFaceAngle_Arousal2_Cielle.BP_FilterFaceAngle_Arousal2_Cielle_C
// 0x0000 (0x00A0 - 0x00A0)
class UBP_FilterFaceAngle_Arousal2_Cielle_C final : public UCyFilterTargetFaceAngle
{
public:
	static class UClass* StaticClass()
	{
		BP_STATIC_CLASS_IMPL("BP_FilterFaceAngle_Arousal2_Cielle_C")
	}
	static const class FName& StaticName()
	{
		STATIC_NAME_IMPL(L"BP_FilterFaceAngle_Arousal2_Cielle_C")
	}
	static class UBP_FilterFaceAngle_Arousal2_Cielle_C* GetDefaultObj()
	{
		return GetDefaultObjImpl<UBP_FilterFaceAngle_Arousal2_Cielle_C>();
	}
};
DUMPER7_ASSERTS_UBP_FilterFaceAngle_Arousal2_Cielle_C;

SDK_NAMESPACE_END
