#pragma once

/*
* SDK generated by Dumper-7
*
* https://github.com/Encryqed/Dumper-7
*/

// Package: BP_FilterTagRequire_A3_Meredith

#include "Basic.hpp"

#include "PMGame_classes.hpp"


SDK_NAMESPACE_START

// BlueprintGeneratedClass BP_FilterTagRequire_A3_Meredith.BP_FilterTagRequire_A3_Meredith_C
// 0x0000 (0x04E0 - 0x04E0)
class BP_FilterTagRequire_A3_Meredith::UBP_FilterTagRequire_A3_Meredith_C final : public UCyFilterTagRequirements
{
public:
	static class UClass* StaticClass()
	{
		BP_STATIC_CLASS_IMPL_FULLNAME("BlueprintGeneratedClass BP_FilterTagRequire_A3_Meredith.BP_FilterTagRequire_A3_Meredith_C")
	}
	static const class FName& StaticName()
	{
		STATIC_NAME_IMPL(L"BP_FilterTagRequire_A3_Meredith_C")
	}
	static class BP_FilterTagRequire_A3_Meredith::UBP_FilterTagRequire_A3_Meredith_C* GetDefaultObj()
	{
		return GetDefaultObjImpl<BP_FilterTagRequire_A3_Meredith::UBP_FilterTagRequire_A3_Meredith_C>();
	}
};
DUMPER7_ASSERTS_BP_FilterTagRequire_A3_Meredith__UBP_FilterTagRequire_A3_Meredith_C;

SDK_NAMESPACE_END
