#pragma once

/*
* SDK generated by Dumper-7
*
* https://github.com/Encryqed/Dumper-7
*/

// Package: BP_FilterSpectator

#include "Basic.hpp"

#include "PMGame_classes.hpp"


SDK_NAMESPACE_START

// BlueprintGeneratedClass BP_FilterSpectator.BP_FilterSpectator_C
// 0x0000 (0x0050 - 0x0050)
class UBP_FilterSpectator_C final : public UCyTargetFilterSpectator
{
public:
	static class UClass* StaticClass()
	{
		BP_STATIC_CLASS_IMPL("BP_FilterSpectator_C")
	}
	static const class FName& StaticName()
	{
		STATIC_NAME_IMPL(L"BP_FilterSpectator_C")
	}
	static class UBP_FilterSpectator_C* GetDefaultObj()
	{
		return GetDefaultObjImpl<UBP_FilterSpectator_C>();
	}
};
DUMPER7_ASSERTS_UBP_FilterSpectator_C;

SDK_NAMESPACE_END
