#pragma once

/*
* SDK generated by Dumper-7
*
* https://github.com/Encryqed/Dumper-7
*/

// Package: BP_FlameGun_CameraShake_Shoulder_0

#include "Basic.hpp"

#include "Engine_classes.hpp"


SDK_NAMESPACE_START

// BlueprintGeneratedClass BP_FlameGun_CameraShake_Shoulder.BP_FlameGun_CameraShake_Shoulder_C
// 0x0000 (0x0160 - 0x0160)
class BP_FlameGun_CameraShake_Shoulder_0::UBP_FlameGun_CameraShake_Shoulder_C final : public UCameraShake
{
public:
	static class UClass* StaticClass()
	{
		BP_STATIC_CLASS_IMPL_FULLNAME("BlueprintGeneratedClass BP_FlameGun_CameraShake_Shoulder.BP_FlameGun_CameraShake_Shoulder_C")
	}
	static const class FName& StaticName()
	{
		STATIC_NAME_IMPL(L"BP_FlameGun_CameraShake_Shoulder_C")
	}
	static class BP_FlameGun_CameraShake_Shoulder_0::UBP_FlameGun_CameraShake_Shoulder_C* GetDefaultObj()
	{
		return GetDefaultObjImpl<BP_FlameGun_CameraShake_Shoulder_0::UBP_FlameGun_CameraShake_Shoulder_C>();
	}
};
DUMPER7_ASSERTS_BP_FlameGun_CameraShake_Shoulder_0__UBP_FlameGun_CameraShake_Shoulder_C;

SDK_NAMESPACE_END
