#pragma once

/*
* SDK generated by Dumper-7
*
* https://github.com/Encryqed/Dumper-7
*/

// Package: BP_FilterPlayerAndControlSummon

#include "Basic.hpp"

#include "PMGame_classes.hpp"


SDK_NAMESPACE_START

// BlueprintGeneratedClass BP_FilterPlayerAndControlSummon.BP_FilterPlayerAndControlSummon_C
// 0x0000 (0x0060 - 0x0060)
class UBP_FilterPlayerAndControlSummon_C final : public UCyFilterSpecifiedType
{
public:
	static class UClass* StaticClass()
	{
		BP_STATIC_CLASS_IMPL("BP_FilterPlayerAndControlSummon_C")
	}
	static const class FName& StaticName()
	{
		STATIC_NAME_IMPL(L"BP_FilterPlayerAndControlSummon_C")
	}
	static class UBP_FilterPlayerAndControlSummon_C* GetDefaultObj()
	{
		return GetDefaultObjImpl<UBP_FilterPlayerAndControlSummon_C>();
	}
};
DUMPER7_ASSERTS_UBP_FilterPlayerAndControlSummon_C;

SDK_NAMESPACE_END
