#pragma once

/*
* SDK generated by Dumper-7
*
* https://github.com/Encryqed/Dumper-7
*/

// Package: BP_Filter_Character_Escort2

#include "Basic.hpp"

#include "PMGame_classes.hpp"


SDK_NAMESPACE_START

// BlueprintGeneratedClass BP_Filter_Character_Escort2.BP_Filter_Character_Escort2_C
// 0x0000 (0x0060 - 0x0060)
class UBP_Filter_Character_Escort2_C final : public UCyFilterSpecifiedType
{
public:
	static class UClass* StaticClass()
	{
		BP_STATIC_CLASS_IMPL("BP_Filter_Character_Escort2_C")
	}
	static const class FName& StaticName()
	{
		STATIC_NAME_IMPL(L"BP_Filter_Character_Escort2_C")
	}
	static class UBP_Filter_Character_Escort2_C* GetDefaultObj()
	{
		return GetDefaultObjImpl<UBP_Filter_Character_Escort2_C>();
	}
};
DUMPER7_ASSERTS_UBP_Filter_Character_Escort2_C;

SDK_NAMESPACE_END
