#pragma once

/*
* SDK generated by Dumper-7
*
* https://github.com/Encryqed/Dumper-7
*/

// Package: BP_GiveAccumulator

#include "Basic.hpp"

#include "PMGame_classes.hpp"


SDK_NAMESPACE_START

// BlueprintGeneratedClass BP_GiveAccumulator.BP_GiveAccumulator_C
// 0x0000 (0x00E8 - 0x00E8)
class UBP_GiveAccumulator_C final : public UCyGAGiveAccumulator
{
public:
	static class UClass* StaticClass()
	{
		BP_STATIC_CLASS_IMPL("BP_GiveAccumulator_C")
	}
	static const class FName& StaticName()
	{
		STATIC_NAME_IMPL(L"BP_GiveAccumulator_C")
	}
	static class UBP_GiveAccumulator_C* GetDefaultObj()
	{
		return GetDefaultObjImpl<UBP_GiveAccumulator_C>();
	}
};
DUMPER7_ASSERTS_UBP_GiveAccumulator_C;

SDK_NAMESPACE_END
