#pragma once

/*
* SDK generated by Dumper-7
*
* https://github.com/Encryqed/Dumper-7
*/

// Package: BP_GPA_RemoveQuestsInGift_UniqueGift

#include "Basic.hpp"

#include "PMGame_classes.hpp"


SDK_NAMESPACE_START

// BlueprintGeneratedClass BP_GPA_RemoveQuestsInGift_UniqueGift.BP_GPA_RemoveQuestsInGift_UniqueGift_C
// 0x0000 (0x0088 - 0x0088)
class UBP_GPA_RemoveQuestsInGift_UniqueGift_C final : public UCyGPAction_RemoveQuestsInGiftSystem
{
public:
	static class UClass* StaticClass()
	{
		BP_STATIC_CLASS_IMPL("BP_GPA_RemoveQuestsInGift_UniqueGift_C")
	}
	static const class FName& StaticName()
	{
		STATIC_NAME_IMPL(L"BP_GPA_RemoveQuestsInGift_UniqueGift_C")
	}
	static class UBP_GPA_RemoveQuestsInGift_UniqueGift_C* GetDefaultObj()
	{
		return GetDefaultObjImpl<UBP_GPA_RemoveQuestsInGift_UniqueGift_C>();
	}
};
DUMPER7_ASSERTS_UBP_GPA_RemoveQuestsInGift_UniqueGift_C;

SDK_NAMESPACE_END
