#pragma once

/*
* SDK generated by Dumper-7
*
* https://github.com/Encryqed/Dumper-7
*/

// Package: BP_GATC_SummonTagRequire01_E_Yvette_0

#include "Basic.hpp"

#include "PMGame_classes.hpp"


SDK_NAMESPACE_START

// BlueprintGeneratedClass BP_GATC_SummonTagRequire01_E_Yvette.BP_GATC_SummonTagRequire01_E_Yvette_C
// 0x0000 (0x0250 - 0x0250)
class BP_GATC_SummonTagRequire01_E_Yvette_0::UBP_GATC_SummonTagRequire01_E_Yvette_C final : public UCyGATriggerCheckSummonTagRequire
{
public:
	static class UClass* StaticClass()
	{
		BP_STATIC_CLASS_IMPL_FULLNAME("BlueprintGeneratedClass BP_GATC_SummonTagRequire01_E_Yvette.BP_GATC_SummonTagRequire01_E_Yvette_C")
	}
	static const class FName& StaticName()
	{
		STATIC_NAME_IMPL(L"BP_GATC_SummonTagRequire01_E_Yvette_C")
	}
	static class BP_GATC_SummonTagRequire01_E_Yvette_0::UBP_GATC_SummonTagRequire01_E_Yvette_C* GetDefaultObj()
	{
		return GetDefaultObjImpl<BP_GATC_SummonTagRequire01_E_Yvette_0::UBP_GATC_SummonTagRequire01_E_Yvette_C>();
	}
};
DUMPER7_ASSERTS_BP_GATC_SummonTagRequire01_E_Yvette_0__UBP_GATC_SummonTagRequire01_E_Yvette_C;

SDK_NAMESPACE_END
