#pragma once

/*
* SDK generated by Dumper-7
*
* https://github.com/Encryqed/Dumper-7
*/

// Package: BP_Giver_AddEnergy_ArousalThree_Ming

#include "Basic.hpp"

#include "PMGame_classes.hpp"


SDK_NAMESPACE_START

// BlueprintGeneratedClass BP_Giver_AddEnergy_ArousalThree_Ming.BP_Giver_AddEnergy_ArousalThree_Ming_C
// 0x0000 (0x0080 - 0x0080)
class UBP_Giver_AddEnergy_ArousalThree_Ming_C final : public UCyGAGiveEffects
{
public:
	static class UClass* StaticClass()
	{
		BP_STATIC_CLASS_IMPL("BP_Giver_AddEnergy_ArousalThree_Ming_C")
	}
	static const class FName& StaticName()
	{
		STATIC_NAME_IMPL(L"BP_Giver_AddEnergy_ArousalThree_Ming_C")
	}
	static class UBP_Giver_AddEnergy_ArousalThree_Ming_C* GetDefaultObj()
	{
		return GetDefaultObjImpl<UBP_Giver_AddEnergy_ArousalThree_Ming_C>();
	}
};
DUMPER7_ASSERTS_UBP_Giver_AddEnergy_ArousalThree_Ming_C;

SDK_NAMESPACE_END
