#pragma once

/*
* SDK generated by Dumper-7
*
* https://github.com/Encryqed/Dumper-7
*/

// Package: BP_GAAtomTriggerStartCustom_X

#include "Basic.hpp"

#include "PMGame_classes.hpp"


SDK_NAMESPACE_START

// BlueprintGeneratedClass BP_GAAtomTriggerStartCustom_X.BP_GAAtomTriggerStartCustom_X_C
// 0x0000 (0x0240 - 0x0240)
class BP_GAAtomTriggerStartCustom_X::UBP_GAAtomTriggerStartCustom_X_C final : public UCyGAAtomTriggerStartCustom
{
public:
	static class UClass* StaticClass()
	{
		BP_STATIC_CLASS_IMPL_FULLNAME("BlueprintGeneratedClass BP_GAAtomTriggerStartCustom_X.BP_GAAtomTriggerStartCustom_X_C")
	}
	static const class FName& StaticName()
	{
		STATIC_NAME_IMPL(L"BP_GAAtomTriggerStartCustom_X_C")
	}
	static class BP_GAAtomTriggerStartCustom_X::UBP_GAAtomTriggerStartCustom_X_C* GetDefaultObj()
	{
		return GetDefaultObjImpl<BP_GAAtomTriggerStartCustom_X::UBP_GAAtomTriggerStartCustom_X_C>();
	}
};
DUMPER7_ASSERTS_BP_GAAtomTriggerStartCustom_X__UBP_GAAtomTriggerStartCustom_X_C;

SDK_NAMESPACE_END
