#pragma once

/*
* SDK generated by Dumper-7
*
* https://github.com/Encryqed/Dumper-7
*/

// Package: BP_GATrigger_SetWeaponDefaults_Q_Leona

#include "Basic.hpp"

#include "PMGame_classes.hpp"


SDK_NAMESPACE_START

// BlueprintGeneratedClass BP_GATrigger_SetWeaponDefaults_Q_Leona.BP_GATrigger_SetWeaponDefaults_Q_Leona_C
// 0x0000 (0x0248 - 0x0248)
class UBP_GATrigger_SetWeaponDefaults_Q_Leona_C final : public UCyGATriggerSetWeaponDefaults
{
public:
	static class UClass* StaticClass()
	{
		BP_STATIC_CLASS_IMPL("BP_GATrigger_SetWeaponDefaults_Q_Leona_C")
	}
	static const class FName& StaticName()
	{
		STATIC_NAME_IMPL(L"BP_GATrigger_SetWeaponDefaults_Q_Leona_C")
	}
	static class UBP_GATrigger_SetWeaponDefaults_Q_Leona_C* GetDefaultObj()
	{
		return GetDefaultObjImpl<UBP_GATrigger_SetWeaponDefaults_Q_Leona_C>();
	}
};
DUMPER7_ASSERTS_UBP_GATrigger_SetWeaponDefaults_Q_Leona_C;

SDK_NAMESPACE_END
