#pragma once

/*
* SDK generated by Dumper-7
*
* https://github.com/Encryqed/Dumper-7
*/

// Package: BP_GCAtomParameterParticle

#include "Basic.hpp"

#include "PMGame_classes.hpp"


SDK_NAMESPACE_START

// BlueprintGeneratedClass BP_GCAtomParameterParticle.BP_GCAtomParameterParticle_C
// 0x0000 (0x0050 - 0x0050)
class UBP_GCAtomParameterParticle_C final : public UCyGCAtomParameterParticle
{
public:
	static class UClass* StaticClass()
	{
		BP_STATIC_CLASS_IMPL("BP_GCAtomParameterParticle_C")
	}
	static const class FName& StaticName()
	{
		STATIC_NAME_IMPL(L"BP_GCAtomParameterParticle_C")
	}
	static class UBP_GCAtomParameterParticle_C* GetDefaultObj()
	{
		return GetDefaultObjImpl<UBP_GCAtomParameterParticle_C>();
	}
};
DUMPER7_ASSERTS_UBP_GCAtomParameterParticle_C;

SDK_NAMESPACE_END
