#pragma once

/*
* SDK generated by Dumper-7
*
* https://github.com/Encryqed/Dumper-7
*/

// Package: BP_GQP_StatPlayerBattleData

#include "Basic.hpp"

#include "PMGame_classes.hpp"


SDK_NAMESPACE_START

// BlueprintGeneratedClass BP_GQP_StatPlayerBattleData.BP_GQP_StatPlayerBattleData_C
// 0x0000 (0x0108 - 0x0108)
class UBP_GQP_StatPlayerBattleData_C final : public UCyGameplayQuestPack
{
public:
	static class UClass* StaticClass()
	{
		BP_STATIC_CLASS_IMPL("BP_GQP_StatPlayerBattleData_C")
	}
	static const class FName& StaticName()
	{
		STATIC_NAME_IMPL(L"BP_GQP_StatPlayerBattleData_C")
	}
	static class UBP_GQP_StatPlayerBattleData_C* GetDefaultObj()
	{
		return GetDefaultObjImpl<UBP_GQP_StatPlayerBattleData_C>();
	}
};
DUMPER7_ASSERTS_UBP_GQP_StatPlayerBattleData_C;

SDK_NAMESPACE_END
