#pragma once

/*
* SDK generated by Dumper-7
*
* https://github.com/Encryqed/Dumper-7
*/

// Package: BP_GATCheckLogic_Or_HasNotCurWeapon_X_Cielle

#include "Basic.hpp"

#include "PMGame_classes.hpp"


SDK_NAMESPACE_START

// BlueprintGeneratedClass BP_GATCheckLogic_Or_HasNotCurWeapon_X_Cielle.BP_GATCheckLogic_Or_HasNotCurWeapon_X_Cielle_C
// 0x0000 (0x0080 - 0x0080)
class UBP_GATCheckLogic_Or_HasNotCurWeapon_X_Cielle_C final : public UCyGATCheckLogic
{
public:
	static class UClass* StaticClass()
	{
		BP_STATIC_CLASS_IMPL("BP_GATCheckLogic_Or_HasNotCurWeapon_X_Cielle_C")
	}
	static const class FName& StaticName()
	{
		STATIC_NAME_IMPL(L"BP_GATCheckLogic_Or_HasNotCurWeapon_X_Cielle_C")
	}
	static class UBP_GATCheckLogic_Or_HasNotCurWeapon_X_Cielle_C* GetDefaultObj()
	{
		return GetDefaultObjImpl<UBP_GATCheckLogic_Or_HasNotCurWeapon_X_Cielle_C>();
	}
};
DUMPER7_ASSERTS_UBP_GATCheckLogic_Or_HasNotCurWeapon_X_Cielle_C;

SDK_NAMESPACE_END
