#pragma once

/*
* SDK generated by Dumper-7
*
* https://github.com/Encryqed/Dumper-7
*/

// Package: BP_GAActivateCustom_0

#include "Basic.hpp"

#include "PMGame_classes.hpp"


SDK_NAMESPACE_START

// BlueprintGeneratedClass BP_GAActivateCustom.BP_GAActivateCustom_C
// 0x0000 (0x0228 - 0x0228)
class BP_GAActivateCustom_0::UBP_GAActivateCustom_C final : public UCyGAActivateCustom
{
public:
	static class UClass* StaticClass()
	{
		BP_STATIC_CLASS_IMPL_FULLNAME("BlueprintGeneratedClass BP_GAActivateCustom.BP_GAActivateCustom_C")
	}
	static const class FName& StaticName()
	{
		STATIC_NAME_IMPL(L"BP_GAActivateCustom_C")
	}
	static class BP_GAActivateCustom_0::UBP_GAActivateCustom_C* GetDefaultObj()
	{
		return GetDefaultObjImpl<BP_GAActivateCustom_0::UBP_GAActivateCustom_C>();
	}
};
DUMPER7_ASSERTS_BP_GAActivateCustom_0__UBP_GAActivateCustom_C;

SDK_NAMESPACE_END
