#pragma once

/*
* SDK generated by Dumper-7
*
* https://github.com/Encryqed/Dumper-7
*/

// Package: BP_GSSA_EvaluateRoleTitle

#include "Basic.hpp"

#include "PMGame_classes.hpp"


SDK_NAMESPACE_START

// BlueprintGeneratedClass BP_GSSA_EvaluateRoleTitle.BP_GSSA_EvaluateRoleTitle_C
// 0x0000 (0x06D8 - 0x06D8)
class UBP_GSSA_EvaluateRoleTitle_C final : public UCyGSStateAtomEvaluateRoleTitle
{
public:
	static class UClass* StaticClass()
	{
		BP_STATIC_CLASS_IMPL("BP_GSSA_EvaluateRoleTitle_C")
	}
	static const class FName& StaticName()
	{
		STATIC_NAME_IMPL(L"BP_GSSA_EvaluateRoleTitle_C")
	}
	static class UBP_GSSA_EvaluateRoleTitle_C* GetDefaultObj()
	{
		return GetDefaultObjImpl<UBP_GSSA_EvaluateRoleTitle_C>();
	}
};
DUMPER7_ASSERTS_UBP_GSSA_EvaluateRoleTitle_C;

SDK_NAMESPACE_END
