#pragma once

/*
* SDK generated by Dumper-7
*
* https://github.com/Encryqed/Dumper-7
*/

// Package: BP_GenAtom_WaveCharacter_06

#include "Basic.hpp"

#include "BP_GenAtom_WaveCharacter_Template_classes.hpp"


SDK_NAMESPACE_START

// BlueprintGeneratedClass BP_GenAtom_WaveCharacter_06.BP_GenAtom_WaveCharacter_06_C
// 0x0000 (0x01A0 - 0x01A0)
class UBP_GenAtom_WaveCharacter_06_C final : public UBP_GenAtom_WaveCharacter_Template_C
{
public:
	static class UClass* StaticClass()
	{
		BP_STATIC_CLASS_IMPL("BP_GenAtom_WaveCharacter_06_C")
	}
	static const class FName& StaticName()
	{
		STATIC_NAME_IMPL(L"BP_GenAtom_WaveCharacter_06_C")
	}
	static class UBP_GenAtom_WaveCharacter_06_C* GetDefaultObj()
	{
		return GetDefaultObjImpl<UBP_GenAtom_WaveCharacter_06_C>();
	}
};
DUMPER7_ASSERTS_UBP_GenAtom_WaveCharacter_06_C;

SDK_NAMESPACE_END
