#pragma once

/*
* SDK generated by Dumper-7
*
* https://github.com/Encryqed/Dumper-7
*/

// Package: BP_GPEM_EventDeath_0

#include "Basic.hpp"

#include "PMGame_classes.hpp"


SDK_NAMESPACE_START

// BlueprintGeneratedClass BP_GPEM_EventDeath.BP_GPEM_EventDeath_C
// 0x0000 (0x0548 - 0x0548)
class BP_GPEM_EventDeath_0::UBP_GPEM_EventDeath_C final : public UCyGPEM_Event
{
public:
	static class UClass* StaticClass()
	{
		BP_STATIC_CLASS_IMPL_FULLNAME("BlueprintGeneratedClass BP_GPEM_EventDeath.BP_GPEM_EventDeath_C")
	}
	static const class FName& StaticName()
	{
		STATIC_NAME_IMPL(L"BP_GPEM_EventDeath_C")
	}
	static class BP_GPEM_EventDeath_0::UBP_GPEM_EventDeath_C* GetDefaultObj()
	{
		return GetDefaultObjImpl<BP_GPEM_EventDeath_0::UBP_GPEM_EventDeath_C>();
	}
};
DUMPER7_ASSERTS_BP_GPEM_EventDeath_0__UBP_GPEM_EventDeath_C;

SDK_NAMESPACE_END
