#pragma once

/*
* SDK generated by Dumper-7
*
* https://github.com/Encryqed/Dumper-7
*/

// Package: BP_GAASetMovementCustomMode

#include "Basic.hpp"

#include "PMGame_classes.hpp"


SDK_NAMESPACE_START

// BlueprintGeneratedClass BP_GAASetMovementCustomMode.BP_GAASetMovementCustomMode_C
// 0x0000 (0x0230 - 0x0230)
class UBP_GAASetMovementCustomMode_C final : public UCyGAASetMovementCustomMode
{
public:
	static class UClass* StaticClass()
	{
		BP_STATIC_CLASS_IMPL("BP_GAASetMovementCustomMode_C")
	}
	static const class FName& StaticName()
	{
		STATIC_NAME_IMPL(L"BP_GAASetMovementCustomMode_C")
	}
	static class UBP_GAASetMovementCustomMode_C* GetDefaultObj()
	{
		return GetDefaultObjImpl<UBP_GAASetMovementCustomMode_C>();
	}
};
DUMPER7_ASSERTS_UBP_GAASetMovementCustomMode_C;

SDK_NAMESPACE_END
