#pragma once

/*
* SDK generated by Dumper-7
*
* https://github.com/Encryqed/Dumper-7
*/

// Package: BP_LocationDetectorPredictPath_0

#include "Basic.hpp"

#include "PMGame_classes.hpp"


SDK_NAMESPACE_START

// BlueprintGeneratedClass BP_LocationDetectorPredictPath.BP_LocationDetectorPredictPath_C
// 0x0000 (0x01F8 - 0x01F8)
class BP_LocationDetectorPredictPath_0::UBP_LocationDetectorPredictPath_C final : public UCyLocationDetectorPredictPath
{
public:
	static class UClass* StaticClass()
	{
		BP_STATIC_CLASS_IMPL_FULLNAME("BlueprintGeneratedClass BP_LocationDetectorPredictPath.BP_LocationDetectorPredictPath_C")
	}
	static const class FName& StaticName()
	{
		STATIC_NAME_IMPL(L"BP_LocationDetectorPredictPath_C")
	}
	static class BP_LocationDetectorPredictPath_0::UBP_LocationDetectorPredictPath_C* GetDefaultObj()
	{
		return GetDefaultObjImpl<BP_LocationDetectorPredictPath_0::UBP_LocationDetectorPredictPath_C>();
	}
};
DUMPER7_ASSERTS_BP_LocationDetectorPredictPath_0__UBP_LocationDetectorPredictPath_C;

SDK_NAMESPACE_END
