#pragma once

/*
* SDK generated by Dumper-7
*
* https://github.com/Encryqed/Dumper-7
*/

// Package: BP_LocationDetectorOwnerOffset_E

#include "Basic.hpp"

#include "PMGame_classes.hpp"


SDK_NAMESPACE_START

// BlueprintGeneratedClass BP_LocationDetectorOwnerOffset_E.BP_LocationDetectorOwnerOffset_E_C
// 0x0000 (0x01E8 - 0x01E8)
class BP_LocationDetectorOwnerOffset_E::UBP_LocationDetectorOwnerOffset_E_C final : public UCyLocationDetectorOwnerLocation
{
public:
	static class UClass* StaticClass()
	{
		BP_STATIC_CLASS_IMPL_FULLNAME("BlueprintGeneratedClass BP_LocationDetectorOwnerOffset_E.BP_LocationDetectorOwnerOffset_E_C")
	}
	static const class FName& StaticName()
	{
		STATIC_NAME_IMPL(L"BP_LocationDetectorOwnerOffset_E_C")
	}
	static class BP_LocationDetectorOwnerOffset_E::UBP_LocationDetectorOwnerOffset_E_C* GetDefaultObj()
	{
		return GetDefaultObjImpl<BP_LocationDetectorOwnerOffset_E::UBP_LocationDetectorOwnerOffset_E_C>();
	}
};
DUMPER7_ASSERTS_BP_LocationDetectorOwnerOffset_E__UBP_LocationDetectorOwnerOffset_E_C;

SDK_NAMESPACE_END
