#pragma once

/*
* SDK generated by Dumper-7
*
* https://github.com/Encryqed/Dumper-7
*/

// Package: BP_LevelUpAttributeChangeExecutionCalc

#include "Basic.hpp"

#include "PMGame_classes.hpp"


SDK_NAMESPACE_START

// BlueprintGeneratedClass BP_LevelUpAttributeChangeExecutionCalc.BP_LevelUpAttributeChangeExecutionCalc_C
// 0x0000 (0x0388 - 0x0388)
class UBP_LevelUpAttributeChangeExecutionCalc_C final : public UCyLevelUpAttributeChangeExecutionCalc
{
public:
	static class UClass* StaticClass()
	{
		BP_STATIC_CLASS_IMPL("BP_LevelUpAttributeChangeExecutionCalc_C")
	}
	static const class FName& StaticName()
	{
		STATIC_NAME_IMPL(L"BP_LevelUpAttributeChangeExecutionCalc_C")
	}
	static class UBP_LevelUpAttributeChangeExecutionCalc_C* GetDefaultObj()
	{
		return GetDefaultObjImpl<UBP_LevelUpAttributeChangeExecutionCalc_C>();
	}
};
DUMPER7_ASSERTS_UBP_LevelUpAttributeChangeExecutionCalc_C;

SDK_NAMESPACE_END
