#pragma once

/*
* SDK generated by Dumper-7
*
* https://github.com/Encryqed/Dumper-7
*/

// Package: BP_Lobby_CharacterBase

#include "Basic.hpp"

#include "PMGame_classes.hpp"


SDK_NAMESPACE_START

// BlueprintGeneratedClass BP_Lobby_CharacterBase.BP_Lobby_CharacterBase_C
// 0x0000 (0x09C0 - 0x09C0)
class ABP_Lobby_CharacterBase_C : public APMLobbyCharacter
{
public:
	static class UClass* StaticClass()
	{
		BP_STATIC_CLASS_IMPL("BP_Lobby_CharacterBase_C")
	}
	static const class FName& StaticName()
	{
		STATIC_NAME_IMPL(L"BP_Lobby_CharacterBase_C")
	}
	static class ABP_Lobby_CharacterBase_C* GetDefaultObj()
	{
		return GetDefaultObjImpl<ABP_Lobby_CharacterBase_C>();
	}
};
DUMPER7_ASSERTS_ABP_Lobby_CharacterBase_C;

SDK_NAMESPACE_END
