#pragma once

/*
* SDK generated by Dumper-7
*
* https://github.com/Encryqed/Dumper-7
*/

// Package: BP_MarkPointItem

#include "Basic.hpp"

#include "PMGame_classes.hpp"


SDK_NAMESPACE_START

// BlueprintGeneratedClass BP_MarkPointItem.BP_MarkPointItem_C
// 0x0010 (0x0398 - 0x0388)
class ABP_MarkPointItem_C final : public ACyMarkPointItem
{
public:
	class UAkComponent*                           Ak;                                                // 0x0388(0x0008)(BlueprintVisible, ZeroConstructor, InstancedReference, IsPlainOldData, NonTransactional, NoDestructor, HasGetValueTypeHash)
	class UBP_CommonOverheadComponent_C*          BP_CommonOverheadComponent;                        // 0x0390(0x0008)(BlueprintVisible, ZeroConstructor, InstancedReference, IsPlainOldData, NonTransactional, NoDestructor, HasGetValueTypeHash)

public:
	static class UClass* StaticClass()
	{
		BP_STATIC_CLASS_IMPL("BP_MarkPointItem_C")
	}
	static const class FName& StaticName()
	{
		STATIC_NAME_IMPL(L"BP_MarkPointItem_C")
	}
	static class ABP_MarkPointItem_C* GetDefaultObj()
	{
		return GetDefaultObjImpl<ABP_MarkPointItem_C>();
	}
};
DUMPER7_ASSERTS_ABP_MarkPointItem_C;

SDK_NAMESPACE_END
