#pragma once

/*
* SDK generated by Dumper-7
*
* https://github.com/Encryqed/Dumper-7
*/

// Package: BP_M4A1_Fragrans_DamageType

#include "Basic.hpp"

#include "PMGame_classes.hpp"


SDK_NAMESPACE_START

// BlueprintGeneratedClass BP_M4A1_Fragrans_DamageType.BP_M4A1_Fragrans_DamageType_C
// 0x0000 (0x0548 - 0x0548)
class UBP_M4A1_Fragrans_DamageType_C final : public UPMDamageType
{
public:
	static class UClass* StaticClass()
	{
		BP_STATIC_CLASS_IMPL("BP_M4A1_Fragrans_DamageType_C")
	}
	static const class FName& StaticName()
	{
		STATIC_NAME_IMPL(L"BP_M4A1_Fragrans_DamageType_C")
	}
	static class UBP_M4A1_Fragrans_DamageType_C* GetDefaultObj()
	{
		return GetDefaultObjImpl<UBP_M4A1_Fragrans_DamageType_C>();
	}
};
DUMPER7_ASSERTS_UBP_M4A1_Fragrans_DamageType_C;

SDK_NAMESPACE_END
