#pragma once

/*
* SDK generated by Dumper-7
*
* https://github.com/Encryqed/Dumper-7
*/

// Package: BP_Payload_Snow

#include "Basic.hpp"

#include "Engine_structs.hpp"
#include "BP_Payload_Default_classes.hpp"


SDK_NAMESPACE_START

// BlueprintGeneratedClass BP_Payload_Snow.BP_Payload_Snow_C
// 0x0010 (0x0DE0 - 0x0DD0)
class ABP_Payload_Snow_C final : public ABP_Payload_Default_C
{
public:
	struct FPointerToUberGraphFrame               UberGraphFrame_BP_Payload_Snow_C;                  // 0x0DD0(0x0008)(ZeroConstructor, Transient, DuplicateTransient)

public:
	void ReceiveBeginPlay();
	void ExecuteUbergraph_BP_Payload_Snow(int32 EntryPoint);

public:
	static class UClass* StaticClass()
	{
		BP_STATIC_CLASS_IMPL("BP_Payload_Snow_C")
	}
	static const class FName& StaticName()
	{
		STATIC_NAME_IMPL(L"BP_Payload_Snow_C")
	}
	static class ABP_Payload_Snow_C* GetDefaultObj()
	{
		return GetDefaultObjImpl<ABP_Payload_Snow_C>();
	}
};
DUMPER7_ASSERTS_ABP_Payload_Snow_C;

SDK_NAMESPACE_END
