#pragma once

/*
* SDK generated by Dumper-7
*
* https://github.com/Encryqed/Dumper-7
*/

// Package: BP_Pickup18102001

#include "Basic.hpp"

#include "BP_PickupWeapon_Template_classes.hpp"


SDK_NAMESPACE_START

// BlueprintGeneratedClass BP_Pickup18102001.BP_Pickup18102001_C
// 0x0000 (0x07A0 - 0x07A0)
class ABP_Pickup18102001_C final : public ABP_PickupWeapon_Template_C
{
public:
	static class UClass* StaticClass()
	{
		BP_STATIC_CLASS_IMPL("BP_Pickup18102001_C")
	}
	static const class FName& StaticName()
	{
		STATIC_NAME_IMPL(L"BP_Pickup18102001_C")
	}
	static class ABP_Pickup18102001_C* GetDefaultObj()
	{
		return GetDefaultObjImpl<ABP_Pickup18102001_C>();
	}
};
DUMPER7_ASSERTS_ABP_Pickup18102001_C;

SDK_NAMESPACE_END
