#pragma once

/*
* SDK generated by Dumper-7
*
* https://github.com/Encryqed/Dumper-7
*/

// Package: BP_SAtom_SetDecalVisible_Q_Nobunaga_Two_Authority_0

#include "Basic.hpp"

#include "PMGame_classes.hpp"


SDK_NAMESPACE_START

// BlueprintGeneratedClass BP_SAtom_SetDecalVisible_Q_Nobunaga_Two_Authority.BP_SAtom_SetDecalVisible_Q_Nobunaga_Two_Authority_C
// 0x0000 (0x05F0 - 0x05F0)
class BP_SAtom_SetDecalVisible_Q_Nobunaga_Two_Authority_0::UBP_SAtom_SetDecalVisible_Q_Nobunaga_Two_Authority_C final : public UCySASetVisible
{
public:
	static class UClass* StaticClass()
	{
		BP_STATIC_CLASS_IMPL_FULLNAME("BlueprintGeneratedClass BP_SAtom_SetDecalVisible_Q_Nobunaga_Two_Authority.BP_SAtom_SetDecalVisible_Q_Nobunaga_Two_Authority_C")
	}
	static const class FName& StaticName()
	{
		STATIC_NAME_IMPL(L"BP_SAtom_SetDecalVisible_Q_Nobunaga_Two_Authority_C")
	}
	static class BP_SAtom_SetDecalVisible_Q_Nobunaga_Two_Authority_0::UBP_SAtom_SetDecalVisible_Q_Nobunaga_Two_Authority_C* GetDefaultObj()
	{
		return GetDefaultObjImpl<BP_SAtom_SetDecalVisible_Q_Nobunaga_Two_Authority_0::UBP_SAtom_SetDecalVisible_Q_Nobunaga_Two_Authority_C>();
	}
};
DUMPER7_ASSERTS_BP_SAtom_SetDecalVisible_Q_Nobunaga_Two_Authority_0__UBP_SAtom_SetDecalVisible_Q_Nobunaga_Two_Authority_C;

SDK_NAMESPACE_END
