#pragma once

/*
* SDK generated by Dumper-7
*
* https://github.com/Encryqed/Dumper-7
*/

// Package: BP_SSA_ShowTips_AlarmGeenade

#include "Basic.hpp"

#include "PMGame_classes.hpp"


SDK_NAMESPACE_START

// BlueprintGeneratedClass BP_SSA_ShowTips_AlarmGeenade.BP_SSA_ShowTips_AlarmGeenade_C
// 0x0000 (0x03B0 - 0x03B0)
class BP_SSA_ShowTips_AlarmGeenade::UBP_SSA_ShowTips_AlarmGeenade_C final : public UCySSAtomShowTips
{
public:
	static class UClass* StaticClass()
	{
		BP_STATIC_CLASS_IMPL_FULLNAME("BlueprintGeneratedClass BP_SSA_ShowTips_AlarmGeenade.BP_SSA_ShowTips_AlarmGeenade_C")
	}
	static const class FName& StaticName()
	{
		STATIC_NAME_IMPL(L"BP_SSA_ShowTips_AlarmGeenade_C")
	}
	static class BP_SSA_ShowTips_AlarmGeenade::UBP_SSA_ShowTips_AlarmGeenade_C* GetDefaultObj()
	{
		return GetDefaultObjImpl<BP_SSA_ShowTips_AlarmGeenade::UBP_SSA_ShowTips_AlarmGeenade_C>();
	}
};
DUMPER7_ASSERTS_BP_SSA_ShowTips_AlarmGeenade__UBP_SSA_ShowTips_AlarmGeenade_C;

SDK_NAMESPACE_END
