#pragma once

/*
* SDK generated by Dumper-7
*
* https://github.com/Encryqed/Dumper-7
*/

// Package: BP_SA_AddInfoToLinkSubSys_Katana

#include "Basic.hpp"

#include "PMGame_classes.hpp"


SDK_NAMESPACE_START

// BlueprintGeneratedClass BP_SA_AddInfoToLinkSubSys_Katana.BP_SA_AddInfoToLinkSubSys_Katana_C
// 0x0000 (0x0618 - 0x0618)
class UBP_SA_AddInfoToLinkSubSys_Katana_C final : public UCyStateAtomAddInfoToLinkSubSys
{
public:
	static class UClass* StaticClass()
	{
		BP_STATIC_CLASS_IMPL("BP_SA_AddInfoToLinkSubSys_Katana_C")
	}
	static const class FName& StaticName()
	{
		STATIC_NAME_IMPL(L"BP_SA_AddInfoToLinkSubSys_Katana_C")
	}
	static class UBP_SA_AddInfoToLinkSubSys_Katana_C* GetDefaultObj()
	{
		return GetDefaultObjImpl<UBP_SA_AddInfoToLinkSubSys_Katana_C>();
	}
};
DUMPER7_ASSERTS_UBP_SA_AddInfoToLinkSubSys_Katana_C;

SDK_NAMESPACE_END
