#pragma once

/*
* SDK generated by Dumper-7
*
* https://github.com/Encryqed/Dumper-7
*/

// Package: BP_SA_PlayInGameVoice

#include "Basic.hpp"

#include "PMGame_classes.hpp"


SDK_NAMESPACE_START

// BlueprintGeneratedClass BP_SA_PlayInGameVoice.BP_SA_PlayInGameVoice_C
// 0x0000 (0x0598 - 0x0598)
class BP_SA_PlayInGameVoice::UBP_SA_PlayInGameVoice_C final : public UCySAtomPlayInGameVoice
{
public:
	static class UClass* StaticClass()
	{
		BP_STATIC_CLASS_IMPL_FULLNAME("BlueprintGeneratedClass BP_SA_PlayInGameVoice.BP_SA_PlayInGameVoice_C")
	}
	static const class FName& StaticName()
	{
		STATIC_NAME_IMPL(L"BP_SA_PlayInGameVoice_C")
	}
	static class BP_SA_PlayInGameVoice::UBP_SA_PlayInGameVoice_C* GetDefaultObj()
	{
		return GetDefaultObjImpl<BP_SA_PlayInGameVoice::UBP_SA_PlayInGameVoice_C>();
	}
};
DUMPER7_ASSERTS_BP_SA_PlayInGameVoice__UBP_SA_PlayInGameVoice_C;

SDK_NAMESPACE_END
