#pragma once

/*
* SDK generated by Dumper-7
*
* https://github.com/Encryqed/Dumper-7
*/

// Package: BP_SSA_KillTargert

#include "Basic.hpp"

#include "PMGame_classes.hpp"


SDK_NAMESPACE_START

// BlueprintGeneratedClass BP_SSA_KillTargert.BP_SSA_KillTargert_C
// 0x0000 (0x0060 - 0x0060)
class UBP_SSA_KillTargert_C final : public UCySSAtomKill
{
public:
	static class UClass* StaticClass()
	{
		BP_STATIC_CLASS_IMPL("BP_SSA_KillTargert_C")
	}
	static const class FName& StaticName()
	{
		STATIC_NAME_IMPL(L"BP_SSA_KillTargert_C")
	}
	static class UBP_SSA_KillTargert_C* GetDefaultObj()
	{
		return GetDefaultObjImpl<UBP_SSA_KillTargert_C>();
	}
};
DUMPER7_ASSERTS_UBP_SSA_KillTargert_C;

SDK_NAMESPACE_END
