#pragma once

/*
* SDK generated by Dumper-7
*
* https://github.com/Encryqed/Dumper-7
*/

// Package: BP_SAShowMesh_Q_Shelf

#include "Basic.hpp"

#include "PMGame_classes.hpp"


SDK_NAMESPACE_START

// BlueprintGeneratedClass BP_SAShowMesh_Q_Shelf.BP_SAShowMesh_Q_Shelf_C
// 0x0000 (0x05F0 - 0x05F0)
class UBP_SAShowMesh_Q_Shelf_C final : public UCySASetVisible
{
public:
	static class UClass* StaticClass()
	{
		BP_STATIC_CLASS_IMPL("BP_SAShowMesh_Q_Shelf_C")
	}
	static const class FName& StaticName()
	{
		STATIC_NAME_IMPL(L"BP_SAShowMesh_Q_Shelf_C")
	}
	static class UBP_SAShowMesh_Q_Shelf_C* GetDefaultObj()
	{
		return GetDefaultObjImpl<UBP_SAShowMesh_Q_Shelf_C>();
	}
};
DUMPER7_ASSERTS_UBP_SAShowMesh_Q_Shelf_C;

SDK_NAMESPACE_END
