#pragma once

/*
* SDK generated by Dumper-7
*
* https://github.com/Encryqed/Dumper-7
*/

// Package: BP_SA_PlayAudioNotViewTarget

#include "Basic.hpp"

#include "PMGame_classes.hpp"


SDK_NAMESPACE_START

// BlueprintGeneratedClass BP_SA_PlayAudioNotViewTarget.BP_SA_PlayAudioNotViewTarget_C
// 0x0000 (0x05E8 - 0x05E8)
class UBP_SA_PlayAudioNotViewTarget_C final : public UCySAtomPlayAsset
{
public:
	static class UClass* StaticClass()
	{
		BP_STATIC_CLASS_IMPL("BP_SA_PlayAudioNotViewTarget_C")
	}
	static const class FName& StaticName()
	{
		STATIC_NAME_IMPL(L"BP_SA_PlayAudioNotViewTarget_C")
	}
	static class UBP_SA_PlayAudioNotViewTarget_C* GetDefaultObj()
	{
		return GetDefaultObjImpl<UBP_SA_PlayAudioNotViewTarget_C>();
	}
};
DUMPER7_ASSERTS_UBP_SA_PlayAudioNotViewTarget_C;

SDK_NAMESPACE_END
