#pragma once

/*
* SDK generated by Dumper-7
*
* https://github.com/Encryqed/Dumper-7
*/

// Package: BP_SA_CraneSprintMode

#include "Basic.hpp"

#include "PMGame_classes.hpp"


SDK_NAMESPACE_START

// BlueprintGeneratedClass BP_SA_CraneSprintMode.BP_SA_CraneSprintMode_C
// 0x0000 (0x05C0 - 0x05C0)
class BP_SA_CraneSprintMode::UBP_SA_CraneSprintMode_C final : public UCySAtomSetCraneMode
{
public:
	static class UClass* StaticClass()
	{
		BP_STATIC_CLASS_IMPL_FULLNAME("BlueprintGeneratedClass BP_SA_CraneSprintMode.BP_SA_CraneSprintMode_C")
	}
	static const class FName& StaticName()
	{
		STATIC_NAME_IMPL(L"BP_SA_CraneSprintMode_C")
	}
	static class BP_SA_CraneSprintMode::UBP_SA_CraneSprintMode_C* GetDefaultObj()
	{
		return GetDefaultObjImpl<BP_SA_CraneSprintMode::UBP_SA_CraneSprintMode_C>();
	}
};
DUMPER7_ASSERTS_BP_SA_CraneSprintMode__UBP_SA_CraneSprintMode_C;

SDK_NAMESPACE_END
