#pragma once

/*
* SDK generated by Dumper-7
*
* https://github.com/Encryqed/Dumper-7
*/

// Package: BP_SAtom_PlayForceFeedBack_ReloadSingle

#include "Basic.hpp"

#include "PMGame_classes.hpp"


SDK_NAMESPACE_START

// BlueprintGeneratedClass BP_SAtom_PlayForceFeedBack_ReloadSingle.BP_SAtom_PlayForceFeedBack_ReloadSingle_C
// 0x0000 (0x0590 - 0x0590)
class UBP_SAtom_PlayForceFeedBack_ReloadSingle_C final : public UCySAtomPlayForceFeedBack
{
public:
	static class UClass* StaticClass()
	{
		BP_STATIC_CLASS_IMPL("BP_SAtom_PlayForceFeedBack_ReloadSingle_C")
	}
	static const class FName& StaticName()
	{
		STATIC_NAME_IMPL(L"BP_SAtom_PlayForceFeedBack_ReloadSingle_C")
	}
	static class UBP_SAtom_PlayForceFeedBack_ReloadSingle_C* GetDefaultObj()
	{
		return GetDefaultObjImpl<UBP_SAtom_PlayForceFeedBack_ReloadSingle_C>();
	}
};
DUMPER7_ASSERTS_UBP_SAtom_PlayForceFeedBack_ReloadSingle_C;

SDK_NAMESPACE_END
