#pragma once

/*
* SDK generated by Dumper-7
*
* https://github.com/Encryqed/Dumper-7
*/

// Package: BP_SA_ModifyCompProperty_E_Yvette_Recover_0

#include "Basic.hpp"

#include "PMGame_classes.hpp"


SDK_NAMESPACE_START

// BlueprintGeneratedClass BP_SA_ModifyCompProperty_E_Yvette_Recover.BP_SA_ModifyCompProperty_E_Yvette_Recover_C
// 0x0000 (0x08A0 - 0x08A0)
class BP_SA_ModifyCompProperty_E_Yvette_Recover_0::UBP_SA_ModifyCompProperty_E_Yvette_Recover_C final : public UCyStateAtomModifyCompProperty
{
public:
	static class UClass* StaticClass()
	{
		BP_STATIC_CLASS_IMPL_FULLNAME("BlueprintGeneratedClass BP_SA_ModifyCompProperty_E_Yvette_Recover.BP_SA_ModifyCompProperty_E_Yvette_Recover_C")
	}
	static const class FName& StaticName()
	{
		STATIC_NAME_IMPL(L"BP_SA_ModifyCompProperty_E_Yvette_Recover_C")
	}
	static class BP_SA_ModifyCompProperty_E_Yvette_Recover_0::UBP_SA_ModifyCompProperty_E_Yvette_Recover_C* GetDefaultObj()
	{
		return GetDefaultObjImpl<BP_SA_ModifyCompProperty_E_Yvette_Recover_0::UBP_SA_ModifyCompProperty_E_Yvette_Recover_C>();
	}
};
DUMPER7_ASSERTS_BP_SA_ModifyCompProperty_E_Yvette_Recover_0__UBP_SA_ModifyCompProperty_E_Yvette_Recover_C;

SDK_NAMESPACE_END
