#pragma once

/*
* SDK generated by Dumper-7
*
* https://github.com/Encryqed/Dumper-7
*/

// Package: BP_SA_SetProjectileInitSpeed

#include "Basic.hpp"

#include "PMGame_classes.hpp"


SDK_NAMESPACE_START

// BlueprintGeneratedClass BP_SA_SetProjectileInitSpeed.BP_SA_SetProjectileInitSpeed_C
// 0x0000 (0x05A0 - 0x05A0)
class UBP_SA_SetProjectileInitSpeed_C final : public UCySAtomSetProjectileSpeed
{
public:
	static class UClass* StaticClass()
	{
		BP_STATIC_CLASS_IMPL("BP_SA_SetProjectileInitSpeed_C")
	}
	static const class FName& StaticName()
	{
		STATIC_NAME_IMPL(L"BP_SA_SetProjectileInitSpeed_C")
	}
	static class UBP_SA_SetProjectileInitSpeed_C* GetDefaultObj()
	{
		return GetDefaultObjImpl<UBP_SA_SetProjectileInitSpeed_C>();
	}
};
DUMPER7_ASSERTS_UBP_SA_SetProjectileInitSpeed_C;

SDK_NAMESPACE_END
