#pragma once

/*
* SDK generated by Dumper-7
*
* https://github.com/Encryqed/Dumper-7
*/

// Package: BP_Sky_Sphere_new

#include "Basic.hpp"

#include "BP_Sky_Sphere_new_classes.hpp"
#include "BP_Sky_Sphere_new_parameters.hpp"


SDK_NAMESPACE_START

// Function BP_Sky_Sphere_new.BP_Sky_Sphere_new_C.RefreshMaterial
// (Public, BlueprintCallable, BlueprintEvent)

void ABP_Sky_Sphere_new_C::RefreshMaterial()
{
	static class UFunction* Func = nullptr;

	if (Func == nullptr)
		Func = Class->GetFunction("BP_Sky_Sphere_new_C", "RefreshMaterial");

	UObject::ProcessEvent(Func, nullptr);
}


// Function BP_Sky_Sphere_new.BP_Sky_Sphere_new_C.UpdateSunDirection
// (Public, BlueprintCallable, BlueprintEvent)

void ABP_Sky_Sphere_new_C::UpdateSunDirection()
{
	static class UFunction* Func = nullptr;

	if (Func == nullptr)
		Func = Class->GetFunction("BP_Sky_Sphere_new_C", "UpdateSunDirection");

	UObject::ProcessEvent(Func, nullptr);
}


// Function BP_Sky_Sphere_new.BP_Sky_Sphere_new_C.UserConstructionScript
// (Event, Public, BlueprintCallable, BlueprintEvent)

void ABP_Sky_Sphere_new_C::UserConstructionScript()
{
	static class UFunction* Func = nullptr;

	if (Func == nullptr)
		Func = Class->GetFunction("BP_Sky_Sphere_new_C", "UserConstructionScript");

	UObject::ProcessEvent(Func, nullptr);
}


SDK_NAMESPACE_END
