#pragma once

/*
* SDK generated by Dumper-7
*
* https://github.com/Encryqed/Dumper-7
*/

// Package: BP_SSAtom_DataCollectionEvent_Q_Reiichi_0

#include "Basic.hpp"

#include "PMGame_classes.hpp"


SDK_NAMESPACE_START

// BlueprintGeneratedClass BP_SSAtom_DataCollectionEvent_Q_Reiichi.BP_SSAtom_DataCollectionEvent_Q_Reiichi_C
// 0x0000 (0x0058 - 0x0058)
class BP_SSAtom_DataCollectionEvent_Q_Reiichi_0::UBP_SSAtom_DataCollectionEvent_Q_Reiichi_C final : public UCySSAtomDataCollectionEvent
{
public:
	static class UClass* StaticClass()
	{
		BP_STATIC_CLASS_IMPL_FULLNAME("BlueprintGeneratedClass BP_SSAtom_DataCollectionEvent_Q_Reiichi.BP_SSAtom_DataCollectionEvent_Q_Reiichi_C")
	}
	static const class FName& StaticName()
	{
		STATIC_NAME_IMPL(L"BP_SSAtom_DataCollectionEvent_Q_Reiichi_C")
	}
	static class BP_SSAtom_DataCollectionEvent_Q_Reiichi_0::UBP_SSAtom_DataCollectionEvent_Q_Reiichi_C* GetDefaultObj()
	{
		return GetDefaultObjImpl<BP_SSAtom_DataCollectionEvent_Q_Reiichi_0::UBP_SSAtom_DataCollectionEvent_Q_Reiichi_C>();
	}
};
DUMPER7_ASSERTS_BP_SSAtom_DataCollectionEvent_Q_Reiichi_0__UBP_SSAtom_DataCollectionEvent_Q_Reiichi_C;

SDK_NAMESPACE_END
