#pragma once

/*
* SDK generated by Dumper-7
*
* https://github.com/Encryqed/Dumper-7
*/

// Package: BP_SA_CostEnergy_Q_CrystalloidAlpha

#include "Basic.hpp"

#include "PMGame_classes.hpp"


SDK_NAMESPACE_START

// BlueprintGeneratedClass BP_SA_CostEnergy_Q_CrystalloidAlpha.BP_SA_CostEnergy_Q_CrystalloidAlpha_C
// 0x0000 (0x05D8 - 0x05D8)
class UBP_SA_CostEnergy_Q_CrystalloidAlpha_C final : public UCySAtomApplyEffects
{
public:
	static class UClass* StaticClass()
	{
		BP_STATIC_CLASS_IMPL("BP_SA_CostEnergy_Q_CrystalloidAlpha_C")
	}
	static const class FName& StaticName()
	{
		STATIC_NAME_IMPL(L"BP_SA_CostEnergy_Q_CrystalloidAlpha_C")
	}
	static class UBP_SA_CostEnergy_Q_CrystalloidAlpha_C* GetDefaultObj()
	{
		return GetDefaultObjImpl<UBP_SA_CostEnergy_Q_CrystalloidAlpha_C>();
	}
};
DUMPER7_ASSERTS_UBP_SA_CostEnergy_Q_CrystalloidAlpha_C;

SDK_NAMESPACE_END
