#pragma once

/*
* SDK generated by Dumper-7
*
* https://github.com/Encryqed/Dumper-7
*/

// Package: BP_StateCheckTargetTags

#include "Basic.hpp"

#include "PMGame_classes.hpp"


SDK_NAMESPACE_START

// BlueprintGeneratedClass BP_StateCheckTargetTags.BP_StateCheckTargetTags_C
// 0x0000 (0x03C8 - 0x03C8)
class BP_StateCheckTargetTags::UBP_StateCheckTargetTags_C final : public UCyStateCheckAtomTargetTags
{
public:
	static class UClass* StaticClass()
	{
		BP_STATIC_CLASS_IMPL_FULLNAME("BlueprintGeneratedClass BP_StateCheckTargetTags.BP_StateCheckTargetTags_C")
	}
	static const class FName& StaticName()
	{
		STATIC_NAME_IMPL(L"BP_StateCheckTargetTags_C")
	}
	static class BP_StateCheckTargetTags::UBP_StateCheckTargetTags_C* GetDefaultObj()
	{
		return GetDefaultObjImpl<BP_StateCheckTargetTags::UBP_StateCheckTargetTags_C>();
	}
};
DUMPER7_ASSERTS_BP_StateCheckTargetTags__UBP_StateCheckTargetTags_C;

SDK_NAMESPACE_END
