#pragma once

/*
* SDK generated by Dumper-7
*
* https://github.com/Encryqed/Dumper-7
*/

// Package: BP_Summon_E_Ming_0

#include "Basic.hpp"


SDK_NAMESPACE_START
SDK_PARAM_NAMESPACE_START

// Function BP_Summon_E_Ming.BP_Summon_E_Ming_C.ExecuteUbergraph_BP_Summon_E_Ming
// 0x0004 (0x0004 - 0x0000)
struct BP_Summon_E_Ming_C_ExecuteUbergraph_BP_Summon_E_Ming final
{
public:
	int32                                         EntryPoint;                                        // 0x0000(0x0004)(BlueprintVisible, BlueprintReadOnly, Parm, ZeroConstructor, IsPlainOldData, NoDestructor, HasGetValueTypeHash)
};
DUMPER7_ASSERTS_BP_Summon_E_Ming_C_ExecuteUbergraph_BP_Summon_E_Ming;

SDK_PARAM_NAMESPACE_END
SDK_NAMESPACE_END
