#pragma once

/*
* SDK generated by Dumper-7
*
* https://github.com/Encryqed/Dumper-7
*/

// Package: BP_SA_AttachTo_ControlDoor

#include "Basic.hpp"

#include "PMGame_classes.hpp"


SDK_NAMESPACE_START

// BlueprintGeneratedClass BP_SA_AttachTo_ControlDoor.BP_SA_AttachTo_ControlDoor_C
// 0x0000 (0x0810 - 0x0810)
class UBP_SA_AttachTo_ControlDoor_C final : public UCySAtomAttachTo
{
public:
	static class UClass* StaticClass()
	{
		BP_STATIC_CLASS_IMPL("BP_SA_AttachTo_ControlDoor_C")
	}
	static const class FName& StaticName()
	{
		STATIC_NAME_IMPL(L"BP_SA_AttachTo_ControlDoor_C")
	}
	static class UBP_SA_AttachTo_ControlDoor_C* GetDefaultObj()
	{
		return GetDefaultObjImpl<UBP_SA_AttachTo_ControlDoor_C>();
	}
};
DUMPER7_ASSERTS_UBP_SA_AttachTo_ControlDoor_C;

SDK_NAMESPACE_END
