#pragma once

/*
* SDK generated by Dumper-7
*
* https://github.com/Encryqed/Dumper-7
*/

// Package: BP_SAPlayInGameVoice_P_Yugiri

#include "Basic.hpp"

#include "PMGame_classes.hpp"


SDK_NAMESPACE_START

// BlueprintGeneratedClass BP_SAPlayInGameVoice_P_Yugiri.BP_SAPlayInGameVoice_P_Yugiri_C
// 0x0000 (0x0598 - 0x0598)
class UBP_SAPlayInGameVoice_P_Yugiri_C final : public UCySAtomPlayInGameVoice
{
public:
	static class UClass* StaticClass()
	{
		BP_STATIC_CLASS_IMPL("BP_SAPlayInGameVoice_P_Yugiri_C")
	}
	static const class FName& StaticName()
	{
		STATIC_NAME_IMPL(L"BP_SAPlayInGameVoice_P_Yugiri_C")
	}
	static class UBP_SAPlayInGameVoice_P_Yugiri_C* GetDefaultObj()
	{
		return GetDefaultObjImpl<UBP_SAPlayInGameVoice_P_Yugiri_C>();
	}
};
DUMPER7_ASSERTS_UBP_SAPlayInGameVoice_P_Yugiri_C;

SDK_NAMESPACE_END
