#pragma once

/*
* SDK generated by Dumper-7
*
* https://github.com/Encryqed/Dumper-7
*/

// Package: BP_SA_SearchTarget_PlayAudio_ArousalTwo

#include "Basic.hpp"

#include "PMGame_classes.hpp"


SDK_NAMESPACE_START

// BlueprintGeneratedClass BP_SA_SearchTarget_PlayAudio_ArousalTwo.BP_SA_SearchTarget_PlayAudio_ArousalTwo_C
// 0x0000 (0x07A0 - 0x07A0)
class UBP_SA_SearchTarget_PlayAudio_ArousalTwo_C final : public UCySAtomSearchTargets
{
public:
	static class UClass* StaticClass()
	{
		BP_STATIC_CLASS_IMPL("BP_SA_SearchTarget_PlayAudio_ArousalTwo_C")
	}
	static const class FName& StaticName()
	{
		STATIC_NAME_IMPL(L"BP_SA_SearchTarget_PlayAudio_ArousalTwo_C")
	}
	static class UBP_SA_SearchTarget_PlayAudio_ArousalTwo_C* GetDefaultObj()
	{
		return GetDefaultObjImpl<UBP_SA_SearchTarget_PlayAudio_ArousalTwo_C>();
	}
};
DUMPER7_ASSERTS_UBP_SA_SearchTarget_PlayAudio_ArousalTwo_C;

SDK_NAMESPACE_END
