#pragma once

/*
* SDK generated by Dumper-7
*
* https://github.com/Encryqed/Dumper-7
*/

// Package: BP_SA_MarkAsAIMapObject

#include "Basic.hpp"

#include "PMGame_classes.hpp"


SDK_NAMESPACE_START

// BlueprintGeneratedClass BP_SA_MarkAsAIMapObject.BP_SA_MarkAsAIMapObject_C
// 0x0000 (0x0590 - 0x0590)
class BP_SA_MarkAsAIMapObject::UBP_SA_MarkAsAIMapObject_C final : public UCySAMarkAsAIMapObject
{
public:
	static class UClass* StaticClass()
	{
		BP_STATIC_CLASS_IMPL_FULLNAME("BlueprintGeneratedClass BP_SA_MarkAsAIMapObject.BP_SA_MarkAsAIMapObject_C")
	}
	static const class FName& StaticName()
	{
		STATIC_NAME_IMPL(L"BP_SA_MarkAsAIMapObject_C")
	}
	static class BP_SA_MarkAsAIMapObject::UBP_SA_MarkAsAIMapObject_C* GetDefaultObj()
	{
		return GetDefaultObjImpl<BP_SA_MarkAsAIMapObject::UBP_SA_MarkAsAIMapObject_C>();
	}
};
DUMPER7_ASSERTS_BP_SA_MarkAsAIMapObject__UBP_SA_MarkAsAIMapObject_C;

SDK_NAMESPACE_END
