#pragma once

/*
* SDK generated by Dumper-7
*
* https://github.com/Encryqed/Dumper-7
*/

// Package: BP_SA_AddForceMoveComponent

#include "Basic.hpp"

#include "PMGame_classes.hpp"


SDK_NAMESPACE_START

// BlueprintGeneratedClass BP_SA_AddForceMoveComponent.BP_SA_AddForceMoveComponent_C
// 0x0000 (0x05C8 - 0x05C8)
class UBP_SA_AddForceMoveComponent_C final : public UCySAtomAddForceMoveComponent
{
public:
	static class UClass* StaticClass()
	{
		BP_STATIC_CLASS_IMPL("BP_SA_AddForceMoveComponent_C")
	}
	static const class FName& StaticName()
	{
		STATIC_NAME_IMPL(L"BP_SA_AddForceMoveComponent_C")
	}
	static class UBP_SA_AddForceMoveComponent_C* GetDefaultObj()
	{
		return GetDefaultObjImpl<UBP_SA_AddForceMoveComponent_C>();
	}
};
DUMPER7_ASSERTS_UBP_SA_AddForceMoveComponent_C;

SDK_NAMESPACE_END
