#pragma once

/*
* SDK generated by Dumper-7
*
* https://github.com/Encryqed/Dumper-7
*/

// Package: BP_SearchTargets_Q_KokonaShiKI

#include "Basic.hpp"

#include "PMGame_classes.hpp"


SDK_NAMESPACE_START

// BlueprintGeneratedClass BP_SearchTargets_Q_KokonaShiKI.BP_SearchTargets_Q_KokonaShiKI_C
// 0x0000 (0x07A0 - 0x07A0)
class BP_SearchTargets_Q_KokonaShiKI::UBP_SearchTargets_Q_KokonaShiKI_C final : public UCySAtomSearchTargets
{
public:
	static class UClass* StaticClass()
	{
		BP_STATIC_CLASS_IMPL_FULLNAME("BlueprintGeneratedClass BP_SearchTargets_Q_KokonaShiKI.BP_SearchTargets_Q_KokonaShiKI_C")
	}
	static const class FName& StaticName()
	{
		STATIC_NAME_IMPL(L"BP_SearchTargets_Q_KokonaShiKI_C")
	}
	static class BP_SearchTargets_Q_KokonaShiKI::UBP_SearchTargets_Q_KokonaShiKI_C* GetDefaultObj()
	{
		return GetDefaultObjImpl<BP_SearchTargets_Q_KokonaShiKI::UBP_SearchTargets_Q_KokonaShiKI_C>();
	}
};
DUMPER7_ASSERTS_BP_SearchTargets_Q_KokonaShiKI__UBP_SearchTargets_Q_KokonaShiKI_C;

SDK_NAMESPACE_END
