#pragma once

/*
* SDK generated by Dumper-7
*
* https://github.com/Encryqed/Dumper-7
*/

// Package: BP_SA_SearchTargets_CharacterTeam0_Payload

#include "Basic.hpp"

#include "PMGame_classes.hpp"


SDK_NAMESPACE_START

// BlueprintGeneratedClass BP_SA_SearchTargets_CharacterTeam0_Payload.BP_SA_SearchTargets_CharacterTeam0_Payload_C
// 0x0000 (0x07F0 - 0x07F0)
class UBP_SA_SearchTargets_CharacterTeam0_Payload_C final : public UCySAtomSearchTargetsWithDetectorSwitcher
{
public:
	static class UClass* StaticClass()
	{
		BP_STATIC_CLASS_IMPL("BP_SA_SearchTargets_CharacterTeam0_Payload_C")
	}
	static const class FName& StaticName()
	{
		STATIC_NAME_IMPL(L"BP_SA_SearchTargets_CharacterTeam0_Payload_C")
	}
	static class UBP_SA_SearchTargets_CharacterTeam0_Payload_C* GetDefaultObj()
	{
		return GetDefaultObjImpl<UBP_SA_SearchTargets_CharacterTeam0_Payload_C>();
	}
};
DUMPER7_ASSERTS_UBP_SA_SearchTargets_CharacterTeam0_Payload_C;

SDK_NAMESPACE_END
