#pragma once

/*
* SDK generated by Dumper-7
*
* https://github.com/Encryqed/Dumper-7
*/

// Package: BP_SAtom_DamageProtect_Butterfly_0

#include "Basic.hpp"

#include "PMGame_classes.hpp"


SDK_NAMESPACE_START

// BlueprintGeneratedClass BP_SAtom_DamageProtect_Butterfly.BP_SAtom_DamageProtect_Butterfly_C
// 0x0000 (0x05C0 - 0x05C0)
class BP_SAtom_DamageProtect_Butterfly_0::UBP_SAtom_DamageProtect_Butterfly_C final : public UCyStateAtomProtect
{
public:
	static class UClass* StaticClass()
	{
		BP_STATIC_CLASS_IMPL_FULLNAME("BlueprintGeneratedClass BP_SAtom_DamageProtect_Butterfly.BP_SAtom_DamageProtect_Butterfly_C")
	}
	static const class FName& StaticName()
	{
		STATIC_NAME_IMPL(L"BP_SAtom_DamageProtect_Butterfly_C")
	}
	static class BP_SAtom_DamageProtect_Butterfly_0::UBP_SAtom_DamageProtect_Butterfly_C* GetDefaultObj()
	{
		return GetDefaultObjImpl<BP_SAtom_DamageProtect_Butterfly_0::UBP_SAtom_DamageProtect_Butterfly_C>();
	}
};
DUMPER7_ASSERTS_BP_SAtom_DamageProtect_Butterfly_0__UBP_SAtom_DamageProtect_Butterfly_C;

SDK_NAMESPACE_END
