#pragma once

/*
* SDK generated by Dumper-7
*
* https://github.com/Encryqed/Dumper-7
*/

// Package: BP_SAtom_SearchTarget_Instigator_1

#include "Basic.hpp"

#include "PMGame_classes.hpp"


SDK_NAMESPACE_START

// BlueprintGeneratedClass BP_SAtom_SearchTarget_Instigator.BP_SAtom_SearchTarget_Instigator_C
// 0x0000 (0x07A0 - 0x07A0)
class BP_SAtom_SearchTarget_Instigator_1::UBP_SAtom_SearchTarget_Instigator_C final : public UCySAtomSearchTargets
{
public:
	static class UClass* StaticClass()
	{
		BP_STATIC_CLASS_IMPL_FULLNAME("BlueprintGeneratedClass BP_SAtom_SearchTarget_Instigator.BP_SAtom_SearchTarget_Instigator_C")
	}
	static const class FName& StaticName()
	{
		STATIC_NAME_IMPL(L"BP_SAtom_SearchTarget_Instigator_C")
	}
	static class BP_SAtom_SearchTarget_Instigator_1::UBP_SAtom_SearchTarget_Instigator_C* GetDefaultObj()
	{
		return GetDefaultObjImpl<BP_SAtom_SearchTarget_Instigator_1::UBP_SAtom_SearchTarget_Instigator_C>();
	}
};
DUMPER7_ASSERTS_BP_SAtom_SearchTarget_Instigator_1__UBP_SAtom_SearchTarget_Instigator_C;

SDK_NAMESPACE_END
