#pragma once

/*
* SDK generated by Dumper-7
*
* https://github.com/Encryqed/Dumper-7
*/

// Package: BP_SAAttack_Q_Audery_Two

#include "Basic.hpp"

#include "PMGame_classes.hpp"


SDK_NAMESPACE_START

// BlueprintGeneratedClass BP_SAAttack_Q_Audery_Two.BP_SAAttack_Q_Audery_Two_C
// 0x0000 (0x05A8 - 0x05A8)
class UBP_SAAttack_Q_Audery_Two_C final : public UCyStateAtomAttack
{
public:
	static class UClass* StaticClass()
	{
		BP_STATIC_CLASS_IMPL("BP_SAAttack_Q_Audery_Two_C")
	}
	static const class FName& StaticName()
	{
		STATIC_NAME_IMPL(L"BP_SAAttack_Q_Audery_Two_C")
	}
	static class UBP_SAAttack_Q_Audery_Two_C* GetDefaultObj()
	{
		return GetDefaultObjImpl<UBP_SAAttack_Q_Audery_Two_C>();
	}
};
DUMPER7_ASSERTS_UBP_SAAttack_Q_Audery_Two_C;

SDK_NAMESPACE_END
