#pragma once

/*
* SDK generated by Dumper-7
*
* https://github.com/Encryqed/Dumper-7
*/

// Package: BP_SA_EdgeScreenEffect_Meredith_E_0

#include "Basic.hpp"

#include "PMGame_classes.hpp"


SDK_NAMESPACE_START

// BlueprintGeneratedClass BP_SA_EdgeScreenEffect_Meredith_E.BP_SA_EdgeScreenEffect_Meredith_E_C
// 0x0000 (0x05B8 - 0x05B8)
class BP_SA_EdgeScreenEffect_Meredith_E_0::UBP_SA_EdgeScreenEffect_Meredith_E_C final : public UCySAEdgeScreenEffect
{
public:
	static class UClass* StaticClass()
	{
		BP_STATIC_CLASS_IMPL_FULLNAME("BlueprintGeneratedClass BP_SA_EdgeScreenEffect_Meredith_E.BP_SA_EdgeScreenEffect_Meredith_E_C")
	}
	static const class FName& StaticName()
	{
		STATIC_NAME_IMPL(L"BP_SA_EdgeScreenEffect_Meredith_E_C")
	}
	static class BP_SA_EdgeScreenEffect_Meredith_E_0::UBP_SA_EdgeScreenEffect_Meredith_E_C* GetDefaultObj()
	{
		return GetDefaultObjImpl<BP_SA_EdgeScreenEffect_Meredith_E_0::UBP_SA_EdgeScreenEffect_Meredith_E_C>();
	}
};
DUMPER7_ASSERTS_BP_SA_EdgeScreenEffect_Meredith_E_0__UBP_SA_EdgeScreenEffect_Meredith_E_C;

SDK_NAMESPACE_END
