#pragma once

/*
* SDK generated by Dumper-7
*
* https://github.com/Encryqed/Dumper-7
*/

// Package: BP_Shared_GSEA_MatchInitialization_AddNowRound

#include "Basic.hpp"

#include "PMGame_classes.hpp"


SDK_NAMESPACE_START

// BlueprintGeneratedClass BP_Shared_GSEA_MatchInitialization_AddNowRound.BP_Shared_GSEA_MatchInitialization_AddNowRound_C
// 0x0000 (0x03D8 - 0x03D8)
class UBP_Shared_GSEA_MatchInitialization_AddNowRound_C final : public UCyGSEventAtomMatchInitialization
{
public:
	static class UClass* StaticClass()
	{
		BP_STATIC_CLASS_IMPL("BP_Shared_GSEA_MatchInitialization_AddNowRound_C")
	}
	static const class FName& StaticName()
	{
		STATIC_NAME_IMPL(L"BP_Shared_GSEA_MatchInitialization_AddNowRound_C")
	}
	static class UBP_Shared_GSEA_MatchInitialization_AddNowRound_C* GetDefaultObj()
	{
		return GetDefaultObjImpl<UBP_Shared_GSEA_MatchInitialization_AddNowRound_C>();
	}
};
DUMPER7_ASSERTS_UBP_Shared_GSEA_MatchInitialization_AddNowRound_C;

SDK_NAMESPACE_END
