#pragma once

/*
* SDK generated by Dumper-7
*
* https://github.com/Encryqed/Dumper-7
*/

// Package: BP_SA_ChangeParticalParam_Closing

#include "Basic.hpp"

#include "PMGame_classes.hpp"


SDK_NAMESPACE_START

// BlueprintGeneratedClass BP_SA_ChangeParticalParam_Closing.BP_SA_ChangeParticalParam_Closing_C
// 0x0000 (0x0620 - 0x0620)
class UBP_SA_ChangeParticalParam_Closing_C final : public UCySAChangeParticleParam
{
public:
	static class UClass* StaticClass()
	{
		BP_STATIC_CLASS_IMPL("BP_SA_ChangeParticalParam_Closing_C")
	}
	static const class FName& StaticName()
	{
		STATIC_NAME_IMPL(L"BP_SA_ChangeParticalParam_Closing_C")
	}
	static class UBP_SA_ChangeParticalParam_Closing_C* GetDefaultObj()
	{
		return GetDefaultObjImpl<UBP_SA_ChangeParticalParam_Closing_C>();
	}
};
DUMPER7_ASSERTS_UBP_SA_ChangeParticalParam_Closing_C;

SDK_NAMESPACE_END
