#pragma once

/*
* SDK generated by Dumper-7
*
* https://github.com/Encryqed/Dumper-7
*/

// Package: BP_TriggerCheckWeaponState_Equip_X_Fuchsia

#include "Basic.hpp"

#include "PMGame_classes.hpp"


SDK_NAMESPACE_START

// BlueprintGeneratedClass BP_TriggerCheckWeaponState_Equip_X_Fuchsia.BP_TriggerCheckWeaponState_Equip_X_Fuchsia_C
// 0x0000 (0x0100 - 0x0100)
class BP_TriggerCheckWeaponState_Equip_X_Fuchsia::UBP_TriggerCheckWeaponState_Equip_X_Fuchsia_C final : public UCyGATCheckWeaponState
{
public:
	static class UClass* StaticClass()
	{
		BP_STATIC_CLASS_IMPL_FULLNAME("BlueprintGeneratedClass BP_TriggerCheckWeaponState_Equip_X_Fuchsia.BP_TriggerCheckWeaponState_Equip_X_Fuchsia_C")
	}
	static const class FName& StaticName()
	{
		STATIC_NAME_IMPL(L"BP_TriggerCheckWeaponState_Equip_X_Fuchsia_C")
	}
	static class BP_TriggerCheckWeaponState_Equip_X_Fuchsia::UBP_TriggerCheckWeaponState_Equip_X_Fuchsia_C* GetDefaultObj()
	{
		return GetDefaultObjImpl<BP_TriggerCheckWeaponState_Equip_X_Fuchsia::UBP_TriggerCheckWeaponState_Equip_X_Fuchsia_C>();
	}
};
DUMPER7_ASSERTS_BP_TriggerCheckWeaponState_Equip_X_Fuchsia__UBP_TriggerCheckWeaponState_Equip_X_Fuchsia_C;

SDK_NAMESPACE_END
