#pragma once

/*
* SDK generated by Dumper-7
*
* https://github.com/Encryqed/Dumper-7
*/

// Package: BP_TriggerEndReloadOnActive_AimingNADS

#include "Basic.hpp"

#include "BP_TriggerEndReloadOnActive_AimingNADS_classes.hpp"
#include "BP_TriggerEndReloadOnActive_AimingNADS_parameters.hpp"


SDK_NAMESPACE_START

// Function BP_TriggerEndReloadOnActive_AimingNADS.BP_TriggerEndReloadOnActive_AimingNADS_C.ExecuteUbergraph_BP_TriggerEndReloadOnActive_AimingNADS
// (Final, UbergraphFunction)
// Parameters:
// int32                                   EntryPoint                                             (BlueprintVisible, BlueprintReadOnly, Parm, ZeroConstructor, IsPlainOldData, NoDestructor, HasGetValueTypeHash)

void UBP_TriggerEndReloadOnActive_AimingNADS_C::ExecuteUbergraph_BP_TriggerEndReloadOnActive_AimingNADS(int32 EntryPoint)
{
	static class UFunction* Func = nullptr;

	if (Func == nullptr)
		Func = Class->GetFunction("BP_TriggerEndReloadOnActive_AimingNADS_C", "ExecuteUbergraph_BP_TriggerEndReloadOnActive_AimingNADS");

	Params::BP_TriggerEndReloadOnActive_AimingNADS_C_ExecuteUbergraph_BP_TriggerEndReloadOnActive_AimingNADS Parms{};

	Parms.EntryPoint = EntryPoint;

	UObject::ProcessEvent(Func, &Parms);
}


SDK_NAMESPACE_END
