#pragma once

/*
* SDK generated by Dumper-7
*
* https://github.com/Encryqed/Dumper-7
*/

// Package: BP_TargetFilter_IsAttacker

#include "Basic.hpp"

#include "PMGame_classes.hpp"


SDK_NAMESPACE_START

// BlueprintGeneratedClass BP_TargetFilter_IsAttacker.BP_TargetFilter_IsAttacker_C
// 0x0000 (0x0050 - 0x0050)
class UBP_TargetFilter_IsAttacker_C final : public UCyTargetFilterGameRoleType
{
public:
	static class UClass* StaticClass()
	{
		BP_STATIC_CLASS_IMPL("BP_TargetFilter_IsAttacker_C")
	}
	static const class FName& StaticName()
	{
		STATIC_NAME_IMPL(L"BP_TargetFilter_IsAttacker_C")
	}
	static class UBP_TargetFilter_IsAttacker_C* GetDefaultObj()
	{
		return GetDefaultObjImpl<UBP_TargetFilter_IsAttacker_C>();
	}
};
DUMPER7_ASSERTS_UBP_TargetFilter_IsAttacker_C;

SDK_NAMESPACE_END
