#pragma once

/*
* SDK generated by Dumper-7
*
* https://github.com/Encryqed/Dumper-7
*/

// Package: BP_Trigger_RemoveBuff_X_Aika

#include "Basic.hpp"

#include "PMGame_classes.hpp"


SDK_NAMESPACE_START

// BlueprintGeneratedClass BP_Trigger_RemoveBuff_X_Aika.BP_Trigger_RemoveBuff_X_Aika_C
// 0x0000 (0x02A0 - 0x02A0)
class BP_Trigger_RemoveBuff_X_Aika::UBP_Trigger_RemoveBuff_X_Aika_C final : public UCyGATriggerRemoveGameEffect
{
public:
	static class UClass* StaticClass()
	{
		BP_STATIC_CLASS_IMPL_FULLNAME("BlueprintGeneratedClass BP_Trigger_RemoveBuff_X_Aika.BP_Trigger_RemoveBuff_X_Aika_C")
	}
	static const class FName& StaticName()
	{
		STATIC_NAME_IMPL(L"BP_Trigger_RemoveBuff_X_Aika_C")
	}
	static class BP_Trigger_RemoveBuff_X_Aika::UBP_Trigger_RemoveBuff_X_Aika_C* GetDefaultObj()
	{
		return GetDefaultObjImpl<BP_Trigger_RemoveBuff_X_Aika::UBP_Trigger_RemoveBuff_X_Aika_C>();
	}
};
DUMPER7_ASSERTS_BP_Trigger_RemoveBuff_X_Aika__UBP_Trigger_RemoveBuff_X_Aika_C;

SDK_NAMESPACE_END
