#pragma once

/*
* SDK generated by Dumper-7
*
* https://github.com/Encryqed/Dumper-7
*/

// Package: BP_TriggerRelease_StopUse_Ming

#include "Basic.hpp"

#include "PMGame_classes.hpp"


SDK_NAMESPACE_START

// BlueprintGeneratedClass BP_TriggerRelease_StopUse_Ming.BP_TriggerRelease_StopUse_Ming_C
// 0x0000 (0x0248 - 0x0248)
class BP_TriggerRelease_StopUse_Ming::UBP_TriggerRelease_StopUse_Ming_C final : public UCyGATriggerStopUse
{
public:
	static class UClass* StaticClass()
	{
		BP_STATIC_CLASS_IMPL_FULLNAME("BlueprintGeneratedClass BP_TriggerRelease_StopUse_Ming.BP_TriggerRelease_StopUse_Ming_C")
	}
	static const class FName& StaticName()
	{
		STATIC_NAME_IMPL(L"BP_TriggerRelease_StopUse_Ming_C")
	}
	static class BP_TriggerRelease_StopUse_Ming::UBP_TriggerRelease_StopUse_Ming_C* GetDefaultObj()
	{
		return GetDefaultObjImpl<BP_TriggerRelease_StopUse_Ming::UBP_TriggerRelease_StopUse_Ming_C>();
	}
};
DUMPER7_ASSERTS_BP_TriggerRelease_StopUse_Ming__UBP_TriggerRelease_StopUse_Ming_C;

SDK_NAMESPACE_END
