#pragma once

/*
* SDK generated by Dumper-7
*
* https://github.com/Encryqed/Dumper-7
*/

// Package: BP_TCheckSwitchedToOther

#include "Basic.hpp"

#include "PMGame_classes.hpp"


SDK_NAMESPACE_START

// BlueprintGeneratedClass BP_TCheckSwitchedToOther.BP_TCheckSwitchedToOther_C
// 0x0000 (0x0080 - 0x0080)
class UBP_TCheckSwitchedToOther_C final : public UCyGATCheckSwitchedToOther
{
public:
	static class UClass* StaticClass()
	{
		BP_STATIC_CLASS_IMPL("BP_TCheckSwitchedToOther_C")
	}
	static const class FName& StaticName()
	{
		STATIC_NAME_IMPL(L"BP_TCheckSwitchedToOther_C")
	}
	static class UBP_TCheckSwitchedToOther_C* GetDefaultObj()
	{
		return GetDefaultObjImpl<UBP_TCheckSwitchedToOther_C>();
	}
};
DUMPER7_ASSERTS_UBP_TCheckSwitchedToOther_C;

SDK_NAMESPACE_END
