#pragma once

/*
* SDK generated by Dumper-7
*
* https://github.com/Encryqed/Dumper-7
*/

// Package: BP_TargetFilter_Or

#include "Basic.hpp"

#include "PMGame_classes.hpp"


SDK_NAMESPACE_START

// BlueprintGeneratedClass BP_TargetFilter_Or.BP_TargetFilter_Or_C
// 0x0000 (0x0060 - 0x0060)
class UBP_TargetFilter_Or_C final : public UCyFilterBoolean
{
public:
	static class UClass* StaticClass()
	{
		BP_STATIC_CLASS_IMPL("BP_TargetFilter_Or_C")
	}
	static const class FName& StaticName()
	{
		STATIC_NAME_IMPL(L"BP_TargetFilter_Or_C")
	}
	static class UBP_TargetFilter_Or_C* GetDefaultObj()
	{
		return GetDefaultObjImpl<UBP_TargetFilter_Or_C>();
	}
};
DUMPER7_ASSERTS_UBP_TargetFilter_Or_C;

SDK_NAMESPACE_END
