#pragma once

/*
* SDK generated by Dumper-7
*
* https://github.com/Encryqed/Dumper-7
*/

// Package: BP_TargetDetector_Sphere_HasEnemy_OnWork_0

#include "Basic.hpp"

#include "PMGame_classes.hpp"


SDK_NAMESPACE_START

// BlueprintGeneratedClass BP_TargetDetector_Sphere_HasEnemy_OnWork.BP_TargetDetector_Sphere_HasEnemy_OnWork_C
// 0x0000 (0x0618 - 0x0618)
class BP_TargetDetector_Sphere_HasEnemy_OnWork_0::UBP_TargetDetector_Sphere_HasEnemy_OnWork_C final : public UCyTargetDetectorSphere
{
public:
	static class UClass* StaticClass()
	{
		BP_STATIC_CLASS_IMPL_FULLNAME("BlueprintGeneratedClass BP_TargetDetector_Sphere_HasEnemy_OnWork.BP_TargetDetector_Sphere_HasEnemy_OnWork_C")
	}
	static const class FName& StaticName()
	{
		STATIC_NAME_IMPL(L"BP_TargetDetector_Sphere_HasEnemy_OnWork_C")
	}
	static class BP_TargetDetector_Sphere_HasEnemy_OnWork_0::UBP_TargetDetector_Sphere_HasEnemy_OnWork_C* GetDefaultObj()
	{
		return GetDefaultObjImpl<BP_TargetDetector_Sphere_HasEnemy_OnWork_0::UBP_TargetDetector_Sphere_HasEnemy_OnWork_C>();
	}
};
DUMPER7_ASSERTS_BP_TargetDetector_Sphere_HasEnemy_OnWork_0__UBP_TargetDetector_Sphere_HasEnemy_OnWork_C;

SDK_NAMESPACE_END
