#pragma once

/*
* SDK generated by Dumper-7
*
* https://github.com/Encryqed/Dumper-7
*/

// Package: BP_TCheckAttributeEnergy

#include "Basic.hpp"

#include "PMGame_classes.hpp"


SDK_NAMESPACE_START

// BlueprintGeneratedClass BP_TCheckAttributeEnergy.BP_TCheckAttributeEnergy_C
// 0x0000 (0x00E8 - 0x00E8)
class BP_TCheckAttributeEnergy::UBP_TCheckAttributeEnergy_C final : public UCyGATCheckAttributeValue
{
public:
	static class UClass* StaticClass()
	{
		BP_STATIC_CLASS_IMPL_FULLNAME("BlueprintGeneratedClass BP_TCheckAttributeEnergy.BP_TCheckAttributeEnergy_C")
	}
	static const class FName& StaticName()
	{
		STATIC_NAME_IMPL(L"BP_TCheckAttributeEnergy_C")
	}
	static class BP_TCheckAttributeEnergy::UBP_TCheckAttributeEnergy_C* GetDefaultObj()
	{
		return GetDefaultObjImpl<BP_TCheckAttributeEnergy::UBP_TCheckAttributeEnergy_C>();
	}
};
DUMPER7_ASSERTS_BP_TCheckAttributeEnergy__UBP_TCheckAttributeEnergy_C;

SDK_NAMESPACE_END
