#pragma once

/*
* SDK generated by Dumper-7
*
* https://github.com/Encryqed/Dumper-7
*/

// Package: BP_TriggerUIEvent_InputPressedAgain_Ming

#include "Basic.hpp"

#include "BP_TriggerUIEvent_InputPressedAgain_classes.hpp"


SDK_NAMESPACE_START

// BlueprintGeneratedClass BP_TriggerUIEvent_InputPressedAgain_Ming.BP_TriggerUIEvent_InputPressedAgain_Ming_C
// 0x0000 (0x02B8 - 0x02B8)
class UBP_TriggerUIEvent_InputPressedAgain_Ming_C final : public UBP_TriggerUIEvent_InputPressedAgain_C
{
public:
	static class UClass* StaticClass()
	{
		BP_STATIC_CLASS_IMPL("BP_TriggerUIEvent_InputPressedAgain_Ming_C")
	}
	static const class FName& StaticName()
	{
		STATIC_NAME_IMPL(L"BP_TriggerUIEvent_InputPressedAgain_Ming_C")
	}
	static class UBP_TriggerUIEvent_InputPressedAgain_Ming_C* GetDefaultObj()
	{
		return GetDefaultObjImpl<UBP_TriggerUIEvent_InputPressedAgain_Ming_C>();
	}
};
DUMPER7_ASSERTS_UBP_TriggerUIEvent_InputPressedAgain_Ming_C;

SDK_NAMESPACE_END
