#pragma once

/*
* SDK generated by Dumper-7
*
* https://github.com/Encryqed/Dumper-7
*/

// Package: BP_Trigger_RemoveEffect_InjuredHealth

#include "Basic.hpp"

#include "PMGame_classes.hpp"


SDK_NAMESPACE_START

// BlueprintGeneratedClass BP_Trigger_RemoveEffect_InjuredHealth.BP_Trigger_RemoveEffect_InjuredHealth_C
// 0x0000 (0x02A0 - 0x02A0)
class BP_Trigger_RemoveEffect_InjuredHealth::UBP_Trigger_RemoveEffect_InjuredHealth_C final : public UCyGATriggerRemoveGameEffect
{
public:
	static class UClass* StaticClass()
	{
		BP_STATIC_CLASS_IMPL_FULLNAME("BlueprintGeneratedClass BP_Trigger_RemoveEffect_InjuredHealth.BP_Trigger_RemoveEffect_InjuredHealth_C")
	}
	static const class FName& StaticName()
	{
		STATIC_NAME_IMPL(L"BP_Trigger_RemoveEffect_InjuredHealth_C")
	}
	static class BP_Trigger_RemoveEffect_InjuredHealth::UBP_Trigger_RemoveEffect_InjuredHealth_C* GetDefaultObj()
	{
		return GetDefaultObjImpl<BP_Trigger_RemoveEffect_InjuredHealth::UBP_Trigger_RemoveEffect_InjuredHealth_C>();
	}
};
DUMPER7_ASSERTS_BP_Trigger_RemoveEffect_InjuredHealth__UBP_Trigger_RemoveEffect_InjuredHealth_C;

SDK_NAMESPACE_END
