#pragma once

/*
* SDK generated by Dumper-7
*
* https://github.com/Encryqed/Dumper-7
*/

// Package: BP_Trigger_EndAbility

#include "Basic.hpp"

#include "PMGame_classes.hpp"


SDK_NAMESPACE_START

// BlueprintGeneratedClass BP_Trigger_EndAbility.BP_Trigger_EndAbility_C
// 0x0000 (0x0240 - 0x0240)
class BP_Trigger_EndAbility::UBP_Trigger_EndAbility_C final : public UCyGATriggerEndAbility
{
public:
	static class UClass* StaticClass()
	{
		BP_STATIC_CLASS_IMPL_FULLNAME("BlueprintGeneratedClass BP_Trigger_EndAbility.BP_Trigger_EndAbility_C")
	}
	static const class FName& StaticName()
	{
		STATIC_NAME_IMPL(L"BP_Trigger_EndAbility_C")
	}
	static class BP_Trigger_EndAbility::UBP_Trigger_EndAbility_C* GetDefaultObj()
	{
		return GetDefaultObjImpl<BP_Trigger_EndAbility::UBP_Trigger_EndAbility_C>();
	}
};
DUMPER7_ASSERTS_BP_Trigger_EndAbility__UBP_Trigger_EndAbility_C;

SDK_NAMESPACE_END
