#pragma once

/*
* SDK generated by Dumper-7
*
* https://github.com/Encryqed/Dumper-7
*/

// Package: BP_Trigger_ApplyEffectToDamageCauser

#include "Basic.hpp"

#include "PMGame_classes.hpp"


SDK_NAMESPACE_START

// BlueprintGeneratedClass BP_Trigger_ApplyEffectToDamageCauser.BP_Trigger_ApplyEffectToDamageCauser_C
// 0x0000 (0x0268 - 0x0268)
class BP_Trigger_ApplyEffectToDamageCauser::UBP_Trigger_ApplyEffectToDamageCauser_C final : public UCyGATriggerAddEffects
{
public:
	static class UClass* StaticClass()
	{
		BP_STATIC_CLASS_IMPL_FULLNAME("BlueprintGeneratedClass BP_Trigger_ApplyEffectToDamageCauser.BP_Trigger_ApplyEffectToDamageCauser_C")
	}
	static const class FName& StaticName()
	{
		STATIC_NAME_IMPL(L"BP_Trigger_ApplyEffectToDamageCauser_C")
	}
	static class BP_Trigger_ApplyEffectToDamageCauser::UBP_Trigger_ApplyEffectToDamageCauser_C* GetDefaultObj()
	{
		return GetDefaultObjImpl<BP_Trigger_ApplyEffectToDamageCauser::UBP_Trigger_ApplyEffectToDamageCauser_C>();
	}
};
DUMPER7_ASSERTS_BP_Trigger_ApplyEffectToDamageCauser__UBP_Trigger_ApplyEffectToDamageCauser_C;

SDK_NAMESPACE_END
