#pragma once

/*
* SDK generated by Dumper-7
*
* https://github.com/Encryqed/Dumper-7
*/

// Package: BP_Trigger_Fuchsia_P_PickupEnergy_0

#include "Basic.hpp"

#include "PMGame_classes.hpp"


SDK_NAMESPACE_START

// BlueprintGeneratedClass BP_Trigger_Fuchsia_P_PickupEnergy.BP_Trigger_Fuchsia_P_PickupEnergy_C
// 0x0000 (0x0268 - 0x0268)
class BP_Trigger_Fuchsia_P_PickupEnergy_0::UBP_Trigger_Fuchsia_P_PickupEnergy_C final : public UCyGATriggerAddEffects
{
public:
	static class UClass* StaticClass()
	{
		BP_STATIC_CLASS_IMPL_FULLNAME("BlueprintGeneratedClass BP_Trigger_Fuchsia_P_PickupEnergy.BP_Trigger_Fuchsia_P_PickupEnergy_C")
	}
	static const class FName& StaticName()
	{
		STATIC_NAME_IMPL(L"BP_Trigger_Fuchsia_P_PickupEnergy_C")
	}
	static class BP_Trigger_Fuchsia_P_PickupEnergy_0::UBP_Trigger_Fuchsia_P_PickupEnergy_C* GetDefaultObj()
	{
		return GetDefaultObjImpl<BP_Trigger_Fuchsia_P_PickupEnergy_0::UBP_Trigger_Fuchsia_P_PickupEnergy_C>();
	}
};
DUMPER7_ASSERTS_BP_Trigger_Fuchsia_P_PickupEnergy_0__UBP_Trigger_Fuchsia_P_PickupEnergy_C;

SDK_NAMESPACE_END
