#pragma once

/*
* SDK generated by Dumper-7
*
* https://github.com/Encryqed/Dumper-7
*/

// Package: BP_TCheckDamageType_0

#include "Basic.hpp"

#include "PMGame_classes.hpp"


SDK_NAMESPACE_START

// BlueprintGeneratedClass BP_TCheckDamageType.BP_TCheckDamageType_C
// 0x0000 (0x0070 - 0x0070)
class BP_TCheckDamageType_0::UBP_TCheckDamageType_C final : public UCyGATCheckDamageType
{
public:
	static class UClass* StaticClass()
	{
		BP_STATIC_CLASS_IMPL_FULLNAME("BlueprintGeneratedClass BP_TCheckDamageType.BP_TCheckDamageType_C")
	}
	static const class FName& StaticName()
	{
		STATIC_NAME_IMPL(L"BP_TCheckDamageType_C")
	}
	static class BP_TCheckDamageType_0::UBP_TCheckDamageType_C* GetDefaultObj()
	{
		return GetDefaultObjImpl<BP_TCheckDamageType_0::UBP_TCheckDamageType_C>();
	}
};
DUMPER7_ASSERTS_BP_TCheckDamageType_0__UBP_TCheckDamageType_C;

SDK_NAMESPACE_END
