#pragma once

/*
* SDK generated by Dumper-7
*
* https://github.com/Encryqed/Dumper-7
*/

// Package: BP_TeamStateComponent

#include "Basic.hpp"

#include "PMGame_classes.hpp"


SDK_NAMESPACE_START

// BlueprintGeneratedClass BP_TeamStateComponent.BP_TeamStateComponent_C
// 0x0000 (0x01A8 - 0x01A8)
class UBP_TeamStateComponent_C final : public UCyTeamStateComponent
{
public:
	static class UClass* StaticClass()
	{
		BP_STATIC_CLASS_IMPL("BP_TeamStateComponent_C")
	}
	static const class FName& StaticName()
	{
		STATIC_NAME_IMPL(L"BP_TeamStateComponent_C")
	}
	static class UBP_TeamStateComponent_C* GetDefaultObj()
	{
		return GetDefaultObjImpl<UBP_TeamStateComponent_C>();
	}
};
DUMPER7_ASSERTS_UBP_TeamStateComponent_C;

SDK_NAMESPACE_END
