#pragma once

/*
* SDK generated by Dumper-7
*
* https://github.com/Encryqed/Dumper-7
*/

// Package: BP_TargetFilter_SameTeam_1

#include "Basic.hpp"

#include "PMGame_classes.hpp"


SDK_NAMESPACE_START

// BlueprintGeneratedClass BP_TargetFilter_SameTeam.BP_TargetFilter_SameTeam_C
// 0x0000 (0x0050 - 0x0050)
class BP_TargetFilter_SameTeam_1::UBP_TargetFilter_SameTeam_C final : public UCyFilterSameTeam
{
public:
	static class UClass* StaticClass()
	{
		BP_STATIC_CLASS_IMPL_FULLNAME("BlueprintGeneratedClass BP_TargetFilter_SameTeam.BP_TargetFilter_SameTeam_C")
	}
	static const class FName& StaticName()
	{
		STATIC_NAME_IMPL(L"BP_TargetFilter_SameTeam_C")
	}
	static class BP_TargetFilter_SameTeam_1::UBP_TargetFilter_SameTeam_C* GetDefaultObj()
	{
		return GetDefaultObjImpl<BP_TargetFilter_SameTeam_1::UBP_TargetFilter_SameTeam_C>();
	}
};
DUMPER7_ASSERTS_BP_TargetFilter_SameTeam_1__UBP_TargetFilter_SameTeam_C;

SDK_NAMESPACE_END
