#pragma once

/*
* SDK generated by Dumper-7
*
* https://github.com/Encryqed/Dumper-7
*/

// Package: BP_TC_AllowRelieveWallNotify

#include "Basic.hpp"

#include "PMGame_classes.hpp"


SDK_NAMESPACE_START

// BlueprintGeneratedClass BP_TC_AllowRelieveWallNotify.BP_TC_AllowRelieveWallNotify_C
// 0x0000 (0x0080 - 0x0080)
class UBP_TC_AllowRelieveWallNotify_C final : public UCyGATriggerCheckNotify
{
public:
	static class UClass* StaticClass()
	{
		BP_STATIC_CLASS_IMPL("BP_TC_AllowRelieveWallNotify_C")
	}
	static const class FName& StaticName()
	{
		STATIC_NAME_IMPL(L"BP_TC_AllowRelieveWallNotify_C")
	}
	static class UBP_TC_AllowRelieveWallNotify_C* GetDefaultObj()
	{
		return GetDefaultObjImpl<UBP_TC_AllowRelieveWallNotify_C>();
	}
};
DUMPER7_ASSERTS_UBP_TC_AllowRelieveWallNotify_C;

SDK_NAMESPACE_END
