#pragma once

/*
* SDK generated by Dumper-7
*
* https://github.com/Encryqed/Dumper-7
*/

// Package: BP_TriggerAddEffects_Aika_FullFire

#include "Basic.hpp"

#include "PMGame_classes.hpp"


SDK_NAMESPACE_START

// BlueprintGeneratedClass BP_TriggerAddEffects_Aika_FullFire.BP_TriggerAddEffects_Aika_FullFire_C
// 0x0000 (0x02A8 - 0x02A8)
class BP_TriggerAddEffects_Aika_FullFire::UBP_TriggerAddEffects_Aika_FullFire_C final : public UCyGATriggerAddGameplayEffects
{
public:
	static class UClass* StaticClass()
	{
		BP_STATIC_CLASS_IMPL_FULLNAME("BlueprintGeneratedClass BP_TriggerAddEffects_Aika_FullFire.BP_TriggerAddEffects_Aika_FullFire_C")
	}
	static const class FName& StaticName()
	{
		STATIC_NAME_IMPL(L"BP_TriggerAddEffects_Aika_FullFire_C")
	}
	static class BP_TriggerAddEffects_Aika_FullFire::UBP_TriggerAddEffects_Aika_FullFire_C* GetDefaultObj()
	{
		return GetDefaultObjImpl<BP_TriggerAddEffects_Aika_FullFire::UBP_TriggerAddEffects_Aika_FullFire_C>();
	}
};
DUMPER7_ASSERTS_BP_TriggerAddEffects_Aika_FullFire__UBP_TriggerAddEffects_Aika_FullFire_C;

SDK_NAMESPACE_END
