#pragma once

/*
* SDK generated by Dumper-7
*
* https://github.com/Encryqed/Dumper-7
*/

// Package: BP_TargetDectectorCylinder_Enhanced_Damge_0

#include "Basic.hpp"

#include "PMGame_classes.hpp"


SDK_NAMESPACE_START

// BlueprintGeneratedClass BP_TargetDectectorCylinder_Enhanced_Damge.BP_TargetDectectorCylinder_Enhanced_Damge_C
// 0x0000 (0x0640 - 0x0640)
class BP_TargetDectectorCylinder_Enhanced_Damge_0::UBP_TargetDectectorCylinder_Enhanced_Damge_C final : public UCyTargetDetectorCylinder
{
public:
	static class UClass* StaticClass()
	{
		BP_STATIC_CLASS_IMPL_FULLNAME("BlueprintGeneratedClass BP_TargetDectectorCylinder_Enhanced_Damge.BP_TargetDectectorCylinder_Enhanced_Damge_C")
	}
	static const class FName& StaticName()
	{
		STATIC_NAME_IMPL(L"BP_TargetDectectorCylinder_Enhanced_Damge_C")
	}
	static class BP_TargetDectectorCylinder_Enhanced_Damge_0::UBP_TargetDectectorCylinder_Enhanced_Damge_C* GetDefaultObj()
	{
		return GetDefaultObjImpl<BP_TargetDectectorCylinder_Enhanced_Damge_0::UBP_TargetDectectorCylinder_Enhanced_Damge_C>();
	}
};
DUMPER7_ASSERTS_BP_TargetDectectorCylinder_Enhanced_Damge_0__UBP_TargetDectectorCylinder_Enhanced_Damge_C;

SDK_NAMESPACE_END
