#pragma once

/*
* SDK generated by Dumper-7
*
* https://github.com/Encryqed/Dumper-7
*/

// Package: BP_TriggerKeepFly_WeaponAuto

#include "Basic.hpp"


SDK_NAMESPACE_START
SDK_PARAM_NAMESPACE_START

// Function BP_TriggerKeepFly_WeaponAuto.BP_TriggerKeepFly_WeaponAuto_C.ExecuteUbergraph_BP_TriggerKeepFly_WeaponAuto
// 0x0004 (0x0004 - 0x0000)
struct BP_TriggerKeepFly_WeaponAuto_C_ExecuteUbergraph_BP_TriggerKeepFly_WeaponAuto final
{
public:
	int32                                         EntryPoint;                                        // 0x0000(0x0004)(BlueprintVisible, BlueprintReadOnly, Parm, ZeroConstructor, IsPlainOldData, NoDestructor, HasGetValueTypeHash)
};
DUMPER7_ASSERTS_BP_TriggerKeepFly_WeaponAuto_C_ExecuteUbergraph_BP_TriggerKeepFly_WeaponAuto;

SDK_PARAM_NAMESPACE_END
SDK_NAMESPACE_END
