#pragma once

/*
* SDK generated by Dumper-7
*
* https://github.com/Encryqed/Dumper-7
*/

// Package: BP_TargetDetectorOverlap_Q_Leona

#include "Basic.hpp"

#include "PMGame_classes.hpp"


SDK_NAMESPACE_START

// BlueprintGeneratedClass BP_TargetDetectorOverlap_Q_Leona.BP_TargetDetectorOverlap_Q_Leona_C
// 0x0000 (0x05B8 - 0x05B8)
class UBP_TargetDetectorOverlap_Q_Leona_C final : public UCyTargetDetectorOverlap
{
public:
	static class UClass* StaticClass()
	{
		BP_STATIC_CLASS_IMPL("BP_TargetDetectorOverlap_Q_Leona_C")
	}
	static const class FName& StaticName()
	{
		STATIC_NAME_IMPL(L"BP_TargetDetectorOverlap_Q_Leona_C")
	}
	static class UBP_TargetDetectorOverlap_Q_Leona_C* GetDefaultObj()
	{
		return GetDefaultObjImpl<UBP_TargetDetectorOverlap_Q_Leona_C>();
	}
};
DUMPER7_ASSERTS_UBP_TargetDetectorOverlap_Q_Leona_C;

SDK_NAMESPACE_END
