#pragma once

/*
* SDK generated by Dumper-7
*
* https://github.com/Encryqed/Dumper-7
*/

// Package: BP_TriggerAddEffects_Nobunaga_AddQPoints_OnDeath_0

#include "Basic.hpp"

#include "PMGame_classes.hpp"


SDK_NAMESPACE_START

// BlueprintGeneratedClass BP_TriggerAddEffects_Nobunaga_AddQPoints_OnDeath.BP_TriggerAddEffects_Nobunaga_AddQPoints_OnDeath_C
// 0x0000 (0x0268 - 0x0268)
class BP_TriggerAddEffects_Nobunaga_AddQPoints_OnDeath_0::UBP_TriggerAddEffects_Nobunaga_AddQPoints_OnDeath_C final : public UCyGATriggerAddEffects
{
public:
	static class UClass* StaticClass()
	{
		BP_STATIC_CLASS_IMPL_FULLNAME("BlueprintGeneratedClass BP_TriggerAddEffects_Nobunaga_AddQPoints_OnDeath.BP_TriggerAddEffects_Nobunaga_AddQPoints_OnDeath_C")
	}
	static const class FName& StaticName()
	{
		STATIC_NAME_IMPL(L"BP_TriggerAddEffects_Nobunaga_AddQPoints_OnDeath_C")
	}
	static class BP_TriggerAddEffects_Nobunaga_AddQPoints_OnDeath_0::UBP_TriggerAddEffects_Nobunaga_AddQPoints_OnDeath_C* GetDefaultObj()
	{
		return GetDefaultObjImpl<BP_TriggerAddEffects_Nobunaga_AddQPoints_OnDeath_0::UBP_TriggerAddEffects_Nobunaga_AddQPoints_OnDeath_C>();
	}
};
DUMPER7_ASSERTS_BP_TriggerAddEffects_Nobunaga_AddQPoints_OnDeath_0__UBP_TriggerAddEffects_Nobunaga_AddQPoints_OnDeath_C;

SDK_NAMESPACE_END
