#pragma once

/*
* SDK generated by Dumper-7
*
* https://github.com/Encryqed/Dumper-7
*/

// Package: BP_TargetDetector_Self_P

#include "Basic.hpp"

#include "PMGame_classes.hpp"


SDK_NAMESPACE_START

// BlueprintGeneratedClass BP_TargetDetector_Self_P.BP_TargetDetector_Self_P_C
// 0x0000 (0x0550 - 0x0550)
class BP_TargetDetector_Self_P::UBP_TargetDetector_Self_P_C final : public UCyTargetDetectorSelf
{
public:
	static class UClass* StaticClass()
	{
		BP_STATIC_CLASS_IMPL_FULLNAME("BlueprintGeneratedClass BP_TargetDetector_Self_P.BP_TargetDetector_Self_P_C")
	}
	static const class FName& StaticName()
	{
		STATIC_NAME_IMPL(L"BP_TargetDetector_Self_P_C")
	}
	static class BP_TargetDetector_Self_P::UBP_TargetDetector_Self_P_C* GetDefaultObj()
	{
		return GetDefaultObjImpl<BP_TargetDetector_Self_P::UBP_TargetDetector_Self_P_C>();
	}
};
DUMPER7_ASSERTS_BP_TargetDetector_Self_P__UBP_TargetDetector_Self_P_C;

SDK_NAMESPACE_END
