#pragma once

/*
* SDK generated by Dumper-7
*
* https://github.com/Encryqed/Dumper-7
*/

// Package: BP_TreatmentExecutionCalculation

#include "Basic.hpp"

#include "PMGame_classes.hpp"


SDK_NAMESPACE_START

// BlueprintGeneratedClass BP_TreatmentExecutionCalculation.BP_TreatmentExecutionCalculation_C
// 0x0000 (0x00C0 - 0x00C0)
class UBP_TreatmentExecutionCalculation_C final : public UPMTreatmentExecutionCalculation
{
public:
	static class UClass* StaticClass()
	{
		BP_STATIC_CLASS_IMPL("BP_TreatmentExecutionCalculation_C")
	}
	static const class FName& StaticName()
	{
		STATIC_NAME_IMPL(L"BP_TreatmentExecutionCalculation_C")
	}
	static class UBP_TreatmentExecutionCalculation_C* GetDefaultObj()
	{
		return GetDefaultObjImpl<UBP_TreatmentExecutionCalculation_C>();
	}
};
DUMPER7_ASSERTS_UBP_TreatmentExecutionCalculation_C;

SDK_NAMESPACE_END
