#pragma once

/*
* SDK generated by Dumper-7
*
* https://github.com/Encryqed/Dumper-7
*/

// Package: BPSA_ShowNormalMesh_0

#include "Basic.hpp"

#include "PMGame_classes.hpp"


SDK_NAMESPACE_START

// BlueprintGeneratedClass BPSA_ShowNormalMesh.BPSA_ShowNormalMesh_C
// 0x0000 (0x05F0 - 0x05F0)
class BPSA_ShowNormalMesh_0::UBPSA_ShowNormalMesh_C final : public UCySASetVisible
{
public:
	static class UClass* StaticClass()
	{
		BP_STATIC_CLASS_IMPL_FULLNAME("BlueprintGeneratedClass BPSA_ShowNormalMesh.BPSA_ShowNormalMesh_C")
	}
	static const class FName& StaticName()
	{
		STATIC_NAME_IMPL(L"BPSA_ShowNormalMesh_C")
	}
	static class BPSA_ShowNormalMesh_0::UBPSA_ShowNormalMesh_C* GetDefaultObj()
	{
		return GetDefaultObjImpl<BPSA_ShowNormalMesh_0::UBPSA_ShowNormalMesh_C>();
	}
};
DUMPER7_ASSERTS_BPSA_ShowNormalMesh_0__UBPSA_ShowNormalMesh_C;

SDK_NAMESPACE_END
