#pragma once

/*
* SDK generated by Dumper-7
*
* https://github.com/Encryqed/Dumper-7
*/

// Package: BT_TCheckInstigatorTargetEnemy

#include "Basic.hpp"

#include "PMGame_classes.hpp"


SDK_NAMESPACE_START

// BlueprintGeneratedClass BT_TCheckInstigatorTargetEnemy.BT_TCheckInstigatorTargetEnemy_C
// 0x0000 (0x0068 - 0x0068)
class UBT_TCheckInstigatorTargetEnemy_C final : public UCyGATCheckInstigatorTargetEnemy
{
public:
	static class UClass* StaticClass()
	{
		BP_STATIC_CLASS_IMPL("BT_TCheckInstigatorTargetEnemy_C")
	}
	static const class FName& StaticName()
	{
		STATIC_NAME_IMPL(L"BT_TCheckInstigatorTargetEnemy_C")
	}
	static class UBT_TCheckInstigatorTargetEnemy_C* GetDefaultObj()
	{
		return GetDefaultObjImpl<UBT_TCheckInstigatorTargetEnemy_C>();
	}
};
DUMPER7_ASSERTS_UBT_TCheckInstigatorTargetEnemy_C;

SDK_NAMESPACE_END
