#pragma once

/*
* SDK generated by Dumper-7
*
* https://github.com/Encryqed/Dumper-7
*/

// Package: CD_Q_Yvette_Control

#include "Basic.hpp"

#include "PMGame_classes.hpp"


SDK_NAMESPACE_START

// BlueprintGeneratedClass CD_Q_Yvette_Control.CD_Q_Yvette_Control_C
// 0x0000 (0x10E0 - 0x10E0)
class CD_Q_Yvette_Control::UCD_Q_Yvette_Control_C final : public UCyGameplayEffect
{
public:
	static class UClass* StaticClass()
	{
		BP_STATIC_CLASS_IMPL_FULLNAME("BlueprintGeneratedClass CD_Q_Yvette_Control.CD_Q_Yvette_Control_C")
	}
	static const class FName& StaticName()
	{
		STATIC_NAME_IMPL(L"CD_Q_Yvette_Control_C")
	}
	static class CD_Q_Yvette_Control::UCD_Q_Yvette_Control_C* GetDefaultObj()
	{
		return GetDefaultObjImpl<CD_Q_Yvette_Control::UCD_Q_Yvette_Control_C>();
	}
};
DUMPER7_ASSERTS_CD_Q_Yvette_Control__UCD_Q_Yvette_Control_C;

SDK_NAMESPACE_END
