#pragma once

/*
* SDK generated by Dumper-7
*
* https://github.com/Encryqed/Dumper-7
*/

// Package: DamageType_GrenadeShield_0

#include "Basic.hpp"

#include "PMGame_classes.hpp"


SDK_NAMESPACE_START

// BlueprintGeneratedClass DamageType_GrenadeShield.DamageType_GrenadeShield_C
// 0x0000 (0x0548 - 0x0548)
class DamageType_GrenadeShield_0::UDamageType_GrenadeShield_C final : public UPMDamageType
{
public:
	static class UClass* StaticClass()
	{
		BP_STATIC_CLASS_IMPL_FULLNAME("BlueprintGeneratedClass DamageType_GrenadeShield.DamageType_GrenadeShield_C")
	}
	static const class FName& StaticName()
	{
		STATIC_NAME_IMPL(L"DamageType_GrenadeShield_C")
	}
	static class DamageType_GrenadeShield_0::UDamageType_GrenadeShield_C* GetDefaultObj()
	{
		return GetDefaultObjImpl<DamageType_GrenadeShield_0::UDamageType_GrenadeShield_C>();
	}
};
DUMPER7_ASSERTS_DamageType_GrenadeShield_0__UDamageType_GrenadeShield_C;

SDK_NAMESPACE_END
