#pragma once

/*
* SDK generated by Dumper-7
*
* https://github.com/Encryqed/Dumper-7
*/

// Package: DamageType_GrenadeInterceptor

#include "Basic.hpp"

#include "PMGame_classes.hpp"


SDK_NAMESPACE_START

// BlueprintGeneratedClass DamageType_GrenadeInterceptor.DamageType_GrenadeInterceptor_C
// 0x0000 (0x0548 - 0x0548)
class UDamageType_GrenadeInterceptor_C final : public UPMDamageType
{
public:
	static class UClass* StaticClass()
	{
		BP_STATIC_CLASS_IMPL("DamageType_GrenadeInterceptor_C")
	}
	static const class FName& StaticName()
	{
		STATIC_NAME_IMPL(L"DamageType_GrenadeInterceptor_C")
	}
	static class UDamageType_GrenadeInterceptor_C* GetDefaultObj()
	{
		return GetDefaultObjImpl<UDamageType_GrenadeInterceptor_C>();
	}
};
DUMPER7_ASSERTS_UDamageType_GrenadeInterceptor_C;

SDK_NAMESPACE_END
