#pragma once

/*
* SDK generated by Dumper-7
*
* https://github.com/Encryqed/Dumper-7
*/

// Package: DamageType_E_Yugiri

#include "Basic.hpp"

#include "PMGame_classes.hpp"


SDK_NAMESPACE_START

// BlueprintGeneratedClass DamageType_E_Yugiri.DamageType_E_Yugiri_C
// 0x0000 (0x0548 - 0x0548)
class UDamageType_E_Yugiri_C final : public UPMDamageType
{
public:
	static class UClass* StaticClass()
	{
		BP_STATIC_CLASS_IMPL("DamageType_E_Yugiri_C")
	}
	static const class FName& StaticName()
	{
		STATIC_NAME_IMPL(L"DamageType_E_Yugiri_C")
	}
	static class UDamageType_E_Yugiri_C* GetDefaultObj()
	{
		return GetDefaultObjImpl<UDamageType_E_Yugiri_C>();
	}
};
DUMPER7_ASSERTS_UDamageType_E_Yugiri_C;

SDK_NAMESPACE_END
