#pragma once

/*
* SDK generated by Dumper-7
*
* https://github.com/Encryqed/Dumper-7
*/

// Package: Duration_X_Fuchsia

#include "Basic.hpp"

#include "GameplayAbilities_classes.hpp"


SDK_NAMESPACE_START

// BlueprintGeneratedClass Duration_X_Fuchsia.Duration_X_Fuchsia_C
// 0x0000 (0x1060 - 0x1060)
class Duration_X_Fuchsia::UDuration_X_Fuchsia_C final : public UGameplayEffect
{
public:
	static class UClass* StaticClass()
	{
		BP_STATIC_CLASS_IMPL_FULLNAME("BlueprintGeneratedClass Duration_X_Fuchsia.Duration_X_Fuchsia_C")
	}
	static const class FName& StaticName()
	{
		STATIC_NAME_IMPL(L"Duration_X_Fuchsia_C")
	}
	static class Duration_X_Fuchsia::UDuration_X_Fuchsia_C* GetDefaultObj()
	{
		return GetDefaultObjImpl<Duration_X_Fuchsia::UDuration_X_Fuchsia_C>();
	}
};
DUMPER7_ASSERTS_Duration_X_Fuchsia__UDuration_X_Fuchsia_C;

SDK_NAMESPACE_END
