#pragma once

/*
* SDK generated by Dumper-7
*
* https://github.com/Encryqed/Dumper-7
*/

// Package: Envi_Umeda_AreaName

#include "Basic.hpp"

#include "Engine_classes.hpp"


SDK_NAMESPACE_START

// BlueprintGeneratedClass Envi_Umeda_AreaName.Envi_Umeda_AreaName_C
// 0x0000 (0x0318 - 0x0318)
class AEnvi_Umeda_AreaName_C final : public ALevelScriptActor
{
public:
	static class UClass* StaticClass()
	{
		BP_STATIC_CLASS_IMPL("Envi_Umeda_AreaName_C")
	}
	static const class FName& StaticName()
	{
		STATIC_NAME_IMPL(L"Envi_Umeda_AreaName_C")
	}
	static class AEnvi_Umeda_AreaName_C* GetDefaultObj()
	{
		return GetDefaultObjImpl<AEnvi_Umeda_AreaName_C>();
	}
};
DUMPER7_ASSERTS_AEnvi_Umeda_AreaName_C;

SDK_NAMESPACE_END
