#pragma once

/*
* SDK generated by Dumper-7
*
* https://github.com/Encryqed/Dumper-7
*/

// Package: FCTween

#include "Basic.hpp"

#include "Engine_classes.hpp"
#include "CoreUObject_structs.hpp"
#include "CoreUObject_classes.hpp"
#include "FCTween_structs.hpp"


SDK_NAMESPACE_START

// Class FCTween.FCTweenBlueprintLibrary
// 0x0000 (0x0028 - 0x0028)
class UFCTweenBlueprintLibrary final : public UBlueprintFunctionLibrary
{
public:
	static float Ease(float T, EFCEase EaseType);
	static float EaseWithParams(float T, EFCEase EaseType, float Param1, float Param2);
	static void EnsureTweenCapacity(int32 NumFloatTweens, int32 NumVectorTweens, int32 NumVector2DTweens, int32 NumQuatTweens);

public:
	static class UClass* StaticClass()
	{
		STATIC_CLASS_IMPL("FCTweenBlueprintLibrary")
	}
	static const class FName& StaticName()
	{
		STATIC_NAME_IMPL(L"FCTweenBlueprintLibrary")
	}
	static class UFCTweenBlueprintLibrary* GetDefaultObj()
	{
		return GetDefaultObjImpl<UFCTweenBlueprintLibrary>();
	}
};
DUMPER7_ASSERTS_UFCTweenBlueprintLibrary;

// Class FCTween.FCTweenBPAction
// 0x0070 (0x00A0 - 0x0030)
class UFCTweenBPAction : public UBlueprintAsyncActionBase
{
public:
	uint8                                         Pad_30[0x30];                                      // 0x0030(0x0030)(Fixing Size After Last Property [ Dumper-7 ])
	class UCurveFloat*                            CustomCurve;                                       // 0x0060(0x0008)(ZeroConstructor, IsPlainOldData, NoDestructor, HasGetValueTypeHash, NativeAccessSpecifierPublic)
	uint8                                         Pad_68[0x8];                                       // 0x0068(0x0008)(Fixing Size After Last Property [ Dumper-7 ])
	TMulticastInlineDelegate<void()>              OnLoop;                                            // 0x0070(0x0010)(ZeroConstructor, InstancedReference, BlueprintAssignable, AdvancedDisplay, NativeAccessSpecifierPublic)
	TMulticastInlineDelegate<void()>              OnYoyo;                                            // 0x0080(0x0010)(ZeroConstructor, InstancedReference, BlueprintAssignable, AdvancedDisplay, NativeAccessSpecifierPublic)
	TMulticastInlineDelegate<void()>              OnComplete;                                        // 0x0090(0x0010)(ZeroConstructor, InstancedReference, BlueprintAssignable, AdvancedDisplay, NativeAccessSpecifierPublic)

public:
	void Pause();
	void Restart();
	void SetTimeMultiplier(float Multiplier);
	void Stop();
	void Unpause();

public:
	static class UClass* StaticClass()
	{
		STATIC_CLASS_IMPL("FCTweenBPAction")
	}
	static const class FName& StaticName()
	{
		STATIC_NAME_IMPL(L"FCTweenBPAction")
	}
	static class UFCTweenBPAction* GetDefaultObj()
	{
		return GetDefaultObjImpl<UFCTweenBPAction>();
	}
};
DUMPER7_ASSERTS_UFCTweenBPAction;

// Class FCTween.FCTweenSubsystem
// 0x0018 (0x0048 - 0x0030)
class UFCTweenSubsystem final : public UGameInstanceSubsystem
{
public:
	uint8                                         Pad_30[0x8];                                       // 0x0030(0x0008)(Fixing Size After Last Property [ Dumper-7 ])
	uint64                                        LastTickedFrame;                                   // 0x0038(0x0008)(ZeroConstructor, IsPlainOldData, NoDestructor, HasGetValueTypeHash, NativeAccessSpecifierPrivate)
	float                                         LastRealTimeSeconds;                               // 0x0040(0x0004)(ZeroConstructor, IsPlainOldData, NoDestructor, HasGetValueTypeHash, NativeAccessSpecifierPrivate)
	uint8                                         Pad_44[0x4];                                       // 0x0044(0x0004)(Fixing Struct Size After Last Property [ Dumper-7 ])

public:
	static class UClass* StaticClass()
	{
		STATIC_CLASS_IMPL("FCTweenSubsystem")
	}
	static const class FName& StaticName()
	{
		STATIC_NAME_IMPL(L"FCTweenSubsystem")
	}
	static class UFCTweenSubsystem* GetDefaultObj()
	{
		return GetDefaultObjImpl<UFCTweenSubsystem>();
	}
};
DUMPER7_ASSERTS_UFCTweenSubsystem;

// Class FCTween.FCTweenBPActionFloat
// 0x0018 (0x00B8 - 0x00A0)
class UFCTweenBPActionFloat final : public UFCTweenBPAction
{
public:
	uint8                                         Pad_A0[0x8];                                       // 0x00A0(0x0008)(Fixing Size After Last Property [ Dumper-7 ])
	TMulticastInlineDelegate<void(float Value)>   ApplyEasing;                                       // 0x00A8(0x0010)(ZeroConstructor, InstancedReference, BlueprintAssignable, NativeAccessSpecifierPublic)

public:
	static class UFCTweenBPActionFloat* TweenFloat(float Start, float End, float DurationSecs, EFCEase EaseType, float EaseParam1, float EaseParam2, float Delay, int32 Loops, float LoopDelay, bool bYoyo, float YoyoDelay, bool bCanTickDuringPause, bool bUseGlobalTimeDilation);
	static class UFCTweenBPActionFloat* TweenFloatCustomCurve(float Start, float End, float DurationSecs, class UCurveFloat* Curve, float Delay, int32 Loops, float LoopDelay, bool bYoyo, float YoyoDelay, bool bCanTickDuringPause, bool bUseGlobalTimeDilation);

public:
	static class UClass* StaticClass()
	{
		STATIC_CLASS_IMPL("FCTweenBPActionFloat")
	}
	static const class FName& StaticName()
	{
		STATIC_NAME_IMPL(L"FCTweenBPActionFloat")
	}
	static class UFCTweenBPActionFloat* GetDefaultObj()
	{
		return GetDefaultObjImpl<UFCTweenBPActionFloat>();
	}
};
DUMPER7_ASSERTS_UFCTweenBPActionFloat;

// Class FCTween.FCTweenBPActionQuat
// 0x0030 (0x00D0 - 0x00A0)
class alignas(0x10) UFCTweenBPActionQuat final : public UFCTweenBPAction
{
public:
	uint8                                         Pad_A0[0x20];                                      // 0x00A0(0x0020)(Fixing Size After Last Property [ Dumper-7 ])
	TMulticastInlineDelegate<void(const struct FQuat& Value)> ApplyEasing;                           // 0x00C0(0x0010)(ZeroConstructor, InstancedReference, BlueprintAssignable, NativeAccessSpecifierPublic)

public:
	static class UFCTweenBPActionQuat* TweenQuat(const struct FQuat& Start, const struct FQuat& End, float DurationSecs, EFCEase EaseType, float EaseParam1, float EaseParam2, float Delay, int32 Loops, float LoopDelay, bool bYoyo, float YoyoDelay, bool bCanTickDuringPause, bool bUseGlobalTimeDilation);
	static class UFCTweenBPActionQuat* TweenQuatCustomCurve(const struct FQuat& Start, const struct FQuat& End, float DurationSecs, class UCurveFloat* Curve, float Delay, int32 Loops, float LoopDelay, bool bYoyo, float YoyoDelay, bool bCanTickDuringPause, bool bUseGlobalTimeDilation);
	static class UFCTweenBPActionQuat* TweenQuatFromRotator(const struct FRotator& Start, const struct FRotator& End, float DurationSecs, EFCEase EaseType, float EaseParam1, float EaseParam2, float Delay, int32 Loops, float LoopDelay, bool bYoyo, float YoyoDelay, bool bCanTickDuringPause, bool bUseGlobalTimeDilation);
	static class UFCTweenBPActionQuat* TweenQuatFromRotatorCustomCurve(const struct FRotator& Start, const struct FRotator& End, float DurationSecs, class UCurveFloat* Curve, float Delay, int32 Loops, float LoopDelay, bool bYoyo, float YoyoDelay, bool bCanTickDuringPause, bool bUseGlobalTimeDilation);

public:
	static class UClass* StaticClass()
	{
		STATIC_CLASS_IMPL("FCTweenBPActionQuat")
	}
	static const class FName& StaticName()
	{
		STATIC_NAME_IMPL(L"FCTweenBPActionQuat")
	}
	static class UFCTweenBPActionQuat* GetDefaultObj()
	{
		return GetDefaultObjImpl<UFCTweenBPActionQuat>();
	}
};
DUMPER7_ASSERTS_UFCTweenBPActionQuat;

// Class FCTween.FCTweenBPActionRotator
// 0x0030 (0x00D0 - 0x00A0)
class alignas(0x10) UFCTweenBPActionRotator final : public UFCTweenBPAction
{
public:
	uint8                                         Pad_A0[0x20];                                      // 0x00A0(0x0020)(Fixing Size After Last Property [ Dumper-7 ])
	TMulticastInlineDelegate<void(const struct FRotator& Value)> ApplyEasing;                        // 0x00C0(0x0010)(ZeroConstructor, InstancedReference, BlueprintAssignable, NativeAccessSpecifierPublic)

public:
	static class UFCTweenBPActionRotator* TweenRotator(const struct FRotator& Start, const struct FRotator& End, float DurationSecs, EFCEase EaseType, float EaseParam1, float EaseParam2, float Delay, int32 Loops, float LoopDelay, bool bYoyo, float YoyoDelay, bool bCanTickDuringPause, bool bUseGlobalTimeDilation);
	static class UFCTweenBPActionRotator* TweenRotatorCustomCurve(const struct FRotator& Start, const struct FRotator& End, float DurationSecs, class UCurveFloat* Curve, float Delay, int32 Loops, float LoopDelay, bool bYoyo, float YoyoDelay, bool bCanTickDuringPause, bool bUseGlobalTimeDilation);

public:
	static class UClass* StaticClass()
	{
		STATIC_CLASS_IMPL("FCTweenBPActionRotator")
	}
	static const class FName& StaticName()
	{
		STATIC_NAME_IMPL(L"FCTweenBPActionRotator")
	}
	static class UFCTweenBPActionRotator* GetDefaultObj()
	{
		return GetDefaultObjImpl<UFCTweenBPActionRotator>();
	}
};
DUMPER7_ASSERTS_UFCTweenBPActionRotator;

// Class FCTween.FCTweenBPActionVector
// 0x0028 (0x00C8 - 0x00A0)
class UFCTweenBPActionVector final : public UFCTweenBPAction
{
public:
	uint8                                         Pad_A0[0x18];                                      // 0x00A0(0x0018)(Fixing Size After Last Property [ Dumper-7 ])
	TMulticastInlineDelegate<void(const struct FVector& Value)> ApplyEasing;                         // 0x00B8(0x0010)(ZeroConstructor, InstancedReference, BlueprintAssignable, NativeAccessSpecifierPublic)

public:
	static class UFCTweenBPActionVector* TweenVector(const struct FVector& Start, const struct FVector& End, float DurationSecs, EFCEase EaseType, float EaseParam1, float EaseParam2, float Delay, int32 Loops, float LoopDelay, bool bYoyo, float YoyoDelay, bool bCanTickDuringPause, bool bUseGlobalTimeDilation);
	static class UFCTweenBPActionVector* TweenVectorCustomCurve(const struct FVector& Start, const struct FVector& End, float DurationSecs, class UCurveFloat* Curve, float Delay, int32 Loops, float LoopDelay, bool bYoyo, float YoyoDelay, bool bCanTickDuringPause, bool bUseGlobalTimeDilation);

public:
	static class UClass* StaticClass()
	{
		STATIC_CLASS_IMPL("FCTweenBPActionVector")
	}
	static const class FName& StaticName()
	{
		STATIC_NAME_IMPL(L"FCTweenBPActionVector")
	}
	static class UFCTweenBPActionVector* GetDefaultObj()
	{
		return GetDefaultObjImpl<UFCTweenBPActionVector>();
	}
};
DUMPER7_ASSERTS_UFCTweenBPActionVector;

// Class FCTween.FCTweenBPActionVector2D
// 0x0020 (0x00C0 - 0x00A0)
class UFCTweenBPActionVector2D final : public UFCTweenBPAction
{
public:
	uint8                                         Pad_A0[0x10];                                      // 0x00A0(0x0010)(Fixing Size After Last Property [ Dumper-7 ])
	TMulticastInlineDelegate<void(const struct FVector2D& Value)> ApplyEasing;                       // 0x00B0(0x0010)(ZeroConstructor, InstancedReference, BlueprintAssignable, NativeAccessSpecifierPublic)

public:
	static class UFCTweenBPActionVector2D* TweenVector2D(const struct FVector2D& Start, const struct FVector2D& End, float DurationSecs, EFCEase EaseType, float EaseParam1, float EaseParam2, float Delay, int32 Loops, float LoopDelay, bool bYoyo, float YoyoDelay, bool bCanTickDuringPause, bool bUseGlobalTimeDilation);
	static class UFCTweenBPActionVector2D* TweenVector2DCustomCurve(const struct FVector2D& Start, const struct FVector2D& End, float DurationSecs, class UCurveFloat* Curve, float Delay, int32 Loops, float LoopDelay, bool bYoyo, float YoyoDelay, bool bCanTickDuringPause, bool bUseGlobalTimeDilation);

public:
	static class UClass* StaticClass()
	{
		STATIC_CLASS_IMPL("FCTweenBPActionVector2D")
	}
	static const class FName& StaticName()
	{
		STATIC_NAME_IMPL(L"FCTweenBPActionVector2D")
	}
	static class UFCTweenBPActionVector2D* GetDefaultObj()
	{
		return GetDefaultObjImpl<UFCTweenBPActionVector2D>();
	}
};
DUMPER7_ASSERTS_UFCTweenBPActionVector2D;

// Class FCTween.FCTweenUObject
// 0x0008 (0x0030 - 0x0028)
class UFCTweenUObject final : public UObject
{
public:
	uint8                                         Pad_28[0x8];                                       // 0x0028(0x0008)(Fixing Struct Size After Last Property [ Dumper-7 ])

public:
	static class UClass* StaticClass()
	{
		STATIC_CLASS_IMPL("FCTweenUObject")
	}
	static const class FName& StaticName()
	{
		STATIC_NAME_IMPL(L"FCTweenUObject")
	}
	static class UFCTweenUObject* GetDefaultObj()
	{
		return GetDefaultObjImpl<UFCTweenUObject>();
	}
};
DUMPER7_ASSERTS_UFCTweenUObject;

SDK_NAMESPACE_END
