#pragma once

/*
* SDK generated by Dumper-7
*
* https://github.com/Encryqed/Dumper-7
*/

// Package: FlyingNavSystem

#include "Basic.hpp"

#include "CoreUObject_structs.hpp"
#include "CoreUObject_classes.hpp"
#include "NavigationSystem_classes.hpp"
#include "Engine_structs.hpp"
#include "Engine_classes.hpp"
#include "FlyingNavSystem_structs.hpp"


SDK_NAMESPACE_START

// Class FlyingNavSystem.FlyingNavDynamicObstacleComponent
// 0x0030 (0x0500 - 0x04D0)
class UFlyingNavDynamicObstacleComponent final : public UBoxComponent
{
public:
	bool                                          bNavigationEnabled;                                // 0x04D0(0x0001)(Edit, BlueprintVisible, ZeroConstructor, IsPlainOldData, NoDestructor, Protected, HasGetValueTypeHash, NativeAccessSpecifierProtected)
	uint8                                         Pad_4D1[0x3];                                      // 0x04D1(0x0003)(Fixing Size After Last Property [ Dumper-7 ])
	float                                         NavigationBoundsInflation;                         // 0x04D4(0x0004)(Edit, BlueprintVisible, ZeroConstructor, IsPlainOldData, NoDestructor, Protected, HasGetValueTypeHash, NativeAccessSpecifierProtected)
	bool                                          bPreserveDetailDuringBake;                         // 0x04D8(0x0001)(Edit, BlueprintVisible, ZeroConstructor, IsPlainOldData, NoDestructor, Protected, HasGetValueTypeHash, NativeAccessSpecifierProtected)
	uint8                                         Pad_4D9[0x27];                                     // 0x04D9(0x0027)(Fixing Struct Size After Last Property [ Dumper-7 ])

public:
	void SetNavigationEnabled(bool bInEnabled);

	bool IsNavigationEnabled() const;

public:
	static class UClass* StaticClass()
	{
		STATIC_CLASS_IMPL("FlyingNavDynamicObstacleComponent")
	}
	static const class FName& StaticName()
	{
		STATIC_NAME_IMPL(L"FlyingNavDynamicObstacleComponent")
	}
	static class UFlyingNavDynamicObstacleComponent* GetDefaultObj()
	{
		return GetDefaultObjImpl<UFlyingNavDynamicObstacleComponent>();
	}
};
DUMPER7_ASSERTS_UFlyingNavDynamicObstacleComponent;

// Class FlyingNavSystem.FlyingNavBenchmarkActor
// 0x0178 (0x0488 - 0x0310)
class AFlyingNavBenchmarkActor final : public AActor
{
public:
	class FName                                   AgentName;                                         // 0x0310(0x0008)(Edit, ZeroConstructor, IsPlainOldData, NoDestructor, HasGetValueTypeHash, NativeAccessSpecifierPublic)
	struct FBox                                   SampleBoxOverride;                                 // 0x0318(0x001C)(Edit, ZeroConstructor, IsPlainOldData, NoDestructor, NativeAccessSpecifierPublic)
	bool                                          bAllowPartialPaths;                                // 0x0334(0x0001)(Edit, ZeroConstructor, IsPlainOldData, NoDestructor, HasGetValueTypeHash, NativeAccessSpecifierPublic)
	bool                                          bDrawFailures;                                     // 0x0335(0x0001)(Edit, ZeroConstructor, IsPlainOldData, NoDestructor, HasGetValueTypeHash, NativeAccessSpecifierPublic)
	uint8                                         Pad_336[0x2];                                      // 0x0336(0x0002)(Fixing Size After Last Property [ Dumper-7 ])
	float                                         FailureDrawDuration;                               // 0x0338(0x0004)(Edit, ZeroConstructor, IsPlainOldData, NoDestructor, HasGetValueTypeHash, NativeAccessSpecifierPublic)
	bool                                          bCollectStageBreakdown;                            // 0x033C(0x0001)(Edit, ZeroConstructor, IsPlainOldData, NoDestructor, HasGetValueTypeHash, NativeAccessSpecifierPublic)
	EFlyingNavBenchmarkDiagnosticsMode            DiagnosticsMode;                                   // 0x033D(0x0001)(Edit, ZeroConstructor, IsPlainOldData, NoDestructor, HasGetValueTypeHash, NativeAccessSpecifierPublic)
	uint8                                         Pad_33E[0x2];                                      // 0x033E(0x0002)(Fixing Size After Last Property [ Dumper-7 ])
	int32                                         RandomSeed;                                        // 0x0340(0x0004)(Edit, ZeroConstructor, IsPlainOldData, NoDestructor, HasGetValueTypeHash, NativeAccessSpecifierPublic)
	bool                                          bClassifyBenchmarkByResolvedConnectivity;          // 0x0344(0x0001)(Edit, ZeroConstructor, IsPlainOldData, NoDestructor, HasGetValueTypeHash, NativeAccessSpecifierPublic)
	uint8                                         Pad_345[0x3];                                      // 0x0345(0x0003)(Fixing Size After Last Property [ Dumper-7 ])
	int32                                         Experimental_MaxIterations;                        // 0x0348(0x0004)(Edit, ZeroConstructor, IsPlainOldData, NoDestructor, HasGetValueTypeHash, NativeAccessSpecifierPublic)
	int32                                         Experimental_MaxIterationHardCap;                  // 0x034C(0x0004)(Edit, ZeroConstructor, IsPlainOldData, NoDestructor, HasGetValueTypeHash, NativeAccessSpecifierPublic)
	float                                         Experimental_HeuristicScale;                       // 0x0350(0x0004)(Edit, ZeroConstructor, IsPlainOldData, NoDestructor, HasGetValueTypeHash, NativeAccessSpecifierPublic)
	EPathfindingAlgorithm                         Experimental_PathfindingAlgorithm;                 // 0x0354(0x0001)(Edit, ZeroConstructor, IsPlainOldData, NoDestructor, HasGetValueTypeHash, NativeAccessSpecifierPublic)
	bool                                          Experimental_bEnableTerminalApproachSubSearch;     // 0x0355(0x0001)(Edit, ZeroConstructor, IsPlainOldData, NoDestructor, HasGetValueTypeHash, NativeAccessSpecifierPublic)
	bool                                          Experimental_bUseCoarseRouteHardPrune;             // 0x0356(0x0001)(Edit, ZeroConstructor, IsPlainOldData, NoDestructor, HasGetValueTypeHash, NativeAccessSpecifierPublic)
	uint8                                         Pad_357[0x1];                                      // 0x0357(0x0001)(Fixing Size After Last Property [ Dumper-7 ])
	float                                         Experimental_TerminalApproachSubSearchRadiusCm;    // 0x0358(0x0004)(Edit, ZeroConstructor, IsPlainOldData, NoDestructor, HasGetValueTypeHash, NativeAccessSpecifierPublic)
	int32                                         Experimental_TerminalApproachSubSearchMaxIterations; // 0x035C(0x0004)(Edit, ZeroConstructor, IsPlainOldData, NoDestructor, HasGetValueTypeHash, NativeAccessSpecifierPublic)
	int32                                         ShortPath_SamplesPerBand;                          // 0x0360(0x0004)(Edit, ZeroConstructor, IsPlainOldData, NoDestructor, HasGetValueTypeHash, NativeAccessSpecifierPublic)
	float                                         ShortPath_PerBandTimeBudgetSec;                    // 0x0364(0x0004)(Edit, ZeroConstructor, IsPlainOldData, NoDestructor, HasGetValueTypeHash, NativeAccessSpecifierPublic)
	float                                         ShortPath_SlowThresholdMs;                         // 0x0368(0x0004)(Edit, ZeroConstructor, IsPlainOldData, NoDestructor, HasGetValueTypeHash, NativeAccessSpecifierPublic)
	float                                         ShortPath_DetourRatioThreshold;                    // 0x036C(0x0004)(Edit, ZeroConstructor, IsPlainOldData, NoDestructor, HasGetValueTypeHash, NativeAccessSpecifierPublic)
	int32                                         ShortPath_MaxLoggedProblemSamples;                 // 0x0370(0x0004)(Edit, ZeroConstructor, IsPlainOldData, NoDestructor, HasGetValueTypeHash, NativeAccessSpecifierPublic)
	bool                                          ShortPath_bAllowPartialPaths;                      // 0x0374(0x0001)(Edit, ZeroConstructor, IsPlainOldData, NoDestructor, HasGetValueTypeHash, NativeAccessSpecifierPublic)
	bool                                          ShortPath_bUsePortalAnchoredSampling;              // 0x0375(0x0001)(Edit, ZeroConstructor, IsPlainOldData, NoDestructor, HasGetValueTypeHash, NativeAccessSpecifierPublic)
	uint8                                         Pad_376[0x2];                                      // 0x0376(0x0002)(Fixing Size After Last Property [ Dumper-7 ])
	int32                                         Latency_SamplesPerBand;                            // 0x0378(0x0004)(Edit, ZeroConstructor, IsPlainOldData, NoDestructor, HasGetValueTypeHash, NativeAccessSpecifierPublic)
	int32                                         Latency_DisconnectedPercent;                       // 0x037C(0x0004)(Edit, ZeroConstructor, IsPlainOldData, NoDestructor, HasGetValueTypeHash, NativeAccessSpecifierPublic)
	bool                                          Latency_bIncludeVeryFarBand;                       // 0x0380(0x0001)(Edit, ZeroConstructor, IsPlainOldData, NoDestructor, HasGetValueTypeHash, NativeAccessSpecifierPublic)
	uint8                                         Pad_381[0x3];                                      // 0x0381(0x0003)(Fixing Size After Last Property [ Dumper-7 ])
	float                                         Latency_PerBandTimeBudgetSec;                      // 0x0384(0x0004)(Edit, ZeroConstructor, IsPlainOldData, NoDestructor, HasGetValueTypeHash, NativeAccessSpecifierPublic)
	float                                         Latency_SlowQueryThresholdMs;                      // 0x0388(0x0004)(Edit, ZeroConstructor, IsPlainOldData, NoDestructor, HasGetValueTypeHash, NativeAccessSpecifierPublic)
	int32                                         Latency_MaxLoggedSlowQueries;                      // 0x038C(0x0004)(Edit, ZeroConstructor, IsPlainOldData, NoDestructor, HasGetValueTypeHash, NativeAccessSpecifierPublic)
	EFlyingNavCompensationOverride                Latency_CompensationOverride;                      // 0x0390(0x0001)(Edit, ZeroConstructor, IsPlainOldData, NoDestructor, HasGetValueTypeHash, NativeAccessSpecifierPublic)
	uint8                                         Pad_391[0x3];                                      // 0x0391(0x0003)(Fixing Size After Last Property [ Dumper-7 ])
	int32                                         EdgeCase_SamplesPerCase;                           // 0x0394(0x0004)(Edit, ZeroConstructor, IsPlainOldData, NoDestructor, HasGetValueTypeHash, NativeAccessSpecifierPublic)
	bool                                          EdgeCase_bUsePortalAnchoredSampling;               // 0x0398(0x0001)(Edit, ZeroConstructor, IsPlainOldData, NoDestructor, HasGetValueTypeHash, NativeAccessSpecifierPublic)
	uint8                                         Pad_399[0x3];                                      // 0x0399(0x0003)(Fixing Size After Last Property [ Dumper-7 ])
	int32                                         Server_PathsPerFrame;                              // 0x039C(0x0004)(Edit, ZeroConstructor, IsPlainOldData, NoDestructor, HasGetValueTypeHash, NativeAccessSpecifierPublic)
	int32                                         Server_NumFrames;                                  // 0x03A0(0x0004)(Edit, ZeroConstructor, IsPlainOldData, NoDestructor, HasGetValueTypeHash, NativeAccessSpecifierPublic)
	uint8                                         Pad_3A4[0x4];                                      // 0x03A4(0x0004)(Fixing Size After Last Property [ Dumper-7 ])
	double                                        Server_FrameBudgetMs;                              // 0x03A8(0x0008)(Edit, ZeroConstructor, IsPlainOldData, NoDestructor, HasGetValueTypeHash, NativeAccessSpecifierPublic)
	float                                         Server_MinDistance;                                // 0x03B0(0x0004)(Edit, ZeroConstructor, IsPlainOldData, NoDestructor, HasGetValueTypeHash, NativeAccessSpecifierPublic)
	float                                         Server_MaxDistance;                                // 0x03B4(0x0004)(Edit, ZeroConstructor, IsPlainOldData, NoDestructor, HasGetValueTypeHash, NativeAccessSpecifierPublic)
	int32                                         Async_RequestCount;                                // 0x03B8(0x0004)(Edit, ZeroConstructor, IsPlainOldData, NoDestructor, HasGetValueTypeHash, NativeAccessSpecifierPublic)
	float                                         Async_MinDistance;                                 // 0x03BC(0x0004)(Edit, ZeroConstructor, IsPlainOldData, NoDestructor, HasGetValueTypeHash, NativeAccessSpecifierPublic)
	float                                         Async_MaxDistance;                                 // 0x03C0(0x0004)(Edit, ZeroConstructor, IsPlainOldData, NoDestructor, HasGetValueTypeHash, NativeAccessSpecifierPublic)
	float                                         Async_DrainIntervalMs;                             // 0x03C4(0x0004)(Edit, ZeroConstructor, IsPlainOldData, NoDestructor, HasGetValueTypeHash, NativeAccessSpecifierPublic)
	float                                         Async_TimeoutSec;                                  // 0x03C8(0x0004)(Edit, ZeroConstructor, IsPlainOldData, NoDestructor, HasGetValueTypeHash, NativeAccessSpecifierPublic)
	bool                                          Async_bRunSyncBaseline;                            // 0x03CC(0x0001)(Edit, ZeroConstructor, IsPlainOldData, NoDestructor, HasGetValueTypeHash, NativeAccessSpecifierPublic)
	uint8                                         Pad_3CD[0x3];                                      // 0x03CD(0x0003)(Fixing Size After Last Property [ Dumper-7 ])
	float                                         AsyncTest_TimeoutSec;                              // 0x03D0(0x0004)(Edit, ZeroConstructor, IsPlainOldData, NoDestructor, HasGetValueTypeHash, NativeAccessSpecifierPublic)
	float                                         AsyncTest_DrainIntervalMs;                         // 0x03D4(0x0004)(Edit, ZeroConstructor, IsPlainOldData, NoDestructor, HasGetValueTypeHash, NativeAccessSpecifierPublic)
	bool                                          AsyncTest_bRunWorkerMode;                          // 0x03D8(0x0001)(Edit, ZeroConstructor, IsPlainOldData, NoDestructor, HasGetValueTypeHash, NativeAccessSpecifierPublic)
	bool                                          AsyncTest_bRunTimeSlicedMode;                      // 0x03D9(0x0001)(Edit, ZeroConstructor, IsPlainOldData, NoDestructor, HasGetValueTypeHash, NativeAccessSpecifierPublic)
	bool                                          AsyncTest_bRunCancelCase;                          // 0x03DA(0x0001)(Edit, ZeroConstructor, IsPlainOldData, NoDestructor, HasGetValueTypeHash, NativeAccessSpecifierPublic)
	uint8                                         Pad_3DB[0x1];                                      // 0x03DB(0x0001)(Fixing Size After Last Property [ Dumper-7 ])
	int32                                         Safety_Samples;                                    // 0x03DC(0x0004)(Edit, ZeroConstructor, IsPlainOldData, NoDestructor, HasGetValueTypeHash, NativeAccessSpecifierPublic)
	float                                         Safety_MinDistance;                                // 0x03E0(0x0004)(Edit, ZeroConstructor, IsPlainOldData, NoDestructor, HasGetValueTypeHash, NativeAccessSpecifierPublic)
	float                                         Safety_MaxDistance;                                // 0x03E4(0x0004)(Edit, ZeroConstructor, IsPlainOldData, NoDestructor, HasGetValueTypeHash, NativeAccessSpecifierPublic)
	bool                                          Safety_bTestAStar;                                 // 0x03E8(0x0001)(Edit, ZeroConstructor, IsPlainOldData, NoDestructor, HasGetValueTypeHash, NativeAccessSpecifierPublic)
	bool                                          Safety_bTestThetaStar;                             // 0x03E9(0x0001)(Edit, ZeroConstructor, IsPlainOldData, NoDestructor, HasGetValueTypeHash, NativeAccessSpecifierPublic)
	bool                                          Safety_bTestLazyThetaStar;                         // 0x03EA(0x0001)(Edit, ZeroConstructor, IsPlainOldData, NoDestructor, HasGetValueTypeHash, NativeAccessSpecifierPublic)
	bool                                          Safety_bUsePortalAnchoredSampling;                 // 0x03EB(0x0001)(Edit, ZeroConstructor, IsPlainOldData, NoDestructor, HasGetValueTypeHash, NativeAccessSpecifierPublic)
	bool                                          Safety_bDrawUnsafeSegments;                        // 0x03EC(0x0001)(Edit, ZeroConstructor, IsPlainOldData, NoDestructor, HasGetValueTypeHash, NativeAccessSpecifierPublic)
	bool                                          Safety_bTestPhysicsCapsule;                        // 0x03ED(0x0001)(Edit, ZeroConstructor, IsPlainOldData, NoDestructor, HasGetValueTypeHash, NativeAccessSpecifierPublic)
	uint8                                         Pad_3EE[0x2];                                      // 0x03EE(0x0002)(Fixing Size After Last Property [ Dumper-7 ])
	float                                         Safety_PhysicsAgentRadiusOverride;                 // 0x03F0(0x0004)(Edit, ZeroConstructor, IsPlainOldData, NoDestructor, HasGetValueTypeHash, NativeAccessSpecifierPublic)
	float                                         Safety_PhysicsAgentHalfHeightOverride;             // 0x03F4(0x0004)(Edit, ZeroConstructor, IsPlainOldData, NoDestructor, HasGetValueTypeHash, NativeAccessSpecifierPublic)
	ECollisionChannel                             Safety_PhysicsCollisionChannel;                    // 0x03F8(0x0001)(Edit, ZeroConstructor, IsPlainOldData, NoDestructor, HasGetValueTypeHash, NativeAccessSpecifierPublic)
	uint8                                         Pad_3F9[0x3];                                      // 0x03F9(0x0003)(Fixing Size After Last Property [ Dumper-7 ])
	int32                                         Safety_MaxLoggedFailures;                          // 0x03FC(0x0004)(Edit, ZeroConstructor, IsPlainOldData, NoDestructor, HasGetValueTypeHash, NativeAccessSpecifierPublic)
	int32                                         Safety_MaxLoggedBudgetPartials;                    // 0x0400(0x0004)(Edit, ZeroConstructor, IsPlainOldData, NoDestructor, HasGetValueTypeHash, NativeAccessSpecifierPublic)
	bool                                          Safety_bLogBudgetDiagnostics;                      // 0x0404(0x0001)(Edit, ZeroConstructor, IsPlainOldData, NoDestructor, HasGetValueTypeHash, NativeAccessSpecifierPublic)
	uint8                                         Pad_405[0x3];                                      // 0x0405(0x0003)(Fixing Size After Last Property [ Dumper-7 ])
	int32                                         RegionGraphDiagnostic_Samples;                     // 0x0408(0x0004)(Edit, ZeroConstructor, IsPlainOldData, NoDestructor, HasGetValueTypeHash, NativeAccessSpecifierPublic)
	int32                                         RegionGraphDiagnostic_MaxLoggedSamples;            // 0x040C(0x0004)(Edit, ZeroConstructor, IsPlainOldData, NoDestructor, HasGetValueTypeHash, NativeAccessSpecifierPublic)
	int32                                         RegionGraphDiagnostic_CorridorHopCount;            // 0x0410(0x0004)(Edit, ZeroConstructor, IsPlainOldData, NoDestructor, HasGetValueTypeHash, NativeAccessSpecifierPublic)
	int32                                         LongPath_MaxLoggedFanoutSamples;                   // 0x0414(0x0004)(Edit, ZeroConstructor, IsPlainOldData, NoDestructor, HasGetValueTypeHash, NativeAccessSpecifierPublic)
	bool                                          LongPath_bLogDetailedDiagnostics;                  // 0x0418(0x0001)(Edit, ZeroConstructor, IsPlainOldData, NoDestructor, HasGetValueTypeHash, NativeAccessSpecifierPublic)
	uint8                                         Pad_419[0x3];                                      // 0x0419(0x0003)(Fixing Size After Last Property [ Dumper-7 ])
	int32                                         LongPath_SamplesPerBand;                           // 0x041C(0x0004)(Edit, ZeroConstructor, IsPlainOldData, NoDestructor, HasGetValueTypeHash, NativeAccessSpecifierPublic)
	int32                                         LongPath_DisconnectedPercent;                      // 0x0420(0x0004)(Edit, ZeroConstructor, IsPlainOldData, NoDestructor, HasGetValueTypeHash, NativeAccessSpecifierPublic)
	bool                                          LongPath_bIncludeVeryFarBand;                      // 0x0424(0x0001)(Edit, ZeroConstructor, IsPlainOldData, NoDestructor, HasGetValueTypeHash, NativeAccessSpecifierPublic)
	uint8                                         Pad_425[0x3];                                      // 0x0425(0x0003)(Fixing Size After Last Property [ Dumper-7 ])
	int32                                         LongPath_MinBandIndex;                             // 0x0428(0x0004)(Edit, ZeroConstructor, IsPlainOldData, NoDestructor, HasGetValueTypeHash, NativeAccessSpecifierPublic)
	int32                                         LongPath_MaxBandIndex;                             // 0x042C(0x0004)(Edit, ZeroConstructor, IsPlainOldData, NoDestructor, HasGetValueTypeHash, NativeAccessSpecifierPublic)
	float                                         LongPath_PerBandTimeBudgetSec;                     // 0x0430(0x0004)(Edit, ZeroConstructor, IsPlainOldData, NoDestructor, HasGetValueTypeHash, NativeAccessSpecifierPublic)
	EFlyingNavCompensationOverride                LongPath_CompensationOverride;                     // 0x0434(0x0001)(Edit, ZeroConstructor, IsPlainOldData, NoDestructor, HasGetValueTypeHash, NativeAccessSpecifierPublic)
	uint8                                         Pad_435[0x3];                                      // 0x0435(0x0003)(Fixing Size After Last Property [ Dumper-7 ])
	int32                                         RegionSearchTest_SafetySamples;                    // 0x0438(0x0004)(Edit, ZeroConstructor, IsPlainOldData, NoDestructor, HasGetValueTypeHash, NativeAccessSpecifierPublic)
	int32                                         RegionSearchTest_LongPathSamplesPerBand;           // 0x043C(0x0004)(Edit, ZeroConstructor, IsPlainOldData, NoDestructor, HasGetValueTypeHash, NativeAccessSpecifierPublic)
	int32                                         RegionSearchTest_MaxIterations;                    // 0x0440(0x0004)(Edit, ZeroConstructor, IsPlainOldData, NoDestructor, HasGetValueTypeHash, NativeAccessSpecifierPublic)
	int32                                         RegionSearchTest_MaxIterationHardCap;              // 0x0444(0x0004)(Edit, ZeroConstructor, IsPlainOldData, NoDestructor, HasGetValueTypeHash, NativeAccessSpecifierPublic)
	float                                         RegionSearchTest_HeuristicScale;                   // 0x0448(0x0004)(Edit, ZeroConstructor, IsPlainOldData, NoDestructor, HasGetValueTypeHash, NativeAccessSpecifierPublic)
	bool                                          RegionSearchTest_bEnableTerminalApproachSubSearch; // 0x044C(0x0001)(Edit, ZeroConstructor, IsPlainOldData, NoDestructor, HasGetValueTypeHash, NativeAccessSpecifierPublic)
	uint8                                         Pad_44D[0x3];                                      // 0x044D(0x0003)(Fixing Size After Last Property [ Dumper-7 ])
	float                                         RegionSearchTest_TerminalApproachSubSearchRadiusCm; // 0x0450(0x0004)(Edit, ZeroConstructor, IsPlainOldData, NoDestructor, HasGetValueTypeHash, NativeAccessSpecifierPublic)
	int32                                         RegionSearchTest_TerminalApproachSubSearchMaxIterations; // 0x0454(0x0004)(Edit, ZeroConstructor, IsPlainOldData, NoDestructor, HasGetValueTypeHash, NativeAccessSpecifierPublic)
	bool                                          RegionSearchTest_bIncludeVeryFarBand;              // 0x0458(0x0001)(Edit, ZeroConstructor, IsPlainOldData, NoDestructor, HasGetValueTypeHash, NativeAccessSpecifierPublic)
	uint8                                         Pad_459[0x3];                                      // 0x0459(0x0003)(Fixing Size After Last Property [ Dumper-7 ])
	float                                         RegionSearchTest_LongPathPerBandBudgetSec;         // 0x045C(0x0004)(Edit, ZeroConstructor, IsPlainOldData, NoDestructor, HasGetValueTypeHash, NativeAccessSpecifierPublic)
	struct FVector                                CoarseFineProbe_Start;                             // 0x0460(0x000C)(Edit, ZeroConstructor, IsPlainOldData, NoDestructor, HasGetValueTypeHash, NativeAccessSpecifierPublic)
	struct FVector                                CoarseFineProbe_End;                               // 0x046C(0x000C)(Edit, ZeroConstructor, IsPlainOldData, NoDestructor, HasGetValueTypeHash, NativeAccessSpecifierPublic)
	EPathfindingAlgorithm                         CoarseFineProbe_Algorithm;                         // 0x0478(0x0001)(Edit, ZeroConstructor, IsPlainOldData, NoDestructor, HasGetValueTypeHash, NativeAccessSpecifierPublic)
	bool                                          CoarseFineProbe_bAllowPartialPaths;                // 0x0479(0x0001)(Edit, ZeroConstructor, IsPlainOldData, NoDestructor, HasGetValueTypeHash, NativeAccessSpecifierPublic)
	uint8                                         Pad_47A[0x2];                                      // 0x047A(0x0002)(Fixing Size After Last Property [ Dumper-7 ])
	int32                                         CoarseFineProbe_MaxIterations;                     // 0x047C(0x0004)(Edit, ZeroConstructor, IsPlainOldData, NoDestructor, HasGetValueTypeHash, NativeAccessSpecifierPublic)
	int32                                         CoarseFineProbe_MaxIterationHardCap;               // 0x0480(0x0004)(Edit, ZeroConstructor, IsPlainOldData, NoDestructor, HasGetValueTypeHash, NativeAccessSpecifierPublic)
	bool                                          CoarseFineProbe_bRunNoCorridor;                    // 0x0484(0x0001)(Edit, ZeroConstructor, IsPlainOldData, NoDestructor, HasGetValueTypeHash, NativeAccessSpecifierPublic)
	bool                                          CoarseFineProbe_bRunNoCostLimit;                   // 0x0485(0x0001)(Edit, ZeroConstructor, IsPlainOldData, NoDestructor, HasGetValueTypeHash, NativeAccessSpecifierPublic)
	bool                                          CoarseFineProbe_bCollectCorridorDiagnostics;       // 0x0486(0x0001)(Edit, ZeroConstructor, IsPlainOldData, NoDestructor, HasGetValueTypeHash, NativeAccessSpecifierPublic)
	uint8                                         Pad_487[0x1];                                      // 0x0487(0x0001)(Fixing Struct Size After Last Property [ Dumper-7 ])

public:
	void ClearFailureMarkers();
	void Run_AsyncFunctionalValidation();
	void Run_AsyncPerformanceBenchmark();
	void Run_CoarseFineConnectivityProbe();
	void Run_CorrectnessCases();
	void Run_FullRegressionSuite();
	void Run_LongPathBenchmark();
	void Run_PathSafetyValidation();
	void Run_QuickRegressionSuite();
	void Run_RegionGraphDiagnostic();
	void Run_RegionSearchDiagnostic();
	void Run_ServerFrameBudgetSimulation();
	void Run_ShortPathBenchmark();
	void Run_SmokeValidation();
	void Run_SyncLatencyBenchmark();

public:
	static class UClass* StaticClass()
	{
		STATIC_CLASS_IMPL("FlyingNavBenchmarkActor")
	}
	static const class FName& StaticName()
	{
		STATIC_NAME_IMPL(L"FlyingNavBenchmarkActor")
	}
	static class AFlyingNavBenchmarkActor* GetDefaultObj()
	{
		return GetDefaultObjImpl<AFlyingNavBenchmarkActor>();
	}
};
DUMPER7_ASSERTS_AFlyingNavBenchmarkActor;

// Class FlyingNavSystem.FlyingNavDynamicObstacleGroupComponent
// 0x00A8 (0x01D0 - 0x0128)
class UFlyingNavDynamicObstacleGroupComponent final : public UActorComponent
{
public:
	uint8                                         Pad_128[0x8];                                      // 0x0128(0x0008)(Fixing Size After Last Property [ Dumper-7 ])
	struct FTransform                             StateATransform;                                   // 0x0130(0x0030)(Edit, BlueprintVisible, IsPlainOldData, NoDestructor, Protected, NativeAccessSpecifierProtected)
	struct FTransform                             StateBTransform;                                   // 0x0160(0x0030)(Edit, BlueprintVisible, IsPlainOldData, NoDestructor, Protected, NativeAccessSpecifierProtected)
	struct FVector                                StateAHalfExtent;                                  // 0x0190(0x000C)(Edit, BlueprintVisible, ZeroConstructor, IsPlainOldData, NoDestructor, Protected, HasGetValueTypeHash, NativeAccessSpecifierProtected)
	struct FVector                                StateBHalfExtent;                                  // 0x019C(0x000C)(Edit, BlueprintVisible, ZeroConstructor, IsPlainOldData, NoDestructor, Protected, HasGetValueTypeHash, NativeAccessSpecifierProtected)
	float                                         NavigationBoundsInflation;                         // 0x01A8(0x0004)(Edit, BlueprintVisible, ZeroConstructor, IsPlainOldData, NoDestructor, Protected, HasGetValueTypeHash, NativeAccessSpecifierProtected)
	bool                                          bPreserveDetailDuringBake;                         // 0x01AC(0x0001)(Edit, BlueprintVisible, ZeroConstructor, IsPlainOldData, NoDestructor, Protected, HasGetValueTypeHash, NativeAccessSpecifierProtected)
	EFlyingNavDynamicObstacleState                ActiveState;                                       // 0x01AD(0x0001)(Edit, BlueprintVisible, ZeroConstructor, IsPlainOldData, NoDestructor, Protected, HasGetValueTypeHash, NativeAccessSpecifierProtected)
	bool                                          bNavigationEnabled;                                // 0x01AE(0x0001)(Edit, BlueprintVisible, ZeroConstructor, IsPlainOldData, NoDestructor, Protected, HasGetValueTypeHash, NativeAccessSpecifierProtected)
	EFlyingNavDynamicObstacleState                DefaultState;                                      // 0x01AF(0x0001)(Edit, BlueprintVisible, ZeroConstructor, IsPlainOldData, NoDestructor, Protected, HasGetValueTypeHash, NativeAccessSpecifierProtected)
	uint8                                         Pad_1B0[0x20];                                     // 0x01B0(0x0020)(Fixing Struct Size After Last Property [ Dumper-7 ])

public:
	void SetActiveState(EFlyingNavDynamicObstacleState InState);
	void SetNavigationEnabled(bool bInEnabled);

	EFlyingNavDynamicObstacleState GetActiveState() const;
	bool IsNavigationEnabled() const;

public:
	static class UClass* StaticClass()
	{
		STATIC_CLASS_IMPL("FlyingNavDynamicObstacleGroupComponent")
	}
	static const class FName& StaticName()
	{
		STATIC_NAME_IMPL(L"FlyingNavDynamicObstacleGroupComponent")
	}
	static class UFlyingNavDynamicObstacleGroupComponent* GetDefaultObj()
	{
		return GetDefaultObjImpl<UFlyingNavDynamicObstacleGroupComponent>();
	}
};
DUMPER7_ASSERTS_UFlyingNavDynamicObstacleGroupComponent;

// Class FlyingNavSystem.FlyingNavDebugActor
// 0x00A8 (0x03B8 - 0x0310)
class AFlyingNavDebugActor final : public AActor
{
public:
	class USceneComponent*                        SceneRoot;                                         // 0x0310(0x0008)(Edit, ExportObject, ZeroConstructor, EditConst, InstancedReference, IsPlainOldData, NoDestructor, HasGetValueTypeHash, NativeAccessSpecifierPublic)
	class FName                                   AgentName;                                         // 0x0318(0x0008)(Edit, BlueprintVisible, ZeroConstructor, IsPlainOldData, NoDestructor, HasGetValueTypeHash, NativeAccessSpecifierPublic)
	EPathfindingAlgorithm                         Algorithm;                                         // 0x0320(0x0001)(Edit, BlueprintVisible, ZeroConstructor, IsPlainOldData, NoDestructor, HasGetValueTypeHash, NativeAccessSpecifierPublic)
	bool                                          bAllowPartialPaths;                                // 0x0321(0x0001)(Edit, BlueprintVisible, ZeroConstructor, IsPlainOldData, NoDestructor, HasGetValueTypeHash, NativeAccessSpecifierPublic)
	bool                                          bUseCoarseRouteCorridorConstraint;                 // 0x0322(0x0001)(Edit, BlueprintVisible, ZeroConstructor, IsPlainOldData, NoDestructor, HasGetValueTypeHash, NativeAccessSpecifierPublic)
	bool                                          bCollectRouteDiagnostics;                          // 0x0323(0x0001)(Edit, BlueprintVisible, ZeroConstructor, IsPlainOldData, NoDestructor, HasGetValueTypeHash, NativeAccessSpecifierPublic)
	float                                         SimAgentHeight;                                    // 0x0324(0x0004)(Edit, BlueprintVisible, ZeroConstructor, IsPlainOldData, NoDestructor, HasGetValueTypeHash, NativeAccessSpecifierPublic)
	float                                         SimAgentRadius;                                    // 0x0328(0x0004)(Edit, BlueprintVisible, ZeroConstructor, IsPlainOldData, NoDestructor, HasGetValueTypeHash, NativeAccessSpecifierPublic)
	bool                                          bPersistentDraw;                                   // 0x032C(0x0001)(Edit, BlueprintVisible, ZeroConstructor, IsPlainOldData, NoDestructor, HasGetValueTypeHash, NativeAccessSpecifierPublic)
	uint8                                         Pad_32D[0x3];                                      // 0x032D(0x0003)(Fixing Size After Last Property [ Dumper-7 ])
	float                                         DrawLifeTime;                                      // 0x0330(0x0004)(Edit, BlueprintVisible, ZeroConstructor, IsPlainOldData, NoDestructor, HasGetValueTypeHash, NativeAccessSpecifierPublic)
	float                                         PathLineThickness;                                 // 0x0334(0x0004)(Edit, BlueprintVisible, ZeroConstructor, IsPlainOldData, NoDestructor, HasGetValueTypeHash, NativeAccessSpecifierPublic)
	float                                         PathPointRadius;                                   // 0x0338(0x0004)(Edit, BlueprintVisible, ZeroConstructor, IsPlainOldData, NoDestructor, HasGetValueTypeHash, NativeAccessSpecifierPublic)
	float                                         MarkerRadius;                                      // 0x033C(0x0004)(Edit, BlueprintVisible, ZeroConstructor, IsPlainOldData, NoDestructor, HasGetValueTypeHash, NativeAccessSpecifierPublic)
	struct FColor                                 StartColor;                                        // 0x0340(0x0004)(Edit, BlueprintVisible, ZeroConstructor, IsPlainOldData, NoDestructor, HasGetValueTypeHash, NativeAccessSpecifierPublic)
	struct FColor                                 EndColor;                                          // 0x0344(0x0004)(Edit, BlueprintVisible, ZeroConstructor, IsPlainOldData, NoDestructor, HasGetValueTypeHash, NativeAccessSpecifierPublic)
	struct FColor                                 PathColor;                                         // 0x0348(0x0004)(Edit, BlueprintVisible, ZeroConstructor, IsPlainOldData, NoDestructor, HasGetValueTypeHash, NativeAccessSpecifierPublic)
	struct FColor                                 PartialPathColor;                                  // 0x034C(0x0004)(Edit, BlueprintVisible, ZeroConstructor, IsPlainOldData, NoDestructor, HasGetValueTypeHash, NativeAccessSpecifierPublic)
	bool                                          bDrawCoarsePath;                                   // 0x0350(0x0001)(Edit, BlueprintVisible, ZeroConstructor, IsPlainOldData, NoDestructor, HasGetValueTypeHash, NativeAccessSpecifierPublic)
	uint8                                         Pad_351[0x3];                                      // 0x0351(0x0003)(Fixing Size After Last Property [ Dumper-7 ])
	struct FColor                                 CoarsePathColor;                                   // 0x0354(0x0004)(Edit, BlueprintVisible, ZeroConstructor, IsPlainOldData, NoDestructor, HasGetValueTypeHash, NativeAccessSpecifierPublic)
	bool                                          bHasRecordedStart;                                 // 0x0358(0x0001)(Edit, BlueprintVisible, BlueprintReadOnly, ZeroConstructor, Transient, EditConst, IsPlainOldData, NoDestructor, HasGetValueTypeHash, NativeAccessSpecifierPublic)
	uint8                                         Pad_359[0x3];                                      // 0x0359(0x0003)(Fixing Size After Last Property [ Dumper-7 ])
	struct FVector                                RecordedStart;                                     // 0x035C(0x000C)(Edit, BlueprintVisible, BlueprintReadOnly, ZeroConstructor, Transient, EditConst, IsPlainOldData, NoDestructor, HasGetValueTypeHash, NativeAccessSpecifierPublic)
	class FString                                 ResultSummary;                                     // 0x0368(0x0010)(Edit, BlueprintVisible, BlueprintReadOnly, ZeroConstructor, Transient, EditConst, HasGetValueTypeHash, NativeAccessSpecifierPublic)
	uint8                                         Pad_378[0x40];                                     // 0x0378(0x0040)(Fixing Struct Size After Last Property [ Dumper-7 ])

public:
	void ClearDebugPath();
	void FindPathToPlayer();
	void MulticastApplyDebugConfig(class FName InAgentName, EPathfindingAlgorithm InAlgorithm);
	void MulticastApplyDebugResult(const class FString& InResultSummary, const TArray<struct FVector>& InPathPoints, const TArray<struct FVector>& InCoarsePathPoints, const struct FVector& InFailureStart, const struct FVector& InFailureEnd, bool bInHasPath, bool bInPathPartial, bool bInPathHighBudget, bool bInHasCoarsePath, bool bInHasFailure, const struct FVector& InRecordedStart, bool bInHasRecordedStart);
	void RecordStartFromPlayer();

public:
	static class UClass* StaticClass()
	{
		STATIC_CLASS_IMPL("FlyingNavDebugActor")
	}
	static const class FName& StaticName()
	{
		STATIC_NAME_IMPL(L"FlyingNavDebugActor")
	}
	static class AFlyingNavDebugActor* GetDefaultObj()
	{
		return GetDefaultObjImpl<AFlyingNavDebugActor>();
	}
};
DUMPER7_ASSERTS_AFlyingNavDebugActor;

// Class FlyingNavSystem.FlyingNavFunctionLibrary
// 0x0000 (0x0028 - 0x0028)
class UFlyingNavFunctionLibrary final : public UBlueprintFunctionLibrary
{
public:
	static void DrawNavPath(const class UObject* WorldContextObject, class UNavigationPath* NavPath, const struct FLinearColor& PathColor, const struct FVector& PathOffset, const bool bPersistent);
	static class UNavigationPath* FindPathToActorAsynchronously(class UObject* WorldContextObject, const struct FLatentActionInfo& LatentInfo, const struct FVector& PathStart, class AActor* GoalActor, float TetherDistance, class AActor* PathfindingContext, TSubclassOf<class UNavigationQueryFilter> FilterClass);
	static class UNavigationPath* FindPathToLocationAsynchronously(class UObject* WorldContextObject, const struct FLatentActionInfo& LatentInfo, const struct FVector& PathStart, const struct FVector& PathEnd, class AActor* PathfindingContext, TSubclassOf<class UNavigationQueryFilter> FilterClass);
	static struct FVector GetActorFeetLocation(const class APawn* Pawn);
	static struct FVector GetActorFeetOffset(const class APawn* Pawn);
	static float GetCelledNavMemoryUsageMB(const class APawn* NavAgent);
	static ECellState GetCellStateAtPosition(const class APawn* NavAgent, const struct FVector& WorldPosition);
	static class AFlyingNavigationData_V4* GetFlyingNavigationData(const class APawn* NavAgent);
	static EPathfindingResult GetPathfindingResult(class UNavigationPath* Path);
	static bool IsPositionAValidEndpoint(const class APawn* NavAgent, const struct FVector& Position, const bool bAllowBlocked);
	static bool IsPositionInLoadedCell(const class APawn* NavAgent, const struct FVector& WorldPosition);
	static class UCatmullRomSpline* MakeCatmullRomSpline(const TArray<struct FVector>& PathPoints);
	static void RebuildAllFlyingNavigation(const class UObject* WorldContextObject);
	static struct FAIRequestID RequestMove(class UNavigationPath* PathToFollow, class AAIController* Controller);
	static class UNavigationPath* SetNavigationPathPoints(const class UObject* WorldContextObject, class UNavigationPath* NavPath, const TArray<struct FVector>& PathPoints);
	static class UNavigationPath* SmoothPath(const class UObject* WorldContextObject, class UNavigationPath* Path, const float SampleLength);
	static TArray<struct FVector> SmoothPathPoints(const TArray<struct FVector>& PathPoints, const float SampleLength);

public:
	static class UClass* StaticClass()
	{
		STATIC_CLASS_IMPL("FlyingNavFunctionLibrary")
	}
	static const class FName& StaticName()
	{
		STATIC_NAME_IMPL(L"FlyingNavFunctionLibrary")
	}
	static class UFlyingNavFunctionLibrary* GetDefaultObj()
	{
		return GetDefaultObjImpl<UFlyingNavFunctionLibrary>();
	}
};
DUMPER7_ASSERTS_UFlyingNavFunctionLibrary;

// Class FlyingNavSystem.FlyingNavDetailVolume
// 0x0008 (0x0350 - 0x0348)
class AFlyingNavDetailVolume final : public AVolume
{
public:
	float                                         DetailSize;                                        // 0x0348(0x0004)(Edit, ZeroConstructor, IsPlainOldData, NoDestructor, HasGetValueTypeHash, NativeAccessSpecifierPublic)
	uint8                                         Pad_34C[0x4];                                      // 0x034C(0x0004)(Fixing Struct Size After Last Property [ Dumper-7 ])

public:
	static class UClass* StaticClass()
	{
		STATIC_CLASS_IMPL("FlyingNavDetailVolume")
	}
	static const class FName& StaticName()
	{
		STATIC_NAME_IMPL(L"FlyingNavDetailVolume")
	}
	static class AFlyingNavDetailVolume* GetDefaultObj()
	{
		return GetDefaultObjImpl<AFlyingNavDetailVolume>();
	}
};
DUMPER7_ASSERTS_AFlyingNavDetailVolume;

// Class FlyingNavSystem.FlyingNavDiagnosticActor
// 0x0030 (0x0340 - 0x0310)
class AFlyingNavDiagnosticActor final : public AActor
{
public:
	class UBoxComponent*                          DiagnosticVolume;                                  // 0x0310(0x0008)(Edit, ExportObject, ZeroConstructor, EditConst, InstancedReference, IsPlainOldData, NoDestructor, HasGetValueTypeHash, NativeAccessSpecifierPublic)
	class FName                                   AgentName;                                         // 0x0318(0x0008)(Edit, ZeroConstructor, IsPlainOldData, NoDestructor, HasGetValueTypeHash, NativeAccessSpecifierPublic)
	bool                                          bDrawFreeVoxels;                                   // 0x0320(0x0001)(Edit, ZeroConstructor, IsPlainOldData, NoDestructor, HasGetValueTypeHash, NativeAccessSpecifierPublic)
	bool                                          bDrawBlockedVoxels;                                // 0x0321(0x0001)(Edit, ZeroConstructor, IsPlainOldData, NoDestructor, HasGetValueTypeHash, NativeAccessSpecifierPublic)
	bool                                          bHighlightFalsePositives;                          // 0x0322(0x0001)(Edit, ZeroConstructor, IsPlainOldData, NoDestructor, HasGetValueTypeHash, NativeAccessSpecifierPublic)
	bool                                          bDrawCausingActorBounds;                           // 0x0323(0x0001)(Edit, ZeroConstructor, IsPlainOldData, NoDestructor, HasGetValueTypeHash, NativeAccessSpecifierPublic)
	bool                                          bDrawBlockingActorLinks;                           // 0x0324(0x0001)(Edit, ZeroConstructor, IsPlainOldData, NoDestructor, HasGetValueTypeHash, NativeAccessSpecifierPublic)
	uint8                                         Pad_325[0x3];                                      // 0x0325(0x0003)(Fixing Size After Last Property [ Dumper-7 ])
	float                                         PhysicsCheckExtentScale;                           // 0x0328(0x0004)(Edit, ZeroConstructor, IsPlainOldData, NoDestructor, HasGetValueTypeHash, NativeAccessSpecifierPublic)
	bool                                          bLogFalsePositiveDetails;                          // 0x032C(0x0001)(Edit, ZeroConstructor, IsPlainOldData, NoDestructor, HasGetValueTypeHash, NativeAccessSpecifierPublic)
	bool                                          bLogNavigationActors;                              // 0x032D(0x0001)(Edit, ZeroConstructor, IsPlainOldData, NoDestructor, HasGetValueTypeHash, NativeAccessSpecifierPublic)
	uint8                                         Pad_32E[0x2];                                      // 0x032E(0x0002)(Fixing Size After Last Property [ Dumper-7 ])
	int32                                         TotalSubNodesScanned;                              // 0x0330(0x0004)(Edit, ZeroConstructor, Transient, EditConst, IsPlainOldData, NoDestructor, HasGetValueTypeHash, NativeAccessSpecifierPublic)
	int32                                         BlockedCount;                                      // 0x0334(0x0004)(Edit, ZeroConstructor, Transient, EditConst, IsPlainOldData, NoDestructor, HasGetValueTypeHash, NativeAccessSpecifierPublic)
	int32                                         FreeCount;                                         // 0x0338(0x0004)(Edit, ZeroConstructor, Transient, EditConst, IsPlainOldData, NoDestructor, HasGetValueTypeHash, NativeAccessSpecifierPublic)
	int32                                         FalsePositiveCount;                                // 0x033C(0x0004)(Edit, ZeroConstructor, Transient, EditConst, IsPlainOldData, NoDestructor, HasGetValueTypeHash, NativeAccessSpecifierPublic)

public:
	static class UClass* StaticClass()
	{
		STATIC_CLASS_IMPL("FlyingNavDiagnosticActor")
	}
	static const class FName& StaticName()
	{
		STATIC_NAME_IMPL(L"FlyingNavDiagnosticActor")
	}
	static class AFlyingNavDiagnosticActor* GetDefaultObj()
	{
		return GetDefaultObjImpl<AFlyingNavDiagnosticActor>();
	}
};
DUMPER7_ASSERTS_AFlyingNavDiagnosticActor;

// Class FlyingNavSystem.CatmullRomSpline
// 0x0048 (0x0070 - 0x0028)
class UCatmullRomSpline final : public UObject
{
public:
	uint8                                         Pad_28[0x48];                                      // 0x0028(0x0048)(Fixing Struct Size After Last Property [ Dumper-7 ])

public:
	bool GenerateSpline(const TArray<struct FVector>& PathPoints);

	TArray<struct FVector> EquidistantSamples(const float SampleLength) const;
	float FindParameterForDistance(float Distance) const;
	float GetArcLength() const;
	struct FVector SampleSplineByDistance(const float Distance) const;
	struct FVector SampleSplineByParameter(const float T) const;

public:
	static class UClass* StaticClass()
	{
		STATIC_CLASS_IMPL("CatmullRomSpline")
	}
	static const class FName& StaticName()
	{
		STATIC_NAME_IMPL(L"CatmullRomSpline")
	}
	static class UCatmullRomSpline* GetDefaultObj()
	{
		return GetDefaultObjImpl<UCatmullRomSpline>();
	}
};
DUMPER7_ASSERTS_UCatmullRomSpline;

// Class FlyingNavSystem.FlyingNavigationData_V4
// 0x0200 (0x06F0 - 0x04F0)
class AFlyingNavigationData_V4 final : public ANavigationData
{
public:
	double                                        MaxDetailSize;                                     // 0x04F0(0x0008)(Edit, ZeroConstructor, Config, IsPlainOldData, NoDestructor, HasGetValueTypeHash, NativeAccessSpecifierPublic)
	double                                        MaxDetailSizeLargeWorld;                           // 0x04F8(0x0008)(Edit, ZeroConstructor, Config, IsPlainOldData, NoDestructor, HasGetValueTypeHash, NativeAccessSpecifierPublic)
	bool                                          bUseLargeWorldGranularity;                         // 0x0500(0x0001)(Edit, ZeroConstructor, Config, IsPlainOldData, NoDestructor, HasGetValueTypeHash, NativeAccessSpecifierPublic)
	uint8                                         Pad_501[0x3];                                      // 0x0501(0x0003)(Fixing Size After Last Property [ Dumper-7 ])
	uint8                                         bMultithreaded : 1;                                // 0x0504(0x0001)(BitIndex: 0x00, PropSize: 0x0001 (Edit, Config, NoDestructor, AdvancedDisplay, HasGetValueTypeHash, NativeAccessSpecifierPublic))
	uint8                                         Pad_505[0x3];                                      // 0x0505(0x0003)(Fixing Size After Last Property [ Dumper-7 ])
	EThreadSubdivisions                           ThreadSubdivisions;                                // 0x0508(0x0001)(Edit, ZeroConstructor, Config, IsPlainOldData, NoDestructor, AdvancedDisplay, HasGetValueTypeHash, NativeAccessSpecifierPublic)
	uint8                                         Pad_509[0x3];                                      // 0x0509(0x0003)(Fixing Size After Last Property [ Dumper-7 ])
	int32                                         MaxThreads;                                        // 0x050C(0x0004)(Edit, ZeroConstructor, Config, IsPlainOldData, NoDestructor, AdvancedDisplay, HasGetValueTypeHash, NativeAccessSpecifierPublic)
	uint8                                         bUseAgentRadius : 1;                               // 0x0510(0x0001)(BitIndex: 0x00, PropSize: 0x0001 (Edit, Config, NoDestructor, AdvancedDisplay, HasGetValueTypeHash, NativeAccessSpecifierPublic))
	uint8                                         bUseExclusiveBounds : 1;                           // 0x0510(0x0001)(BitIndex: 0x01, PropSize: 0x0001 (Edit, Config, NoDestructor, AdvancedDisplay, HasGetValueTypeHash, NativeAccessSpecifierPublic))
	uint8                                         bUsePreciseExclusiveBounds : 1;                    // 0x0510(0x0001)(BitIndex: 0x02, PropSize: 0x0001 (Edit, Config, NoDestructor, AdvancedDisplay, HasGetValueTypeHash, NativeAccessSpecifierPublic))
	uint8                                         bApplyLevelTransformOnBeginPlay : 1;               // 0x0510(0x0001)(BitIndex: 0x03, PropSize: 0x0001 (Edit, Config, NoDestructor, AdvancedDisplay, HasGetValueTypeHash, NativeAccessSpecifierPublic))
	uint8                                         bBuildOnBeginPlay : 1;                             // 0x0510(0x0001)(BitIndex: 0x04, PropSize: 0x0001 (Edit, Config, NoDestructor, HasGetValueTypeHash, NativeAccessSpecifierPublic))
	uint8                                         Pad_511[0x3];                                      // 0x0511(0x0003)(Fixing Size After Last Property [ Dumper-7 ])
	bool                                          bAutoCellSize;                                     // 0x0514(0x0001)(Edit, ZeroConstructor, Config, IsPlainOldData, NoDestructor, HasGetValueTypeHash, NativeAccessSpecifierPublic)
	uint8                                         Pad_515[0x3];                                      // 0x0515(0x0003)(Fixing Size After Last Property [ Dumper-7 ])
	int32                                         TargetVoxelsPerCellAxis;                           // 0x0518(0x0004)(Edit, ZeroConstructor, Config, IsPlainOldData, NoDestructor, HasGetValueTypeHash, NativeAccessSpecifierPublic)
	float                                         CellSize;                                          // 0x051C(0x0004)(Edit, ZeroConstructor, Config, IsPlainOldData, NoDestructor, HasGetValueTypeHash, NativeAccessSpecifierPublic)
	struct FSVOCelledConfig                       CelledNavConfig;                                   // 0x0520(0x0004)(Edit, Config, NoDestructor, NativeAccessSpecifierPublic)
	uint8                                         Pad_524[0x14];                                     // 0x0524(0x0014)(Fixing Size After Last Property [ Dumper-7 ])
	TMap<struct FIntVector, struct FSVOCellConfig> CellConfigOverrides;                              // 0x0538(0x0050)(Edit, Config, NativeAccessSpecifierPublic)
	int32                                         DetailTransitionLayers;                            // 0x0588(0x0004)(Edit, ZeroConstructor, Config, IsPlainOldData, NoDestructor, HasGetValueTypeHash, NativeAccessSpecifierPublic)
	int32                                         NoCoarsenNearObstacleLayers;                       // 0x058C(0x0004)(Edit, ZeroConstructor, Config, IsPlainOldData, NoDestructor, HasGetValueTypeHash, NativeAccessSpecifierPublic)
	bool                                          bFillTinyLeafAirPockets;                           // 0x0590(0x0001)(Edit, ZeroConstructor, Config, IsPlainOldData, NoDestructor, HasGetValueTypeHash, NativeAccessSpecifierPublic)
	uint8                                         Pad_591[0x3];                                      // 0x0591(0x0003)(Fixing Size After Last Property [ Dumper-7 ])
	int32                                         TinyLeafAirPocketMaxSubNodes;                      // 0x0594(0x0004)(Edit, ZeroConstructor, Config, IsPlainOldData, NoDestructor, HasGetValueTypeHash, NativeAccessSpecifierPublic)
	struct FSVOQuerySettings                      DefaultQuerySettings;                              // 0x0598(0x0090)(Edit, Config, NativeAccessSpecifierPublic)
	float                                         AsyncTimeSlicedDistanceThresholdCm;                // 0x0628(0x0004)(Edit, BlueprintVisible, ZeroConstructor, Config, IsPlainOldData, NoDestructor, HasGetValueTypeHash, NativeAccessSpecifierPublic)
	uint8                                         ProjectPointExtent;                                // 0x062C(0x0001)(Edit, BlueprintVisible, ZeroConstructor, Config, IsPlainOldData, NoDestructor, HasGetValueTypeHash, NativeAccessSpecifierPublic)
	uint8                                         Pad_62D[0x3];                                      // 0x062D(0x0003)(Fixing Size After Last Property [ Dumper-7 ])
	uint8                                         bDrawBlockedVoxels : 1;                            // 0x0630(0x0001)(BitIndex: 0x00, PropSize: 0x0001 (Edit, NoDestructor, HasGetValueTypeHash, NativeAccessSpecifierPublic))
	uint8                                         bDrawFreeVoxels : 1;                               // 0x0630(0x0001)(BitIndex: 0x01, PropSize: 0x0001 (Edit, NoDestructor, HasGetValueTypeHash, NativeAccessSpecifierPublic))
	uint8                                         bDrawOctreeNodes : 1;                              // 0x0630(0x0001)(BitIndex: 0x02, PropSize: 0x0001 (Edit, NoDestructor, HasGetValueTypeHash, NativeAccessSpecifierPublic))
	uint8                                         bColourByConnected : 1;                            // 0x0630(0x0001)(BitIndex: 0x03, PropSize: 0x0001 (Edit, NoDestructor, HasGetValueTypeHash, NativeAccessSpecifierPublic))
	uint8                                         Pad_631[0x3];                                      // 0x0631(0x0003)(Fixing Size After Last Property [ Dumper-7 ])
	float                                         NodeMargin;                                        // 0x0634(0x0004)(Edit, ZeroConstructor, IsPlainOldData, NoDestructor, HasGetValueTypeHash, NativeAccessSpecifierPublic)
	float                                         WireThickness;                                     // 0x0638(0x0004)(Edit, ZeroConstructor, IsPlainOldData, NoDestructor, HasGetValueTypeHash, NativeAccessSpecifierPublic)
	uint8                                         bDrawNeighbourConnections : 1;                     // 0x063C(0x0001)(BitIndex: 0x00, PropSize: 0x0001 (Edit, NoDestructor, HasGetValueTypeHash, NativeAccessSpecifierPublic))
	uint8                                         bDrawSimplifiedConnections : 1;                    // 0x063C(0x0001)(BitIndex: 0x01, PropSize: 0x0001 (Edit, NoDestructor, HasGetValueTypeHash, NativeAccessSpecifierPublic))
	uint8                                         Pad_63D[0x3];                                      // 0x063D(0x0003)(Fixing Size After Last Property [ Dumper-7 ])
	float                                         NodeCentreRadius;                                  // 0x0640(0x0004)(Edit, ZeroConstructor, IsPlainOldData, NoDestructor, HasGetValueTypeHash, NativeAccessSpecifierPublic)
	uint8                                         Pad_644[0x4];                                      // 0x0644(0x0004)(Fixing Size After Last Property [ Dumper-7 ])
	TMulticastInlineDelegate<void()>              OnFlyingNavGenerationFinished;                     // 0x0648(0x0010)(ZeroConstructor, InstancedReference, BlueprintAssignable, NativeAccessSpecifierPublic)
	uint8                                         Pad_658[0x98];                                     // 0x0658(0x0098)(Fixing Struct Size After Last Property [ Dumper-7 ])

public:
	void RebuildFlyingNavigation(class UObject* WorldContextObject, const struct FLatentActionInfo& LatentInfo);
	void RebuildNavigationData();
	void StopRebuild();

	float CurrentlyBuiltVoxelSize() const;
	bool IsNavigationDataBuilt() const;
	bool OctreeRaycast(const struct FVector& RayStart, const struct FVector& RayEnd, struct FVector* HitLocation) const;

public:
	static class UClass* StaticClass()
	{
		STATIC_CLASS_IMPL("FlyingNavigationData_V4")
	}
	static const class FName& StaticName()
	{
		STATIC_NAME_IMPL(L"FlyingNavigationData_V4")
	}
	static class AFlyingNavigationData_V4* GetDefaultObj()
	{
		return GetDefaultObjImpl<AFlyingNavigationData_V4>();
	}
};
DUMPER7_ASSERTS_AFlyingNavigationData_V4;

// Class FlyingNavSystem.FlyingNavigationSystem
// 0x0000 (0x0550 - 0x0550)
class UFlyingNavigationSystem final : public UNavigationSystemV1
{
public:
	static class UClass* StaticClass()
	{
		STATIC_CLASS_IMPL("FlyingNavigationSystem")
	}
	static const class FName& StaticName()
	{
		STATIC_NAME_IMPL(L"FlyingNavigationSystem")
	}
	static class UFlyingNavigationSystem* GetDefaultObj()
	{
		return GetDefaultObjImpl<UFlyingNavigationSystem>();
	}
};
DUMPER7_ASSERTS_UFlyingNavigationSystem;

// Class FlyingNavSystem.FlyingNavTestActor
// 0x00F0 (0x0400 - 0x0310)
class AFlyingNavTestActor final : public AActor
{
public:
	class USceneComponent*                        SceneRoot;                                         // 0x0310(0x0008)(Edit, ExportObject, ZeroConstructor, EditConst, InstancedReference, IsPlainOldData, NoDestructor, HasGetValueTypeHash, NativeAccessSpecifierPublic)
	class USphereComponent*                       StartPoint;                                        // 0x0318(0x0008)(Edit, ExportObject, ZeroConstructor, EditConst, InstancedReference, IsPlainOldData, NoDestructor, HasGetValueTypeHash, NativeAccessSpecifierPublic)
	class USphereComponent*                       EndPoint;                                          // 0x0320(0x0008)(Edit, ExportObject, ZeroConstructor, EditConst, InstancedReference, IsPlainOldData, NoDestructor, HasGetValueTypeHash, NativeAccessSpecifierPublic)
	class USplineComponent*                       PathSpline_AStar;                                  // 0x0328(0x0008)(Edit, ExportObject, ZeroConstructor, EditConst, InstancedReference, IsPlainOldData, NoDestructor, HasGetValueTypeHash, NativeAccessSpecifierPublic)
	class USplineComponent*                       PathSpline_ThetaStar;                              // 0x0330(0x0008)(Edit, ExportObject, ZeroConstructor, EditConst, InstancedReference, IsPlainOldData, NoDestructor, HasGetValueTypeHash, NativeAccessSpecifierPublic)
	class USplineComponent*                       PathSpline_LazyThetaStar;                          // 0x0338(0x0008)(Edit, ExportObject, ZeroConstructor, EditConst, InstancedReference, IsPlainOldData, NoDestructor, HasGetValueTypeHash, NativeAccessSpecifierPublic)
	class USplineComponent*                       PathSpline_CoarseRoute;                            // 0x0340(0x0008)(Edit, ExportObject, ZeroConstructor, EditConst, InstancedReference, IsPlainOldData, NoDestructor, HasGetValueTypeHash, NativeAccessSpecifierPublic)
	TArray<class USplineComponent*>               SingleRoutePathSplines;                            // 0x0348(0x0010)(ExportObject, ZeroConstructor, Transient, ContainsInstancedReference, HasGetValueTypeHash, NativeAccessSpecifierPublic)
	class FName                                   AgentName;                                         // 0x0358(0x0008)(Edit, ZeroConstructor, IsPlainOldData, NoDestructor, HasGetValueTypeHash, NativeAccessSpecifierPublic)
	float                                         SimAgentHeight;                                    // 0x0360(0x0004)(Edit, BlueprintVisible, ZeroConstructor, IsPlainOldData, NoDestructor, HasGetValueTypeHash, NativeAccessSpecifierPublic)
	float                                         SimAgentRadius;                                    // 0x0364(0x0004)(Edit, BlueprintVisible, ZeroConstructor, IsPlainOldData, NoDestructor, HasGetValueTypeHash, NativeAccessSpecifierPublic)
	bool                                          bAutoFindOnMove;                                   // 0x0368(0x0001)(Edit, ZeroConstructor, IsPlainOldData, NoDestructor, HasGetValueTypeHash, NativeAccessSpecifierPublic)
	uint8                                         Pad_369[0x3];                                      // 0x0369(0x0003)(Fixing Size After Last Property [ Dumper-7 ])
	float                                         AutoFindDelaySeconds;                              // 0x036C(0x0004)(Edit, ZeroConstructor, IsPlainOldData, NoDestructor, HasGetValueTypeHash, NativeAccessSpecifierPublic)
	bool                                          bConnectivityOnly;                                 // 0x0370(0x0001)(Edit, ZeroConstructor, IsPlainOldData, NoDestructor, HasGetValueTypeHash, NativeAccessSpecifierPublic)
	bool                                          bFailFastWhenDisconnected;                         // 0x0371(0x0001)(Edit, ZeroConstructor, IsPlainOldData, NoDestructor, HasGetValueTypeHash, NativeAccessSpecifierPublic)
	bool                                          bAllowPartialPaths;                                // 0x0372(0x0001)(Edit, ZeroConstructor, IsPlainOldData, NoDestructor, HasGetValueTypeHash, NativeAccessSpecifierPublic)
	bool                                          bRunAStar;                                         // 0x0373(0x0001)(Edit, ZeroConstructor, IsPlainOldData, NoDestructor, HasGetValueTypeHash, NativeAccessSpecifierPublic)
	bool                                          bRunThetaStar;                                     // 0x0374(0x0001)(Edit, ZeroConstructor, IsPlainOldData, NoDestructor, HasGetValueTypeHash, NativeAccessSpecifierPublic)
	bool                                          bRunLazyThetaStar;                                 // 0x0375(0x0001)(Edit, ZeroConstructor, IsPlainOldData, NoDestructor, HasGetValueTypeHash, NativeAccessSpecifierPublic)
	uint8                                         Pad_376[0x2];                                      // 0x0376(0x0002)(Fixing Size After Last Property [ Dumper-7 ])
	struct FLinearColor                           AStarColor;                                        // 0x0378(0x0010)(Edit, ZeroConstructor, IsPlainOldData, NoDestructor, HasGetValueTypeHash, NativeAccessSpecifierPublic)
	struct FLinearColor                           ThetaStarColor;                                    // 0x0388(0x0010)(Edit, ZeroConstructor, IsPlainOldData, NoDestructor, HasGetValueTypeHash, NativeAccessSpecifierPublic)
	struct FLinearColor                           LazyThetaStarColor;                                // 0x0398(0x0010)(Edit, ZeroConstructor, IsPlainOldData, NoDestructor, HasGetValueTypeHash, NativeAccessSpecifierPublic)
	bool                                          bDrawRawPathPoints;                                // 0x03A8(0x0001)(Edit, ZeroConstructor, IsPlainOldData, NoDestructor, HasGetValueTypeHash, NativeAccessSpecifierPublic)
	uint8                                         Pad_3A9[0x3];                                      // 0x03A9(0x0003)(Fixing Size After Last Property [ Dumper-7 ])
	float                                         RawPointRadius;                                    // 0x03AC(0x0004)(Edit, ZeroConstructor, IsPlainOldData, NoDestructor, HasGetValueTypeHash, NativeAccessSpecifierPublic)
	bool                                          bDrawFinalPathPointLabels;                         // 0x03B0(0x0001)(Edit, ZeroConstructor, IsPlainOldData, NoDestructor, HasGetValueTypeHash, NativeAccessSpecifierPublic)
	bool                                          bLogFinalPathPointStats;                           // 0x03B1(0x0001)(Edit, ZeroConstructor, IsPlainOldData, NoDestructor, HasGetValueTypeHash, NativeAccessSpecifierPublic)
	uint8                                         Pad_3B2[0x2];                                      // 0x03B2(0x0002)(Fixing Size After Last Property [ Dumper-7 ])
	float                                         DenseFinalPointDistanceCm;                         // 0x03B4(0x0004)(Edit, ZeroConstructor, IsPlainOldData, NoDestructor, HasGetValueTypeHash, NativeAccessSpecifierPublic)
	float                                         HeightTurnWarnCm;                                  // 0x03B8(0x0004)(Edit, ZeroConstructor, IsPlainOldData, NoDestructor, HasGetValueTypeHash, NativeAccessSpecifierPublic)
	bool                                          bDrawCoarseRoute;                                  // 0x03BC(0x0001)(Edit, ZeroConstructor, IsPlainOldData, NoDestructor, HasGetValueTypeHash, NativeAccessSpecifierPublic)
	uint8                                         Pad_3BD[0x3];                                      // 0x03BD(0x0003)(Fixing Size After Last Property [ Dumper-7 ])
	struct FLinearColor                           CoarseRouteColor;                                  // 0x03C0(0x0010)(Edit, ZeroConstructor, IsPlainOldData, NoDestructor, HasGetValueTypeHash, NativeAccessSpecifierPublic)
	bool                                          bDrawCoarseRouteRegionBounds;                      // 0x03D0(0x0001)(Edit, ZeroConstructor, IsPlainOldData, NoDestructor, HasGetValueTypeHash, NativeAccessSpecifierPublic)
	bool                                          bDrawCoarseRouteRegionLabels;                      // 0x03D1(0x0001)(Edit, ZeroConstructor, IsPlainOldData, NoDestructor, HasGetValueTypeHash, NativeAccessSpecifierPublic)
	bool                                          bDrawCoarseRouteContactBounds;                     // 0x03D2(0x0001)(Edit, ZeroConstructor, IsPlainOldData, NoDestructor, HasGetValueTypeHash, NativeAccessSpecifierPublic)
	bool                                          bSingleRouteDebug;                                 // 0x03D3(0x0001)(Edit, ZeroConstructor, IsPlainOldData, NoDestructor, HasGetValueTypeHash, NativeAccessSpecifierPublic)
	EPathfindingAlgorithm                         SingleRouteAlgorithm;                              // 0x03D4(0x0001)(Edit, ZeroConstructor, IsPlainOldData, NoDestructor, HasGetValueTypeHash, NativeAccessSpecifierPublic)
	uint8                                         Pad_3D5[0x3];                                      // 0x03D5(0x0003)(Fixing Size After Last Property [ Dumper-7 ])
	int32                                         SingleRouteTargetCount;                            // 0x03D8(0x0004)(Edit, ZeroConstructor, IsPlainOldData, NoDestructor, HasGetValueTypeHash, NativeAccessSpecifierPublic)
	float                                         SingleRouteMinRadiusCm;                            // 0x03DC(0x0004)(Edit, ZeroConstructor, IsPlainOldData, NoDestructor, HasGetValueTypeHash, NativeAccessSpecifierPublic)
	float                                         SingleRouteMaxRadiusCm;                            // 0x03E0(0x0004)(Edit, ZeroConstructor, IsPlainOldData, NoDestructor, HasGetValueTypeHash, NativeAccessSpecifierPublic)
	int32                                         SingleRouteAttemptsPerTarget;                      // 0x03E4(0x0004)(Edit, ZeroConstructor, IsPlainOldData, NoDestructor, HasGetValueTypeHash, NativeAccessSpecifierPublic)
	int32                                         SingleRouteRandomSeed;                             // 0x03E8(0x0004)(Edit, ZeroConstructor, IsPlainOldData, NoDestructor, HasGetValueTypeHash, NativeAccessSpecifierPublic)
	uint8                                         Pad_3EC[0x4];                                      // 0x03EC(0x0004)(Fixing Size After Last Property [ Dumper-7 ])
	class FString                                 ResultSummary;                                     // 0x03F0(0x0010)(Edit, ZeroConstructor, Transient, EditConst, HasGetValueTypeHash, NativeAccessSpecifierPublic)

public:
	static class UClass* StaticClass()
	{
		STATIC_CLASS_IMPL("FlyingNavTestActor")
	}
	static const class FName& StaticName()
	{
		STATIC_NAME_IMPL(L"FlyingNavTestActor")
	}
	static class AFlyingNavTestActor* GetDefaultObj()
	{
		return GetDefaultObjImpl<AFlyingNavTestActor>();
	}
};
DUMPER7_ASSERTS_AFlyingNavTestActor;

// Class FlyingNavSystem.OctreeRenderingComponent
// 0x0080 (0x0550 - 0x04D0)
class UOctreeRenderingComponent final : public UMeshComponent
{
public:
	uint8                                         Pad_4D0[0x8];                                      // 0x04D0(0x0008)(Fixing Size After Last Property [ Dumper-7 ])
	class UMaterialInstanceDynamic*               WireMaterial;                                      // 0x04D8(0x0008)(ZeroConstructor, IsPlainOldData, NoDestructor, Protected, HasGetValueTypeHash, NativeAccessSpecifierProtected)
	uint8                                         Pad_4E0[0x70];                                     // 0x04E0(0x0070)(Fixing Struct Size After Last Property [ Dumper-7 ])

public:
	static class UClass* StaticClass()
	{
		STATIC_CLASS_IMPL("OctreeRenderingComponent")
	}
	static const class FName& StaticName()
	{
		STATIC_NAME_IMPL(L"OctreeRenderingComponent")
	}
	static class UOctreeRenderingComponent* GetDefaultObj()
	{
		return GetDefaultObjImpl<UOctreeRenderingComponent>();
	}
};
DUMPER7_ASSERTS_UOctreeRenderingComponent;

// Class FlyingNavSystem.PathBatchComponent
// 0x0040 (0x0530 - 0x04F0)
class UPathBatchComponent final : public ULineBatchComponent
{
public:
	uint8                                         Pad_4F0[0x40];                                     // 0x04F0(0x0040)(Fixing Struct Size After Last Property [ Dumper-7 ])

public:
	static class UClass* StaticClass()
	{
		STATIC_CLASS_IMPL("PathBatchComponent")
	}
	static const class FName& StaticName()
	{
		STATIC_NAME_IMPL(L"PathBatchComponent")
	}
	static class UPathBatchComponent* GetDefaultObj()
	{
		return GetDefaultObjImpl<UPathBatchComponent>();
	}
};
DUMPER7_ASSERTS_UPathBatchComponent;

SDK_NAMESPACE_END
