#pragma once

/*
* SDK generated by Dumper-7
*
* https://github.com/Encryqed/Dumper-7
*/

// Package: GA_E_Maddelena

#include "Basic.hpp"

#include "PMGame_classes.hpp"


SDK_NAMESPACE_START

// BlueprintGeneratedClass GA_E_Maddelena.GA_E_Maddelena_C
// 0x0000 (0x1B08 - 0x1B08)
class UGA_E_Maddelena_C final : public UCyBaseAbility
{
public:
	static class UClass* StaticClass()
	{
		BP_STATIC_CLASS_IMPL("GA_E_Maddelena_C")
	}
	static const class FName& StaticName()
	{
		STATIC_NAME_IMPL(L"GA_E_Maddelena_C")
	}
	static class UGA_E_Maddelena_C* GetDefaultObj()
	{
		return GetDefaultObjImpl<UGA_E_Maddelena_C>();
	}
};
DUMPER7_ASSERTS_UGA_E_Maddelena_C;

SDK_NAMESPACE_END
