#pragma once

/*
* SDK generated by Dumper-7
*
* https://github.com/Encryqed/Dumper-7
*/

// Package: GA_P_Leona

#include "Basic.hpp"

#include "PMGame_classes.hpp"


SDK_NAMESPACE_START

// BlueprintGeneratedClass GA_P_Leona.GA_P_Leona_C
// 0x0000 (0x1B08 - 0x1B08)
class UGA_P_Leona_C final : public UCyBaseAbility
{
public:
	static class UClass* StaticClass()
	{
		BP_STATIC_CLASS_IMPL("GA_P_Leona_C")
	}
	static const class FName& StaticName()
	{
		STATIC_NAME_IMPL(L"GA_P_Leona_C")
	}
	static class UGA_P_Leona_C* GetDefaultObj()
	{
		return GetDefaultObjImpl<UGA_P_Leona_C>();
	}
};
DUMPER7_ASSERTS_UGA_P_Leona_C;

SDK_NAMESPACE_END
