#pragma once

/*
* SDK generated by Dumper-7
*
* https://github.com/Encryqed/Dumper-7
*/

// Package: GA_X_Yugiri

#include "Basic.hpp"

#include "PMGame_classes.hpp"


SDK_NAMESPACE_START

// BlueprintGeneratedClass GA_X_Yugiri.GA_X_Yugiri_C
// 0x0000 (0x1B08 - 0x1B08)
class UGA_X_Yugiri_C final : public UCyBaseAbility
{
public:
	static class UClass* StaticClass()
	{
		BP_STATIC_CLASS_IMPL("GA_X_Yugiri_C")
	}
	static const class FName& StaticName()
	{
		STATIC_NAME_IMPL(L"GA_X_Yugiri_C")
	}
	static class UGA_X_Yugiri_C* GetDefaultObj()
	{
		return GetDefaultObjImpl<UGA_X_Yugiri_C>();
	}
};
DUMPER7_ASSERTS_UGA_X_Yugiri_C;

SDK_NAMESPACE_END
