#pragma once

/*
* SDK generated by Dumper-7
*
* https://github.com/Encryqed/Dumper-7
*/

// Package: GA_X_Nobunaga_0

#include "Basic.hpp"

#include "PMGame_classes.hpp"


SDK_NAMESPACE_START

// BlueprintGeneratedClass GA_X_Nobunaga.GA_X_Nobunaga_C
// 0x0000 (0x1B08 - 0x1B08)
class GA_X_Nobunaga_0::UGA_X_Nobunaga_C final : public UCyBaseAbility
{
public:
	static class UClass* StaticClass()
	{
		BP_STATIC_CLASS_IMPL_FULLNAME("BlueprintGeneratedClass GA_X_Nobunaga.GA_X_Nobunaga_C")
	}
	static const class FName& StaticName()
	{
		STATIC_NAME_IMPL(L"GA_X_Nobunaga_C")
	}
	static class GA_X_Nobunaga_0::UGA_X_Nobunaga_C* GetDefaultObj()
	{
		return GetDefaultObjImpl<GA_X_Nobunaga_0::UGA_X_Nobunaga_C>();
	}
};
DUMPER7_ASSERTS_GA_X_Nobunaga_0__UGA_X_Nobunaga_C;

SDK_NAMESPACE_END
