#pragma once

/*
* SDK generated by Dumper-7
*
* https://github.com/Encryqed/Dumper-7
*/

// Package: GC_Nobunaga_P

#include "Basic.hpp"

#include "PMGame_classes.hpp"


SDK_NAMESPACE_START

// BlueprintGeneratedClass GC_Nobunaga_P.GC_Nobunaga_P_C
// 0x0008 (0x04F8 - 0x04F0)
class AGC_Nobunaga_P_C final : public ACyCueNotifyActor
{
public:
	class USceneComponent*                        DefaultSceneRoot;                                  // 0x04F0(0x0008)(BlueprintVisible, ZeroConstructor, InstancedReference, IsPlainOldData, NonTransactional, NoDestructor, HasGetValueTypeHash)

public:
	static class UClass* StaticClass()
	{
		BP_STATIC_CLASS_IMPL("GC_Nobunaga_P_C")
	}
	static const class FName& StaticName()
	{
		STATIC_NAME_IMPL(L"GC_Nobunaga_P_C")
	}
	static class AGC_Nobunaga_P_C* GetDefaultObj()
	{
		return GetDefaultObjImpl<AGC_Nobunaga_P_C>();
	}
};
DUMPER7_ASSERTS_AGC_Nobunaga_P_C;

SDK_NAMESPACE_END
