#pragma once

/*
* SDK generated by Dumper-7
*
* https://github.com/Encryqed/Dumper-7
*/

// Package: GC_Yugiri_Q_Close

#include "Basic.hpp"

#include "PMGame_classes.hpp"


SDK_NAMESPACE_START

// BlueprintGeneratedClass GC_Yugiri_Q_Close.GC_Yugiri_Q_Close_C
// 0x0000 (0x0050 - 0x0050)
class UGC_Yugiri_Q_Close_C final : public UCyCueNotify_Static
{
public:
	static class UClass* StaticClass()
	{
		BP_STATIC_CLASS_IMPL("GC_Yugiri_Q_Close_C")
	}
	static const class FName& StaticName()
	{
		STATIC_NAME_IMPL(L"GC_Yugiri_Q_Close_C")
	}
	static class UGC_Yugiri_Q_Close_C* GetDefaultObj()
	{
		return GetDefaultObjImpl<UGC_Yugiri_Q_Close_C>();
	}
};
DUMPER7_ASSERTS_UGC_Yugiri_Q_Close_C;

SDK_NAMESPACE_END
