#pragma once

/*
* SDK generated by Dumper-7
*
* https://github.com/Encryqed/Dumper-7
*/

// Package: GE_AllowSendEventToOnDodge_P_MoBai

#include "Basic.hpp"

#include "PMGame_classes.hpp"


SDK_NAMESPACE_START

// BlueprintGeneratedClass GE_AllowSendEventToOnDodge_P_MoBai.GE_AllowSendEventToOnDodge_P_MoBai_C
// 0x0000 (0x10E0 - 0x10E0)
class UGE_AllowSendEventToOnDodge_P_MoBai_C final : public UCyGameplayEffect
{
public:
	static class UClass* StaticClass()
	{
		BP_STATIC_CLASS_IMPL("GE_AllowSendEventToOnDodge_P_MoBai_C")
	}
	static const class FName& StaticName()
	{
		STATIC_NAME_IMPL(L"GE_AllowSendEventToOnDodge_P_MoBai_C")
	}
	static class UGE_AllowSendEventToOnDodge_P_MoBai_C* GetDefaultObj()
	{
		return GetDefaultObjImpl<UGE_AllowSendEventToOnDodge_P_MoBai_C>();
	}
};
DUMPER7_ASSERTS_UGE_AllowSendEventToOnDodge_P_MoBai_C;

SDK_NAMESPACE_END
