#pragma once

/*
* SDK generated by Dumper-7
*
* https://github.com/Encryqed/Dumper-7
*/

// Package: GE_ArousalOne_Ming_0

#include "Basic.hpp"

#include "GameplayAbilities_classes.hpp"


SDK_NAMESPACE_START

// BlueprintGeneratedClass GE_ArousalOne_Ming.GE_ArousalOne_Ming_C
// 0x0000 (0x1060 - 0x1060)
class GE_ArousalOne_Ming_0::UGE_ArousalOne_Ming_C final : public UGameplayEffect
{
public:
	static class UClass* StaticClass()
	{
		BP_STATIC_CLASS_IMPL_FULLNAME("BlueprintGeneratedClass GE_ArousalOne_Ming.GE_ArousalOne_Ming_C")
	}
	static const class FName& StaticName()
	{
		STATIC_NAME_IMPL(L"GE_ArousalOne_Ming_C")
	}
	static class GE_ArousalOne_Ming_0::UGE_ArousalOne_Ming_C* GetDefaultObj()
	{
		return GetDefaultObjImpl<GE_ArousalOne_Ming_0::UGE_ArousalOne_Ming_C>();
	}
};
DUMPER7_ASSERTS_GE_ArousalOne_Ming_0__UGE_ArousalOne_Ming_C;

SDK_NAMESPACE_END
