#pragma once

/*
* SDK generated by Dumper-7
*
* https://github.com/Encryqed/Dumper-7
*/

// Package: GE_AddProperty_Q_Nobunaga_Lv1_0

#include "Basic.hpp"

#include "GameplayAbilities_classes.hpp"


SDK_NAMESPACE_START

// BlueprintGeneratedClass GE_AddProperty_Q_Nobunaga_Lv1.GE_AddProperty_Q_Nobunaga_Lv1_C
// 0x0000 (0x1060 - 0x1060)
class GE_AddProperty_Q_Nobunaga_Lv1_0::UGE_AddProperty_Q_Nobunaga_Lv1_C final : public UGameplayEffect
{
public:
	static class UClass* StaticClass()
	{
		BP_STATIC_CLASS_IMPL_FULLNAME("BlueprintGeneratedClass GE_AddProperty_Q_Nobunaga_Lv1.GE_AddProperty_Q_Nobunaga_Lv1_C")
	}
	static const class FName& StaticName()
	{
		STATIC_NAME_IMPL(L"GE_AddProperty_Q_Nobunaga_Lv1_C")
	}
	static class GE_AddProperty_Q_Nobunaga_Lv1_0::UGE_AddProperty_Q_Nobunaga_Lv1_C* GetDefaultObj()
	{
		return GetDefaultObjImpl<GE_AddProperty_Q_Nobunaga_Lv1_0::UGE_AddProperty_Q_Nobunaga_Lv1_C>();
	}
};
DUMPER7_ASSERTS_GE_AddProperty_Q_Nobunaga_Lv1_0__UGE_AddProperty_Q_Nobunaga_Lv1_C;

SDK_NAMESPACE_END
