#pragma once

/*
* SDK generated by Dumper-7
*
* https://github.com/Encryqed/Dumper-7
*/

// Package: GE_Flavia_ExtraArmorMax

#include "Basic.hpp"

#include "PMGame_classes.hpp"


SDK_NAMESPACE_START

// BlueprintGeneratedClass GE_Flavia_ExtraArmorMax.GE_Flavia_ExtraArmorMax_C
// 0x0000 (0x10E0 - 0x10E0)
class UGE_Flavia_ExtraArmorMax_C final : public UCyGameplayEffect
{
public:
	static class UClass* StaticClass()
	{
		BP_STATIC_CLASS_IMPL("GE_Flavia_ExtraArmorMax_C")
	}
	static const class FName& StaticName()
	{
		STATIC_NAME_IMPL(L"GE_Flavia_ExtraArmorMax_C")
	}
	static class UGE_Flavia_ExtraArmorMax_C* GetDefaultObj()
	{
		return GetDefaultObjImpl<UGE_Flavia_ExtraArmorMax_C>();
	}
};
DUMPER7_ASSERTS_UGE_Flavia_ExtraArmorMax_C;

SDK_NAMESPACE_END
