#pragma once

/*
* SDK generated by Dumper-7
*
* https://github.com/Encryqed/Dumper-7
*/

// Package: GE_Growth_TeamDeath_Lv2_Infinite

#include "Basic.hpp"

#include "PMGame_classes.hpp"


SDK_NAMESPACE_START

// BlueprintGeneratedClass GE_Growth_TeamDeath_Lv2_Infinite.GE_Growth_TeamDeath_Lv2_Infinite_C
// 0x0000 (0x10E0 - 0x10E0)
class UGE_Growth_TeamDeath_Lv2_Infinite_C final : public UCyGameplayEffect
{
public:
	static class UClass* StaticClass()
	{
		BP_STATIC_CLASS_IMPL("GE_Growth_TeamDeath_Lv2_Infinite_C")
	}
	static const class FName& StaticName()
	{
		STATIC_NAME_IMPL(L"GE_Growth_TeamDeath_Lv2_Infinite_C")
	}
	static class UGE_Growth_TeamDeath_Lv2_Infinite_C* GetDefaultObj()
	{
		return GetDefaultObjImpl<UGE_Growth_TeamDeath_Lv2_Infinite_C>();
	}
};
DUMPER7_ASSERTS_UGE_Growth_TeamDeath_Lv2_Infinite_C;

SDK_NAMESPACE_END
