#pragma once

/*
* SDK generated by Dumper-7
*
* https://github.com/Encryqed/Dumper-7
*/

// Package: GE_GiftChargedTimeSpeedFactor_10013

#include "Basic.hpp"

#include "PMGame_classes.hpp"


SDK_NAMESPACE_START

// BlueprintGeneratedClass GE_GiftChargedTimeSpeedFactor_10013.GE_GiftChargedTimeSpeedFactor_10013_C
// 0x0000 (0x10E0 - 0x10E0)
class UGE_GiftChargedTimeSpeedFactor_10013_C final : public UCyGameplayEffect
{
public:
	static class UClass* StaticClass()
	{
		BP_STATIC_CLASS_IMPL("GE_GiftChargedTimeSpeedFactor_10013_C")
	}
	static const class FName& StaticName()
	{
		STATIC_NAME_IMPL(L"GE_GiftChargedTimeSpeedFactor_10013_C")
	}
	static class UGE_GiftChargedTimeSpeedFactor_10013_C* GetDefaultObj()
	{
		return GetDefaultObjImpl<UGE_GiftChargedTimeSpeedFactor_10013_C>();
	}
};
DUMPER7_ASSERTS_UGE_GiftChargedTimeSpeedFactor_10013_C;

SDK_NAMESPACE_END
