#pragma once

/*
* SDK generated by Dumper-7
*
* https://github.com/Encryqed/Dumper-7
*/

// Package: GE_HealthRecoveryTeam_Q_CrystalloidBeta1

#include "Basic.hpp"

#include "PMGame_classes.hpp"


SDK_NAMESPACE_START

// BlueprintGeneratedClass GE_HealthRecoveryTeam_Q_CrystalloidBeta1.GE_HealthRecoveryTeam_Q_CrystalloidBeta1_C
// 0x0000 (0x10E0 - 0x10E0)
class UGE_HealthRecoveryTeam_Q_CrystalloidBeta1_C final : public UCyGameplayEffect
{
public:
	static class UClass* StaticClass()
	{
		BP_STATIC_CLASS_IMPL("GE_HealthRecoveryTeam_Q_CrystalloidBeta1_C")
	}
	static const class FName& StaticName()
	{
		STATIC_NAME_IMPL(L"GE_HealthRecoveryTeam_Q_CrystalloidBeta1_C")
	}
	static class UGE_HealthRecoveryTeam_Q_CrystalloidBeta1_C* GetDefaultObj()
	{
		return GetDefaultObjImpl<UGE_HealthRecoveryTeam_Q_CrystalloidBeta1_C>();
	}
};
DUMPER7_ASSERTS_UGE_HealthRecoveryTeam_Q_CrystalloidBeta1_C;

SDK_NAMESPACE_END
