#pragma once

/*
* SDK generated by Dumper-7
*
* https://github.com/Encryqed/Dumper-7
*/

// Package: GE_NoReload_0

#include "Basic.hpp"

#include "PMGame_classes.hpp"


SDK_NAMESPACE_START

// BlueprintGeneratedClass GE_NoReload.GE_NoReload_C
// 0x0000 (0x10E0 - 0x10E0)
class GE_NoReload_0::UGE_NoReload_C final : public UCyGameplayEffect
{
public:
	static class UClass* StaticClass()
	{
		BP_STATIC_CLASS_IMPL_FULLNAME("BlueprintGeneratedClass GE_NoReload.GE_NoReload_C")
	}
	static const class FName& StaticName()
	{
		STATIC_NAME_IMPL(L"GE_NoReload_C")
	}
	static class GE_NoReload_0::UGE_NoReload_C* GetDefaultObj()
	{
		return GetDefaultObjImpl<GE_NoReload_0::UGE_NoReload_C>();
	}
};
DUMPER7_ASSERTS_GE_NoReload_0__UGE_NoReload_C;

SDK_NAMESPACE_END
