#pragma once

/*
* SDK generated by Dumper-7
*
* https://github.com/Encryqed/Dumper-7
*/

// Package: GE_P_RemoveCharging_Nobunaga

#include "Basic.hpp"

#include "GameplayAbilities_classes.hpp"


SDK_NAMESPACE_START

// BlueprintGeneratedClass GE_P_RemoveCharging_Nobunaga.GE_P_RemoveCharging_Nobunaga_C
// 0x0000 (0x1060 - 0x1060)
class UGE_P_RemoveCharging_Nobunaga_C final : public UGameplayEffect
{
public:
	static class UClass* StaticClass()
	{
		BP_STATIC_CLASS_IMPL("GE_P_RemoveCharging_Nobunaga_C")
	}
	static const class FName& StaticName()
	{
		STATIC_NAME_IMPL(L"GE_P_RemoveCharging_Nobunaga_C")
	}
	static class UGE_P_RemoveCharging_Nobunaga_C* GetDefaultObj()
	{
		return GetDefaultObjImpl<UGE_P_RemoveCharging_Nobunaga_C>();
	}
};
DUMPER7_ASSERTS_UGE_P_RemoveCharging_Nobunaga_C;

SDK_NAMESPACE_END
