#pragma once

/*
* SDK generated by Dumper-7
*
* https://github.com/Encryqed/Dumper-7
*/

// Package: GE_Q_HuixingSelf

#include "Basic.hpp"

#include "PMGame_classes.hpp"


SDK_NAMESPACE_START

// BlueprintGeneratedClass GE_Q_HuixingSelf.GE_Q_HuixingSelf_C
// 0x0000 (0x10E0 - 0x10E0)
class UGE_Q_HuixingSelf_C final : public UCyGameplayEffect
{
public:
	static class UClass* StaticClass()
	{
		BP_STATIC_CLASS_IMPL("GE_Q_HuixingSelf_C")
	}
	static const class FName& StaticName()
	{
		STATIC_NAME_IMPL(L"GE_Q_HuixingSelf_C")
	}
	static class UGE_Q_HuixingSelf_C* GetDefaultObj()
	{
		return GetDefaultObjImpl<UGE_Q_HuixingSelf_C>();
	}
};
DUMPER7_ASSERTS_UGE_Q_HuixingSelf_C;

SDK_NAMESPACE_END
