#pragma once

/*
* SDK generated by Dumper-7
*
* https://github.com/Encryqed/Dumper-7
*/

// Package: GE_Q_Ming_Damage

#include "Basic.hpp"

#include "PMGame_classes.hpp"


SDK_NAMESPACE_START

// BlueprintGeneratedClass GE_Q_Ming_Damage.GE_Q_Ming_Damage_C
// 0x0000 (0x10E0 - 0x10E0)
class GE_Q_Ming_Damage::UGE_Q_Ming_Damage_C final : public UCyGameplayEffect
{
public:
	static class UClass* StaticClass()
	{
		BP_STATIC_CLASS_IMPL_FULLNAME("BlueprintGeneratedClass GE_Q_Ming_Damage.GE_Q_Ming_Damage_C")
	}
	static const class FName& StaticName()
	{
		STATIC_NAME_IMPL(L"GE_Q_Ming_Damage_C")
	}
	static class GE_Q_Ming_Damage::UGE_Q_Ming_Damage_C* GetDefaultObj()
	{
		return GetDefaultObjImpl<GE_Q_Ming_Damage::UGE_Q_Ming_Damage_C>();
	}
};
DUMPER7_ASSERTS_GE_Q_Ming_Damage__UGE_Q_Ming_Damage_C;

SDK_NAMESPACE_END
