#pragma once

/*
* SDK generated by Dumper-7
*
* https://github.com/Encryqed/Dumper-7
*/

// Package: GE_SquareSafeZone_Warning

#include "Basic.hpp"

#include "PMGame_classes.hpp"


SDK_NAMESPACE_START

// BlueprintGeneratedClass GE_SquareSafeZone_Warning.GE_SquareSafeZone_Warning_C
// 0x0000 (0x10E0 - 0x10E0)
class UGE_SquareSafeZone_Warning_C final : public UCyGameplayEffect
{
public:
	static class UClass* StaticClass()
	{
		BP_STATIC_CLASS_IMPL("GE_SquareSafeZone_Warning_C")
	}
	static const class FName& StaticName()
	{
		STATIC_NAME_IMPL(L"GE_SquareSafeZone_Warning_C")
	}
	static class UGE_SquareSafeZone_Warning_C* GetDefaultObj()
	{
		return GetDefaultObjImpl<UGE_SquareSafeZone_Warning_C>();
	}
};
DUMPER7_ASSERTS_UGE_SquareSafeZone_Warning_C;

SDK_NAMESPACE_END
