#pragma once

/*
* SDK generated by Dumper-7
*
* https://github.com/Encryqed/Dumper-7
*/

// Package: GE_X_HuiXing_ExtraArmorMax_Add_Self

#include "Basic.hpp"

#include "PMGame_classes.hpp"


SDK_NAMESPACE_START

// BlueprintGeneratedClass GE_X_HuiXing_ExtraArmorMax_Add_Self.GE_X_HuiXing_ExtraArmorMax_Add_Self_C
// 0x0000 (0x10E0 - 0x10E0)
class UGE_X_HuiXing_ExtraArmorMax_Add_Self_C final : public UCyGameplayEffect
{
public:
	static class UClass* StaticClass()
	{
		BP_STATIC_CLASS_IMPL("GE_X_HuiXing_ExtraArmorMax_Add_Self_C")
	}
	static const class FName& StaticName()
	{
		STATIC_NAME_IMPL(L"GE_X_HuiXing_ExtraArmorMax_Add_Self_C")
	}
	static class UGE_X_HuiXing_ExtraArmorMax_Add_Self_C* GetDefaultObj()
	{
		return GetDefaultObjImpl<UGE_X_HuiXing_ExtraArmorMax_Add_Self_C>();
	}
};
DUMPER7_ASSERTS_UGE_X_HuiXing_ExtraArmorMax_Add_Self_C;

SDK_NAMESPACE_END
