#pragma once

/*
* SDK generated by Dumper-7
*
* https://github.com/Encryqed/Dumper-7
*/

// Package: LobbyWeapon

#include "Basic.hpp"

#include "PMGame_classes.hpp"


SDK_NAMESPACE_START

// BlueprintGeneratedClass LobbyWeapon.LobbyWeapon_C
// 0x0000 (0x1350 - 0x1350)
class ALobbyWeapon_C final : public ACyLobbyWeapon
{
public:
	static class UClass* StaticClass()
	{
		BP_STATIC_CLASS_IMPL("LobbyWeapon_C")
	}
	static const class FName& StaticName()
	{
		STATIC_NAME_IMPL(L"LobbyWeapon_C")
	}
	static class ALobbyWeapon_C* GetDefaultObj()
	{
		return GetDefaultObjImpl<ALobbyWeapon_C>();
	}
};
DUMPER7_ASSERTS_ALobbyWeapon_C;

SDK_NAMESPACE_END
