#pragma once

/*
* SDK generated by Dumper-7
*
* https://github.com/Encryqed/Dumper-7
*/

// Package: PM_BTTask_AlwaysTrue

#include "Basic.hpp"


SDK_NAMESPACE_START
SDK_PARAM_NAMESPACE_START

// Function PM_BTTask_AlwaysTrue.PM_BTTask_AlwaysTrue_C.ReceiveExecuteAI
// 0x0010 (0x0010 - 0x0000)
struct PM_BTTask_AlwaysTrue_C_ReceiveExecuteAI final
{
public:
	class AAIController*                          OwnerController_ReceiveExecuteAI;                  // 0x0000(0x0008)(BlueprintVisible, BlueprintReadOnly, Parm, ZeroConstructor, IsPlainOldData, NoDestructor, HasGetValueTypeHash)
	class APawn*                                  ControlledPawn_ReceiveExecuteAI;                   // 0x0008(0x0008)(BlueprintVisible, BlueprintReadOnly, Parm, ZeroConstructor, IsPlainOldData, NoDestructor, HasGetValueTypeHash)
};
DUMPER7_ASSERTS_PM_BTTask_AlwaysTrue_C_ReceiveExecuteAI;

// Function PM_BTTask_AlwaysTrue.PM_BTTask_AlwaysTrue_C.ExecuteUbergraph_PM_BTTask_AlwaysTrue
// 0x0018 (0x0018 - 0x0000)
struct PM_BTTask_AlwaysTrue_C_ExecuteUbergraph_PM_BTTask_AlwaysTrue final
{
public:
	int32                                         EntryPoint;                                        // 0x0000(0x0004)(BlueprintVisible, BlueprintReadOnly, Parm, ZeroConstructor, IsPlainOldData, NoDestructor, HasGetValueTypeHash)
	uint8                                         Pad_4[0x4];                                        // 0x0004(0x0004)(Fixing Size After Last Property [ Dumper-7 ])
	class AAIController*                          K2Node_Event_OwnerController;                      // 0x0008(0x0008)(ZeroConstructor, IsPlainOldData, NoDestructor, HasGetValueTypeHash)
	class APawn*                                  K2Node_Event_ControlledPawn;                       // 0x0010(0x0008)(ZeroConstructor, IsPlainOldData, NoDestructor, HasGetValueTypeHash)
};
DUMPER7_ASSERTS_PM_BTTask_AlwaysTrue_C_ExecuteUbergraph_PM_BTTask_AlwaysTrue;

SDK_PARAM_NAMESPACE_END
SDK_NAMESPACE_END
