#pragma once

/*
* SDK generated by Dumper-7
*
* https://github.com/Encryqed/Dumper-7
*/

// Package: PM_BTTask_DoAction

#include "Basic.hpp"

#include "PM_BTTask_DoAction_classes.hpp"
#include "PM_BTTask_DoAction_parameters.hpp"


SDK_NAMESPACE_START

// Function PM_BTTask_DoAction.PM_BTTask_DoAction_C.ReceiveExecuteAI
// (Event, Protected, BlueprintEvent)
// Parameters:
// class AAIController*                    OwnerController_ReceiveExecuteAI                       (BlueprintVisible, BlueprintReadOnly, Parm, ZeroConstructor, IsPlainOldData, NoDestructor, HasGetValueTypeHash)
// class APawn*                            ControlledPawn_ReceiveExecuteAI                        (BlueprintVisible, BlueprintReadOnly, Parm, ZeroConstructor, IsPlainOldData, NoDestructor, HasGetValueTypeHash)

void UPM_BTTask_DoAction_C::ReceiveExecuteAI(class AAIController* OwnerController_ReceiveExecuteAI, class APawn* ControlledPawn_ReceiveExecuteAI)
{
	static class UFunction* Func = nullptr;

	if (Func == nullptr)
		Func = Class->GetFunction("PM_BTTask_DoAction_C", "ReceiveExecuteAI");

	Params::PM_BTTask_DoAction_C_ReceiveExecuteAI Parms{};

	Parms.OwnerController_ReceiveExecuteAI = OwnerController_ReceiveExecuteAI;
	Parms.ControlledPawn_ReceiveExecuteAI = ControlledPawn_ReceiveExecuteAI;

	UObject::ProcessEvent(Func, &Parms);
}


// Function PM_BTTask_DoAction.PM_BTTask_DoAction_C.ExecuteUbergraph_PM_BTTask_DoAction
// (Final, UbergraphFunction)
// Parameters:
// int32                                   EntryPoint                                             (BlueprintVisible, BlueprintReadOnly, Parm, ZeroConstructor, IsPlainOldData, NoDestructor, HasGetValueTypeHash)

void UPM_BTTask_DoAction_C::ExecuteUbergraph_PM_BTTask_DoAction(int32 EntryPoint)
{
	static class UFunction* Func = nullptr;

	if (Func == nullptr)
		Func = Class->GetFunction("PM_BTTask_DoAction_C", "ExecuteUbergraph_PM_BTTask_DoAction");

	Params::PM_BTTask_DoAction_C_ExecuteUbergraph_PM_BTTask_DoAction Parms{};

	Parms.EntryPoint = EntryPoint;

	UObject::ProcessEvent(Func, &Parms);
}


SDK_NAMESPACE_END
