#pragma once

/*
* SDK generated by Dumper-7
*
* https://github.com/Encryqed/Dumper-7
*/

// Package: Preview_XRm_Mara

#include "Basic.hpp"

#include "PMGame_classes.hpp"


SDK_NAMESPACE_START

// BlueprintGeneratedClass Preview_XRm_Mara.Preview_XRm_Mara_C
// 0x0020 (0x08C0 - 0x08A0)
class APreview_XRm_Mara_C final : public ACySummonActor
{
public:
	uint8                                         Pad_898[0x8];                                      // 0x0898(0x0008)(Fixing Size After Last Property [ Dumper-7 ])
	class UCySceneMapTwoPointLineComponent*       CySceneMapTwoPointLine;                            // 0x08A0(0x0008)(BlueprintVisible, ZeroConstructor, InstancedReference, IsPlainOldData, NonTransactional, NoDestructor, HasGetValueTypeHash)
	class UCyPreviewComponent*                    CyPreview;                                         // 0x08A8(0x0008)(BlueprintVisible, ZeroConstructor, InstancedReference, IsPlainOldData, NonTransactional, NoDestructor, HasGetValueTypeHash)
	class UCySkinComponent*                       CySkin;                                            // 0x08B0(0x0008)(BlueprintVisible, ZeroConstructor, InstancedReference, IsPlainOldData, NonTransactional, NoDestructor, HasGetValueTypeHash)
	class USceneComponent*                        DefaultSceneRoot;                                  // 0x08B8(0x0008)(BlueprintVisible, ZeroConstructor, InstancedReference, IsPlainOldData, NonTransactional, NoDestructor, HasGetValueTypeHash)

public:
	static class UClass* StaticClass()
	{
		BP_STATIC_CLASS_IMPL("Preview_XRm_Mara_C")
	}
	static const class FName& StaticName()
	{
		STATIC_NAME_IMPL(L"Preview_XRm_Mara_C")
	}
	static class APreview_XRm_Mara_C* GetDefaultObj()
	{
		return GetDefaultObjImpl<APreview_XRm_Mara_C>();
	}
};
DUMPER7_ASSERTS_APreview_XRm_Mara_C;

SDK_NAMESPACE_END
