#pragma once

/*
* SDK generated by Dumper-7
*
* https://github.com/Encryqed/Dumper-7
*/

// Package: Projectile_E_Ming_Escort2

#include "Basic.hpp"

#include "Projectile_E_Ming_Escort2_classes.hpp"
#include "Projectile_E_Ming_Escort2_parameters.hpp"


SDK_NAMESPACE_START

// Function Projectile_E_Ming_Escort2.Projectile_E_Ming_Escort2_C.ExecuteUbergraph_Projectile_E_Ming_Escort2
// (Final, UbergraphFunction)
// Parameters:
// int32                                   EntryPoint                                             (BlueprintVisible, BlueprintReadOnly, Parm, ZeroConstructor, IsPlainOldData, NoDestructor, HasGetValueTypeHash)

void AProjectile_E_Ming_Escort2_C::ExecuteUbergraph_Projectile_E_Ming_Escort2(int32 EntryPoint)
{
	static class UFunction* Func = nullptr;

	if (Func == nullptr)
		Func = Class->GetFunction("Projectile_E_Ming_Escort2_C", "ExecuteUbergraph_Projectile_E_Ming_Escort2");

	Params::Projectile_E_Ming_Escort2_C_ExecuteUbergraph_Projectile_E_Ming_Escort2 Parms{};

	Parms.EntryPoint = EntryPoint;

	UObject::ProcessEvent(Func, &Parms);
}


// Function Projectile_E_Ming_Escort2.Projectile_E_Ming_Escort2_C.ReceiveBeginPlay
// (Event, Protected, BlueprintEvent)

void AProjectile_E_Ming_Escort2_C::ReceiveBeginPlay()
{
	static class UFunction* Func = nullptr;

	if (Func == nullptr)
		Func = Class->GetFunction("Projectile_E_Ming_Escort2_C", "ReceiveBeginPlay");

	UObject::ProcessEvent(Func, nullptr);
}


SDK_NAMESPACE_END
