#pragma once

/*
* SDK generated by Dumper-7
*
* https://github.com/Encryqed/Dumper-7
*/

// Package: Projectile_ArousalTwo_Lawine

#include "Basic.hpp"

#include "PMGame_classes.hpp"


SDK_NAMESPACE_START

// BlueprintGeneratedClass Projectile_ArousalTwo_Lawine.Projectile_ArousalTwo_Lawine_C
// 0x0008 (0x0B58 - 0x0B50)
class Projectile_ArousalTwo_Lawine::AProjectile_ArousalTwo_Lawine_C final : public ACyProjectileBlast
{
public:
	class UCyRetainComponent*                     CyRetain;                                          // 0x0B50(0x0008)(BlueprintVisible, ZeroConstructor, InstancedReference, IsPlainOldData, NonTransactional, NoDestructor, HasGetValueTypeHash)

public:
	static class UClass* StaticClass()
	{
		BP_STATIC_CLASS_IMPL_FULLNAME("BlueprintGeneratedClass Projectile_ArousalTwo_Lawine.Projectile_ArousalTwo_Lawine_C")
	}
	static const class FName& StaticName()
	{
		STATIC_NAME_IMPL(L"Projectile_ArousalTwo_Lawine_C")
	}
	static class Projectile_ArousalTwo_Lawine::AProjectile_ArousalTwo_Lawine_C* GetDefaultObj()
	{
		return GetDefaultObjImpl<Projectile_ArousalTwo_Lawine::AProjectile_ArousalTwo_Lawine_C>();
	}
};
DUMPER7_ASSERTS_Projectile_ArousalTwo_Lawine__AProjectile_ArousalTwo_Lawine_C;

SDK_NAMESPACE_END
