#pragma once

/*
* SDK generated by Dumper-7
*
* https://github.com/Encryqed/Dumper-7
*/

// Package: Projectile18101001

#include "Basic.hpp"

#include "PMGame_classes.hpp"


SDK_NAMESPACE_START

// BlueprintGeneratedClass Projectile18101001.Projectile18101001_C
// 0x0008 (0x0B58 - 0x0B50)
class AProjectile18101001_C final : public ACyProjectileBlast
{
public:
	class UCyDataManagerComponent*                CyDataManager;                                     // 0x0B50(0x0008)(BlueprintVisible, ZeroConstructor, InstancedReference, IsPlainOldData, NonTransactional, NoDestructor, HasGetValueTypeHash)

public:
	static class UClass* StaticClass()
	{
		BP_STATIC_CLASS_IMPL("Projectile18101001_C")
	}
	static const class FName& StaticName()
	{
		STATIC_NAME_IMPL(L"Projectile18101001_C")
	}
	static class AProjectile18101001_C* GetDefaultObj()
	{
		return GetDefaultObjImpl<AProjectile18101001_C>();
	}
};
DUMPER7_ASSERTS_AProjectile18101001_C;

SDK_NAMESPACE_END
