#pragma once

/*
* SDK generated by Dumper-7
*
* https://github.com/Encryqed/Dumper-7
*/

// Package: Projectile_E_Michele_MB

#include "Basic.hpp"

#include "PMGame_classes.hpp"


SDK_NAMESPACE_START

// BlueprintGeneratedClass Projectile_E_Michele_MB.Projectile_E_Michele_MB_C
// 0x0000 (0x0B50 - 0x0B50)
class AProjectile_E_Michele_MB_C final : public ACyProjectileBlast
{
public:
	static class UClass* StaticClass()
	{
		BP_STATIC_CLASS_IMPL("Projectile_E_Michele_MB_C")
	}
	static const class FName& StaticName()
	{
		STATIC_NAME_IMPL(L"Projectile_E_Michele_MB_C")
	}
	static class AProjectile_E_Michele_MB_C* GetDefaultObj()
	{
		return GetDefaultObjImpl<AProjectile_E_Michele_MB_C>();
	}
};
DUMPER7_ASSERTS_AProjectile_E_Michele_MB_C;

SDK_NAMESPACE_END
