#pragma once

/*
* SDK generated by Dumper-7
*
* https://github.com/Encryqed/Dumper-7
*/

// Package: Projectile_Primary_Nora_Summon

#include "Basic.hpp"

#include "Projectile_Q_Summon_Nora_classes.hpp"


SDK_NAMESPACE_START

// BlueprintGeneratedClass Projectile_Primary_Nora_Summon.Projectile_Primary_Nora_Summon_C
// 0x0000 (0x0828 - 0x0828)
class AProjectile_Primary_Nora_Summon_C final : public AProjectile_Q_Summon_Nora_C
{
public:
	static class UClass* StaticClass()
	{
		BP_STATIC_CLASS_IMPL("Projectile_Primary_Nora_Summon_C")
	}
	static const class FName& StaticName()
	{
		STATIC_NAME_IMPL(L"Projectile_Primary_Nora_Summon_C")
	}
	static class AProjectile_Primary_Nora_Summon_C* GetDefaultObj()
	{
		return GetDefaultObjImpl<AProjectile_Primary_Nora_Summon_C>();
	}
};
DUMPER7_ASSERTS_AProjectile_Primary_Nora_Summon_C;

SDK_NAMESPACE_END
