#pragma once

/*
* SDK generated by Dumper-7
*
* https://github.com/Encryqed/Dumper-7
*/

// Package: Projectile18105001

#include "Basic.hpp"

#include "PMGame_classes.hpp"


SDK_NAMESPACE_START

// BlueprintGeneratedClass Projectile18105001.Projectile18105001_C
// 0x0008 (0x07F0 - 0x07E8)
class AProjectile18105001_C final : public ACyProjectileBase
{
public:
	class UCyDataManagerComponent*                CyDataManager;                                     // 0x07E8(0x0008)(BlueprintVisible, ZeroConstructor, InstancedReference, IsPlainOldData, NonTransactional, NoDestructor, HasGetValueTypeHash)

public:
	static class UClass* StaticClass()
	{
		BP_STATIC_CLASS_IMPL("Projectile18105001_C")
	}
	static const class FName& StaticName()
	{
		STATIC_NAME_IMPL(L"Projectile18105001_C")
	}
	static class AProjectile18105001_C* GetDefaultObj()
	{
		return GetDefaultObjImpl<AProjectile18105001_C>();
	}
};
DUMPER7_ASSERTS_AProjectile18105001_C;

SDK_NAMESPACE_END
