#pragma once

/*
* SDK generated by Dumper-7
*
* https://github.com/Encryqed/Dumper-7
*/

// Package: SubAnimBP_Grenade

#include "Basic.hpp"

#include "ALSV4_CPP_classes.hpp"
#include "AnimGraphRuntime_structs.hpp"
#include "Engine_structs.hpp"


SDK_NAMESPACE_START

// DynamicClass SubAnimBP_Grenade.SubAnimBP_Grenade_C
// 0x0620 (0x0B10 - 0x04F0)
class USubAnimBP_Grenade_C final : public UCySubAnimInstanceDefault
{
public:
	struct FAnimNode_Root                         AnimGraphNode_Root;                                // 0x04E8(0x0030)(NativeAccessSpecifierPublic)
	struct FAnimNode_ApplyAdditive                AnimGraphNode_ApplyAdditive;                       // 0x0518(0x00E8)(NativeAccessSpecifierPublic)
	struct FAnimNode_TwoWayBlend                  AnimGraphNode_TwoWayBlend_2;                       // 0x0600(0x00C8)(NativeAccessSpecifierPublic)
	struct FAnimNode_TwoWayBlend                  AnimGraphNode_TwoWayBlend_1;                       // 0x06C8(0x00C8)(NativeAccessSpecifierPublic)
	struct FAnimNode_TwoWayBlend                  AnimGraphNode_TwoWayBlend;                         // 0x0790(0x00C8)(NativeAccessSpecifierPublic)
	struct FAnimNode_SequencePlayer               AnimGraphNode_SequencePlayer;                      // 0x0858(0x0080)(NativeAccessSpecifierPublic)
	struct FAnimNode_SequenceEvaluator            AnimGraphNode_SequenceEvaluator_4;                 // 0x08D8(0x0050)(NativeAccessSpecifierPublic)
	struct FAnimNode_SequenceEvaluator            AnimGraphNode_SequenceEvaluator_3;                 // 0x0928(0x0050)(NativeAccessSpecifierPublic)
	struct FAnimNode_SequenceEvaluator            AnimGraphNode_SequenceEvaluator_2;                 // 0x0978(0x0050)(NativeAccessSpecifierPublic)
	struct FAnimNode_SequenceEvaluator            AnimGraphNode_SequenceEvaluator_1;                 // 0x09C8(0x0050)(NativeAccessSpecifierPublic)
	struct FAnimNode_BlendListByBool              AnimGraphNode_BlendListByBool;                     // 0x0A18(0x00A0)(NativeAccessSpecifierPublic)
	struct FAnimNode_SequenceEvaluator            AnimGraphNode_SequenceEvaluator;                   // 0x0AB8(0x0050)(NativeAccessSpecifierPublic)
	uint8                                         Pad_B08[0x8];                                      // 0x0B08(0x0008)(Fixing Struct Size After Last Property [ Dumper-7 ])

public:
	void AnimGraph(struct FPoseLink* bpp__AnimGraph__pf);
	void ExecuteUbergraph_SubAnimBP_Grenade(int32 bpp__EntryPoint__pf);

public:
	static class UClass* StaticClass()
	{
		STATIC_CLASS_IMPL("SubAnimBP_Grenade_C")
	}
	static const class FName& StaticName()
	{
		STATIC_NAME_IMPL(L"SubAnimBP_Grenade_C")
	}
	static class USubAnimBP_Grenade_C* GetDefaultObj()
	{
		return GetDefaultObjImpl<USubAnimBP_Grenade_C>();
	}
};
DUMPER7_ASSERTS_USubAnimBP_Grenade_C;

SDK_NAMESPACE_END
