#pragma once

/*
* SDK generated by Dumper-7
*
* https://github.com/Encryqed/Dumper-7
*/

// Package: Summon_CheckCharacterBlock

#include "Basic.hpp"

#include "Engine_structs.hpp"
#include "PMGame_classes.hpp"


SDK_NAMESPACE_START

// BlueprintGeneratedClass Summon_CheckCharacterBlock.Summon_CheckCharacterBlock_C
// 0x0030 (0x08D0 - 0x08A0)
class ASummon_CheckCharacterBlock_C final : public ACySummonActor
{
public:
	uint8                                         Pad_898[0x8];                                      // 0x0898(0x0008)(Fixing Size After Last Property [ Dumper-7 ])
	struct FPointerToUberGraphFrame               UberGraphFrame;                                    // 0x08A0(0x0008)(ZeroConstructor, Transient, DuplicateTransient)
	class USkeletalMeshComponent*                 SkeletalMesh;                                      // 0x08A8(0x0008)(BlueprintVisible, ZeroConstructor, InstancedReference, IsPlainOldData, NonTransactional, NoDestructor, HasGetValueTypeHash)
	class UCySearchTargetsComponent*              CySearchTargets;                                   // 0x08B0(0x0008)(BlueprintVisible, ZeroConstructor, InstancedReference, IsPlainOldData, NonTransactional, NoDestructor, HasGetValueTypeHash)
	class UCyAIWorkState*                         CyAIWorkState;                                     // 0x08B8(0x0008)(BlueprintVisible, ZeroConstructor, InstancedReference, IsPlainOldData, NonTransactional, NoDestructor, HasGetValueTypeHash)
	class UCyAIMachine*                           CyAIMachine;                                       // 0x08C0(0x0008)(BlueprintVisible, ZeroConstructor, InstancedReference, IsPlainOldData, NonTransactional, NoDestructor, HasGetValueTypeHash)
	class USceneComponent*                        DefaultSceneRoot;                                  // 0x08C8(0x0008)(BlueprintVisible, ZeroConstructor, InstancedReference, IsPlainOldData, NonTransactional, NoDestructor, HasGetValueTypeHash)

public:
	void ReceiveTick(float DeltaSeconds_ReceiveTick);
	void ExecuteUbergraph_Summon_CheckCharacterBlock(int32 EntryPoint);

public:
	static class UClass* StaticClass()
	{
		BP_STATIC_CLASS_IMPL("Summon_CheckCharacterBlock_C")
	}
	static const class FName& StaticName()
	{
		STATIC_NAME_IMPL(L"Summon_CheckCharacterBlock_C")
	}
	static class ASummon_CheckCharacterBlock_C* GetDefaultObj()
	{
		return GetDefaultObjImpl<ASummon_CheckCharacterBlock_C>();
	}
};
DUMPER7_ASSERTS_ASummon_CheckCharacterBlock_C;

SDK_NAMESPACE_END
