#pragma once

/*
* SDK generated by Dumper-7
*
* https://github.com/Encryqed/Dumper-7
*/

// Package: Summon_X_Chiyo

#include "Basic.hpp"

#include "Summon_X_Chiyo_classes.hpp"
#include "Summon_X_Chiyo_parameters.hpp"


SDK_NAMESPACE_START

// Function Summon_X_Chiyo.Summon_X_Chiyo_C.ExecuteUbergraph_Summon_X_Chiyo
// (Final, UbergraphFunction)
// Parameters:
// int32                                   EntryPoint                                             (BlueprintVisible, BlueprintReadOnly, Parm, ZeroConstructor, IsPlainOldData, NoDestructor, HasGetValueTypeHash)

void ASummon_X_Chiyo_C::ExecuteUbergraph_Summon_X_Chiyo(int32 EntryPoint)
{
	static class UFunction* Func = nullptr;

	if (Func == nullptr)
		Func = Class->GetFunction("Summon_X_Chiyo_C", "ExecuteUbergraph_Summon_X_Chiyo");

	Params::Summon_X_Chiyo_C_ExecuteUbergraph_Summon_X_Chiyo Parms{};

	Parms.EntryPoint = EntryPoint;

	UObject::ProcessEvent(Func, &Parms);
}


// Function Summon_X_Chiyo.Summon_X_Chiyo_C.ReceiveBeginPlay
// (Event, Protected, BlueprintEvent)

void ASummon_X_Chiyo_C::ReceiveBeginPlay()
{
	static class UFunction* Func = nullptr;

	if (Func == nullptr)
		Func = Class->GetFunction("Summon_X_Chiyo_C", "ReceiveBeginPlay");

	UObject::ProcessEvent(Func, nullptr);
}


SDK_NAMESPACE_END
