#pragma once

/*
* SDK generated by Dumper-7
*
* https://github.com/Encryqed/Dumper-7
*/

// Package: Trajectory206

#include "Basic.hpp"

#include "BP_BulletTrajectoryBase_classes.hpp"


SDK_NAMESPACE_START

// BlueprintGeneratedClass Trajectory206.Trajectory206_C
// 0x0000 (0x0330 - 0x0330)
class ATrajectory206_C final : public ABP_BulletTrajectoryBase_C
{
public:
	static class UClass* StaticClass()
	{
		BP_STATIC_CLASS_IMPL("Trajectory206_C")
	}
	static const class FName& StaticName()
	{
		STATIC_NAME_IMPL(L"Trajectory206_C")
	}
	static class ATrajectory206_C* GetDefaultObj()
	{
		return GetDefaultObjImpl<ATrajectory206_C>();
	}
};
DUMPER7_ASSERTS_ATrajectory206_C;

SDK_NAMESPACE_END
