#pragma once

/*
* SDK generated by Dumper-7
*
* https://github.com/Encryqed/Dumper-7
*/

// Package: Trajectory205

#include "Basic.hpp"

#include "BP_BulletTrajectoryBase_classes.hpp"


SDK_NAMESPACE_START

// BlueprintGeneratedClass Trajectory205.Trajectory205_C
// 0x0000 (0x0330 - 0x0330)
class Trajectory205::ATrajectory205_C final : public ABP_BulletTrajectoryBase_C
{
public:
	static class UClass* StaticClass()
	{
		BP_STATIC_CLASS_IMPL_FULLNAME("BlueprintGeneratedClass Trajectory205.Trajectory205_C")
	}
	static const class FName& StaticName()
	{
		STATIC_NAME_IMPL(L"Trajectory205_C")
	}
	static class Trajectory205::ATrajectory205_C* GetDefaultObj()
	{
		return GetDefaultObjImpl<Trajectory205::ATrajectory205_C>();
	}
};
DUMPER7_ASSERTS_Trajectory205__ATrajectory205_C;

SDK_NAMESPACE_END
