#pragma once

/*
* SDK generated by Dumper-7
*
* https://github.com/Encryqed/Dumper-7
*/

// Package: TriggerAddEffects_0

#include "Basic.hpp"

#include "PMGame_classes.hpp"


SDK_NAMESPACE_START

// BlueprintGeneratedClass TriggerAddEffects.TriggerAddEffects_C
// 0x0000 (0x0268 - 0x0268)
class TriggerAddEffects_0::UTriggerAddEffects_C final : public UCyGATriggerAddEffects
{
public:
	static class UClass* StaticClass()
	{
		BP_STATIC_CLASS_IMPL_FULLNAME("BlueprintGeneratedClass TriggerAddEffects.TriggerAddEffects_C")
	}
	static const class FName& StaticName()
	{
		STATIC_NAME_IMPL(L"TriggerAddEffects_C")
	}
	static class TriggerAddEffects_0::UTriggerAddEffects_C* GetDefaultObj()
	{
		return GetDefaultObjImpl<TriggerAddEffects_0::UTriggerAddEffects_C>();
	}
};
DUMPER7_ASSERTS_TriggerAddEffects_0__UTriggerAddEffects_C;

SDK_NAMESPACE_END
