#pragma once

/*
* SDK generated by Dumper-7
*
* https://github.com/Encryqed/Dumper-7
*/

// Package: Trigger_AddQPoints

#include "Basic.hpp"

#include "PMGame_classes.hpp"


SDK_NAMESPACE_START

// BlueprintGeneratedClass Trigger_AddQPoints.Trigger_AddQPoints_C
// 0x0000 (0x0268 - 0x0268)
class UTrigger_AddQPoints_C final : public UCyGATriggerAddEffects
{
public:
	static class UClass* StaticClass()
	{
		BP_STATIC_CLASS_IMPL("Trigger_AddQPoints_C")
	}
	static const class FName& StaticName()
	{
		STATIC_NAME_IMPL(L"Trigger_AddQPoints_C")
	}
	static class UTrigger_AddQPoints_C* GetDefaultObj()
	{
		return GetDefaultObjImpl<UTrigger_AddQPoints_C>();
	}
};
DUMPER7_ASSERTS_UTrigger_AddQPoints_C;

SDK_NAMESPACE_END
