#pragma once

/*
* SDK generated by Dumper-7
*
* https://github.com/Encryqed/Dumper-7
*/

// Package: WBP_SelectRoleBombPassRuleTipPanel

#include "Basic.hpp"

#include "PMGame_classes.hpp"


SDK_NAMESPACE_START

// WidgetBlueprintGeneratedClass WBP_SelectRoleBombPassRuleTipPanel.WBP_SelectRoleBombPassRuleTipPanel_C
// 0x0000 (0x05C8 - 0x05C8)
class UWBP_SelectRoleBombPassRuleTipPanel_C final : public UPMBaseUserWidget
{
public:
	static class UClass* StaticClass()
	{
		BP_STATIC_CLASS_IMPL("WBP_SelectRoleBombPassRuleTipPanel_C")
	}
	static const class FName& StaticName()
	{
		STATIC_NAME_IMPL(L"WBP_SelectRoleBombPassRuleTipPanel_C")
	}
	static class UWBP_SelectRoleBombPassRuleTipPanel_C* GetDefaultObj()
	{
		return GetDefaultObjImpl<UWBP_SelectRoleBombPassRuleTipPanel_C>();
	}
};
DUMPER7_ASSERTS_UWBP_SelectRoleBombPassRuleTipPanel_C;

SDK_NAMESPACE_END
