#pragma once

/*
* SDK generated by Dumper-7
*
* https://github.com/Encryqed/Dumper-7
*/

// Package: WBP_PracticeGrenadeSignage5

#include "Basic.hpp"

#include "PMGame_classes.hpp"


SDK_NAMESPACE_START

// WidgetBlueprintGeneratedClass WBP_PracticeGrenadeSignage5.WBP_PracticeGrenadeSignage5_C
// 0x0008 (0x08E0 - 0x08D8)
class UWBP_PracticeGrenadeSignage5_C final : public UPMUserWidget
{
public:
	class UWBP_PracticeGrenadeSignageBase_C*      WBP_PracticeGrenadeSignageBase;                    // 0x08D8(0x0008)(BlueprintVisible, ExportObject, ZeroConstructor, InstancedReference, IsPlainOldData, RepSkip, NoDestructor, PersistentInstance, HasGetValueTypeHash)

public:
	static class UClass* StaticClass()
	{
		BP_STATIC_CLASS_IMPL("WBP_PracticeGrenadeSignage5_C")
	}
	static const class FName& StaticName()
	{
		STATIC_NAME_IMPL(L"WBP_PracticeGrenadeSignage5_C")
	}
	static class UWBP_PracticeGrenadeSignage5_C* GetDefaultObj()
	{
		return GetDefaultObjImpl<UWBP_PracticeGrenadeSignage5_C>();
	}
};
DUMPER7_ASSERTS_UWBP_PracticeGrenadeSignage5_C;

SDK_NAMESPACE_END
