#pragma once

/*
* SDK generated by Dumper-7
*
* https://github.com/Encryqed/Dumper-7
*/

// Package: WBP_SelectRoleWaterPoloRuleTipPanel

#include "Basic.hpp"

#include "PMGame_classes.hpp"


SDK_NAMESPACE_START

// WidgetBlueprintGeneratedClass WBP_SelectRoleWaterPoloRuleTipPanel.WBP_SelectRoleWaterPoloRuleTipPanel_C
// 0x0000 (0x05C8 - 0x05C8)
class UWBP_SelectRoleWaterPoloRuleTipPanel_C final : public UPMBaseUserWidget
{
public:
	static class UClass* StaticClass()
	{
		BP_STATIC_CLASS_IMPL("WBP_SelectRoleWaterPoloRuleTipPanel_C")
	}
	static const class FName& StaticName()
	{
		STATIC_NAME_IMPL(L"WBP_SelectRoleWaterPoloRuleTipPanel_C")
	}
	static class UWBP_SelectRoleWaterPoloRuleTipPanel_C* GetDefaultObj()
	{
		return GetDefaultObjImpl<UWBP_SelectRoleWaterPoloRuleTipPanel_C>();
	}
};
DUMPER7_ASSERTS_UWBP_SelectRoleWaterPoloRuleTipPanel_C;

SDK_NAMESPACE_END
