#pragma once

/*
* SDK generated by Dumper-7
*
* https://github.com/Encryqed/Dumper-7
*/

// Package: WBP_FastMessagePanel

#include "Basic.hpp"

#include "Engine_structs.hpp"
#include "PMGame_classes.hpp"


SDK_NAMESPACE_START

// WidgetBlueprintGeneratedClass WBP_FastMessagePanel.WBP_FastMessagePanel_C
// 0x0040 (0x0608 - 0x05C8)
class UWBP_FastMessagePanel_C final : public UPMBaseUserWidget
{
public:
	struct FPointerToUberGraphFrame               UberGraphFrame;                                    // 0x05C8(0x0008)(ZeroConstructor, Transient, DuplicateTransient)
	class UWBP_FastMessageItem_C*                 FastMsgItem_1;                                     // 0x05D0(0x0008)(BlueprintVisible, ExportObject, ZeroConstructor, InstancedReference, IsPlainOldData, RepSkip, NoDestructor, PersistentInstance, HasGetValueTypeHash)
	class UWBP_FastMessageItem_C*                 FastMsgItem_2;                                     // 0x05D8(0x0008)(BlueprintVisible, ExportObject, ZeroConstructor, InstancedReference, IsPlainOldData, RepSkip, NoDestructor, PersistentInstance, HasGetValueTypeHash)
	class UWBP_FastMessageItem_C*                 FastMsgItem_3;                                     // 0x05E0(0x0008)(BlueprintVisible, ExportObject, ZeroConstructor, InstancedReference, IsPlainOldData, RepSkip, NoDestructor, PersistentInstance, HasGetValueTypeHash)
	class UWBP_FastMessageItem_C*                 FastMsgItem_4;                                     // 0x05E8(0x0008)(BlueprintVisible, ExportObject, ZeroConstructor, InstancedReference, IsPlainOldData, RepSkip, NoDestructor, PersistentInstance, HasGetValueTypeHash)
	class UWBP_FastMessageItem_C*                 FastMsgItem_5;                                     // 0x05F0(0x0008)(BlueprintVisible, ExportObject, ZeroConstructor, InstancedReference, IsPlainOldData, RepSkip, NoDestructor, PersistentInstance, HasGetValueTypeHash)
	class UWBP_FastMessageItem_C*                 FastMsgItem_6;                                     // 0x05F8(0x0008)(BlueprintVisible, ExportObject, ZeroConstructor, InstancedReference, IsPlainOldData, RepSkip, NoDestructor, PersistentInstance, HasGetValueTypeHash)
	class UVerticalBox*                           VB_FastMsg;                                        // 0x0600(0x0008)(BlueprintVisible, ExportObject, ZeroConstructor, InstancedReference, IsPlainOldData, RepSkip, NoDestructor, PersistentInstance, HasGetValueTypeHash)

public:
	void ExecuteUbergraph_WBP_FastMessagePanel(int32 EntryPoint);
	void OnListItemObjectSet(class UObject* ListItemObject);
	void BP_OnItemSelectionChanged(bool bIsSelected);
	void BP_OnItemExpansionChanged(bool bIsExpanded);
	void BP_OnEntryReleased();

public:
	static class UClass* StaticClass()
	{
		BP_STATIC_CLASS_IMPL("WBP_FastMessagePanel_C")
	}
	static const class FName& StaticName()
	{
		STATIC_NAME_IMPL(L"WBP_FastMessagePanel_C")
	}
	static class UWBP_FastMessagePanel_C* GetDefaultObj()
	{
		return GetDefaultObjImpl<UWBP_FastMessagePanel_C>();
	}
};
DUMPER7_ASSERTS_UWBP_FastMessagePanel_C;

SDK_NAMESPACE_END
