#pragma once

/*
* SDK generated by Dumper-7
*
* https://github.com/Encryqed/Dumper-7
*/

// Package: WBP_SelectRoleChangeSkinAdvanceList

#include "Basic.hpp"

#include "PMGame_classes.hpp"


SDK_NAMESPACE_START

// WidgetBlueprintGeneratedClass WBP_SelectRoleChangeSkinAdvanceList.WBP_SelectRoleChangeSkinAdvanceList_C
// 0x0030 (0x05F8 - 0x05C8)
class UWBP_SelectRoleChangeSkinAdvanceList_C final : public UPMBaseUserWidget
{
public:
	class UButton*                                Button_AdvanceView;                                // 0x05C8(0x0008)(BlueprintVisible, ExportObject, ZeroConstructor, InstancedReference, IsPlainOldData, RepSkip, NoDestructor, PersistentInstance, HasGetValueTypeHash)
	class UButton*                                Button_BaseView;                                   // 0x05D0(0x0008)(BlueprintVisible, ExportObject, ZeroConstructor, InstancedReference, IsPlainOldData, RepSkip, NoDestructor, PersistentInstance, HasGetValueTypeHash)
	class UDynamicEntryBox*                       Dynamic_PartSkin;                                  // 0x05D8(0x0008)(BlueprintVisible, ExportObject, ZeroConstructor, InstancedReference, IsPlainOldData, RepSkip, NoDestructor, PersistentInstance, HasGetValueTypeHash)
	class UDynamicEntryBox*                       DynamicEntryBox;                                   // 0x05E0(0x0008)(BlueprintVisible, ExportObject, ZeroConstructor, InstancedReference, IsPlainOldData, RepSkip, NoDestructor, PersistentInstance, HasGetValueTypeHash)
	class UOverlay*                               Overlay_Advance;                                   // 0x05E8(0x0008)(BlueprintVisible, ExportObject, ZeroConstructor, InstancedReference, IsPlainOldData, RepSkip, NoDestructor, PersistentInstance, HasGetValueTypeHash)
	class UPMImage*                               PMImage_De;                                        // 0x05F0(0x0008)(BlueprintVisible, ExportObject, ZeroConstructor, InstancedReference, IsPlainOldData, RepSkip, NoDestructor, PersistentInstance, HasGetValueTypeHash)

public:
	static class UClass* StaticClass()
	{
		BP_STATIC_CLASS_IMPL("WBP_SelectRoleChangeSkinAdvanceList_C")
	}
	static const class FName& StaticName()
	{
		STATIC_NAME_IMPL(L"WBP_SelectRoleChangeSkinAdvanceList_C")
	}
	static class UWBP_SelectRoleChangeSkinAdvanceList_C* GetDefaultObj()
	{
		return GetDefaultObjImpl<UWBP_SelectRoleChangeSkinAdvanceList_C>();
	}
};
DUMPER7_ASSERTS_UWBP_SelectRoleChangeSkinAdvanceList_C;

SDK_NAMESPACE_END
