#pragma once

/*
* SDK generated by Dumper-7
*
* https://github.com/Encryqed/Dumper-7
*/

// Package: WBP_CustomWidgetLayoutPanel

#include "Basic.hpp"

#include "PMGame_classes.hpp"


SDK_NAMESPACE_START

// WidgetBlueprintGeneratedClass WBP_CustomWidgetLayoutPanel.WBP_CustomWidgetLayoutPanel_C
// 0x0068 (0x0630 - 0x05C8)
class UWBP_CustomWidgetLayoutPanel_C final : public UPMBaseUserWidget
{
public:
	class UCanvasPanel*                           EditArea_Click;                                    // 0x05C8(0x0008)(BlueprintVisible, ExportObject, ZeroConstructor, InstancedReference, IsPlainOldData, RepSkip, NoDestructor, PersistentInstance, HasGetValueTypeHash)
	class UImage*                                 Image_73;                                          // 0x05D0(0x0008)(BlueprintVisible, ExportObject, ZeroConstructor, InstancedReference, IsPlainOldData, RepSkip, NoDestructor, PersistentInstance, HasGetValueTypeHash)
	class UWBP_CustomWidgetOptItem_C*             WBP_CustomWidgetOptItem_PC;                        // 0x05D8(0x0008)(BlueprintVisible, ExportObject, ZeroConstructor, InstancedReference, IsPlainOldData, RepSkip, NoDestructor, PersistentInstance, HasGetValueTypeHash)
	TSoftClassPtr<class UClass>                   WidgetClassRef;                                    // 0x05E0(0x0028)(Edit, BlueprintVisible, HasGetValueTypeHash)
	TSoftClassPtr<class UClass>                   OptItemRef;                                        // 0x0608(0x0028)(Edit, BlueprintVisible, DisableEditOnInstance, HasGetValueTypeHash)

public:
	static class UClass* StaticClass()
	{
		BP_STATIC_CLASS_IMPL("WBP_CustomWidgetLayoutPanel_C")
	}
	static const class FName& StaticName()
	{
		STATIC_NAME_IMPL(L"WBP_CustomWidgetLayoutPanel_C")
	}
	static class UWBP_CustomWidgetLayoutPanel_C* GetDefaultObj()
	{
		return GetDefaultObjImpl<UWBP_CustomWidgetLayoutPanel_C>();
	}
};
DUMPER7_ASSERTS_UWBP_CustomWidgetLayoutPanel_C;

SDK_NAMESPACE_END
