#pragma once

/*
* SDK generated by Dumper-7
*
* https://github.com/Encryqed/Dumper-7
*/

// Package: WBP_PracticeChallengeResultItem

#include "Basic.hpp"

#include "PMGame_classes.hpp"


SDK_NAMESPACE_START

// WidgetBlueprintGeneratedClass WBP_PracticeChallengeResultItem.WBP_PracticeChallengeResultItem_C
// 0x0050 (0x0618 - 0x05C8)
class UWBP_PracticeChallengeResultItem_C final : public UPMBaseUserWidget
{
public:
	class UImage*                                 Image_Head;                                        // 0x05C8(0x0008)(BlueprintVisible, ExportObject, ZeroConstructor, InstancedReference, IsPlainOldData, RepSkip, NoDestructor, PersistentInstance, HasGetValueTypeHash)
	class UTextBlock*                             Text_CostTime;                                     // 0x05D0(0x0008)(BlueprintVisible, ExportObject, ZeroConstructor, InstancedReference, IsPlainOldData, RepSkip, NoDestructor, PersistentInstance, HasGetValueTypeHash)
	class UTextBlock*                             Text_Name;                                         // 0x05D8(0x0008)(BlueprintVisible, ExportObject, ZeroConstructor, InstancedReference, IsPlainOldData, RepSkip, NoDestructor, PersistentInstance, HasGetValueTypeHash)
	class UTextBlock*                             Text_Score;                                        // 0x05E0(0x0008)(BlueprintVisible, ExportObject, ZeroConstructor, InstancedReference, IsPlainOldData, RepSkip, NoDestructor, PersistentInstance, HasGetValueTypeHash)
	class FText                                   ScoreFormat;                                       // 0x05E8(0x0018)(Edit, BlueprintVisible)
	class FText                                   CostTimeFormat;                                    // 0x0600(0x0018)(Edit, BlueprintVisible)

public:
	static class UClass* StaticClass()
	{
		BP_STATIC_CLASS_IMPL("WBP_PracticeChallengeResultItem_C")
	}
	static const class FName& StaticName()
	{
		STATIC_NAME_IMPL(L"WBP_PracticeChallengeResultItem_C")
	}
	static class UWBP_PracticeChallengeResultItem_C* GetDefaultObj()
	{
		return GetDefaultObjImpl<UWBP_PracticeChallengeResultItem_C>();
	}
};
DUMPER7_ASSERTS_UWBP_PracticeChallengeResultItem_C;

SDK_NAMESPACE_END
