#pragma once

/*
* SDK generated by Dumper-7
*
* https://github.com/Encryqed/Dumper-7
*/

// Package: WBP_BannerChange

#include "Basic.hpp"

#include "UMG_classes.hpp"


SDK_NAMESPACE_START

// WidgetBlueprintGeneratedClass WBP_BannerChange.WBP_BannerChange_C
// 0x0008 (0x0268 - 0x0260)
class UWBP_BannerChange_C final : public UUserWidget
{
public:
	class UDynamicEntryBox*                       DynamicEntryBox;                                   // 0x0260(0x0008)(BlueprintVisible, ExportObject, ZeroConstructor, InstancedReference, IsPlainOldData, RepSkip, NoDestructor, PersistentInstance, HasGetValueTypeHash)

public:
	static class UClass* StaticClass()
	{
		BP_STATIC_CLASS_IMPL("WBP_BannerChange_C")
	}
	static const class FName& StaticName()
	{
		STATIC_NAME_IMPL(L"WBP_BannerChange_C")
	}
	static class UWBP_BannerChange_C* GetDefaultObj()
	{
		return GetDefaultObjImpl<UWBP_BannerChange_C>();
	}
};
DUMPER7_ASSERTS_UWBP_BannerChange_C;

SDK_NAMESPACE_END
