#pragma once

/*
* SDK generated by Dumper-7
*
* https://github.com/Encryqed/Dumper-7
*/

// Package: WBP_Abilities

#include "Basic.hpp"

#include "PMGame_classes.hpp"


SDK_NAMESPACE_START

// WidgetBlueprintGeneratedClass WBP_Abilities.WBP_Abilities_C
// 0x0000 (0x1238 - 0x1238)
class UWBP_Abilities_C final : public UPMUWGameplayAbility
{
public:
	static class UClass* StaticClass()
	{
		BP_STATIC_CLASS_IMPL("WBP_Abilities_C")
	}
	static const class FName& StaticName()
	{
		STATIC_NAME_IMPL(L"WBP_Abilities_C")
	}
	static class UWBP_Abilities_C* GetDefaultObj()
	{
		return GetDefaultObjImpl<UWBP_Abilities_C>();
	}
};
DUMPER7_ASSERTS_UWBP_Abilities_C;

SDK_NAMESPACE_END
