#pragma once

/*
* SDK generated by Dumper-7
*
* https://github.com/Encryqed/Dumper-7
*/

// Package: WBP_RoomModeSelectPage

#include "Basic.hpp"

#include "WBP_RoomModeSelectPage_classes.hpp"
#include "WBP_RoomModeSelectPage_parameters.hpp"


SDK_NAMESPACE_START

// Function WBP_RoomModeSelectPage.WBP_RoomModeSelectPage_C.On_Ground_MouseButtonDown_0
// (Public, HasOutParams, BlueprintCallable, BlueprintEvent)
// Parameters:
// const struct FGeometry&                 MyGeometry                                             (BlueprintVisible, BlueprintReadOnly, Parm, IsPlainOldData, NoDestructor)
// const struct FPointerEvent&             MouseEvent                                             (ConstParm, BlueprintVisible, BlueprintReadOnly, Parm, OutParm, ReferenceParm)

void UWBP_RoomModeSelectPage_C::On_Ground_MouseButtonDown_0(const struct FGeometry& MyGeometry, const struct FPointerEvent& MouseEvent)
{
	static class UFunction* Func = nullptr;

	if (Func == nullptr)
		Func = Class->GetFunction("WBP_RoomModeSelectPage_C", "On_Ground_MouseButtonDown_0");

	Params::WBP_RoomModeSelectPage_C_On_Ground_MouseButtonDown_0 Parms{};

	Parms.MyGeometry = std::move(MyGeometry);
	Parms.MouseEvent = std::move(MouseEvent);

	UObject::ProcessEvent(Func, &Parms);
}


SDK_NAMESPACE_END
