#pragma once

/*
* SDK generated by Dumper-7
*
* https://github.com/Encryqed/Dumper-7
*/

// Package: WBP_ChatFriendPage

#include "Basic.hpp"

#include "WBP_ChatFriendPage_classes.hpp"
#include "WBP_ChatFriendPage_parameters.hpp"


SDK_NAMESPACE_START

// Function WBP_ChatFriendPage.WBP_ChatFriendPage_C.ExecuteUbergraph_WBP_ChatFriendPage
// (Final, UbergraphFunction)
// Parameters:
// int32                                   EntryPoint                                             (BlueprintVisible, BlueprintReadOnly, Parm, ZeroConstructor, IsPlainOldData, NoDestructor, HasGetValueTypeHash)

void UWBP_ChatFriendPage_C::ExecuteUbergraph_WBP_ChatFriendPage(int32 EntryPoint)
{
	static class UFunction* Func = nullptr;

	if (Func == nullptr)
		Func = Class->GetFunction("WBP_ChatFriendPage_C", "ExecuteUbergraph_WBP_ChatFriendPage");

	Params::WBP_ChatFriendPage_C_ExecuteUbergraph_WBP_ChatFriendPage Parms{};

	Parms.EntryPoint = EntryPoint;

	UObject::ProcessEvent(Func, &Parms);
}


// Function WBP_ChatFriendPage.WBP_ChatFriendPage_C.Construct
// (BlueprintCosmetic, Native, Event, Public, BlueprintEvent)

void UWBP_ChatFriendPage_C::Construct()
{
	static class UFunction* Func = nullptr;

	if (Func == nullptr)
		Func = Class->GetFunction("WBP_ChatFriendPage_C", "Construct");

	auto Flgs = Func->FunctionFlags;
	Func->FunctionFlags |= 0x400;

	UObject::ProcessEvent(Func, nullptr);

	Func->FunctionFlags = Flgs;
}


SDK_NAMESPACE_END
