#pragma once

/*
* SDK generated by Dumper-7
*
* https://github.com/Encryqed/Dumper-7
*/

// Package: WBP_RedDot_CustomA_Panel

#include "Basic.hpp"

#include "WBP_RedDot_CustomA_Panel_classes.hpp"
#include "WBP_RedDot_CustomA_Panel_parameters.hpp"


SDK_NAMESPACE_START

// Function WBP_RedDot_CustomA_Panel.WBP_RedDot_CustomA_Panel_C.ExecuteUbergraph_WBP_RedDot_CustomA_Panel
// (Final, UbergraphFunction)
// Parameters:
// int32                                   EntryPoint                                             (BlueprintVisible, BlueprintReadOnly, Parm, ZeroConstructor, IsPlainOldData, NoDestructor, HasGetValueTypeHash)

void UWBP_RedDot_CustomA_Panel_C::ExecuteUbergraph_WBP_RedDot_CustomA_Panel(int32 EntryPoint)
{
	static class UFunction* Func = nullptr;

	if (Func == nullptr)
		Func = Class->GetFunction("WBP_RedDot_CustomA_Panel_C", "ExecuteUbergraph_WBP_RedDot_CustomA_Panel");

	Params::WBP_RedDot_CustomA_Panel_C_ExecuteUbergraph_WBP_RedDot_CustomA_Panel Parms{};

	Parms.EntryPoint = EntryPoint;

	UObject::ProcessEvent(Func, &Parms);
}


// Function WBP_RedDot_CustomA_Panel.WBP_RedDot_CustomA_Panel_C.Construct
// (BlueprintCosmetic, Native, Event, Public, BlueprintEvent)

void UWBP_RedDot_CustomA_Panel_C::Construct()
{
	static class UFunction* Func = nullptr;

	if (Func == nullptr)
		Func = Class->GetFunction("WBP_RedDot_CustomA_Panel_C", "Construct");

	auto Flgs = Func->FunctionFlags;
	Func->FunctionFlags |= 0x400;

	UObject::ProcessEvent(Func, nullptr);

	Func->FunctionFlags = Flgs;
}


SDK_NAMESPACE_END
