#pragma once

/*
* SDK generated by Dumper-7
*
* https://github.com/Encryqed/Dumper-7
*/

// Package: WBP_MsgWarningPage

#include "Basic.hpp"

#include "PMGame_classes.hpp"


SDK_NAMESPACE_START

// WidgetBlueprintGeneratedClass WBP_MsgWarningPage.WBP_MsgWarningPage_C
// 0x0008 (0x05F0 - 0x05E8)
class UWBP_MsgWarningPage_C final : public UPMWarningMsgWidget
{
public:
	class UImage*                                 Image_78;                                          // 0x05E8(0x0008)(BlueprintVisible, ExportObject, ZeroConstructor, InstancedReference, IsPlainOldData, RepSkip, NoDestructor, PersistentInstance, HasGetValueTypeHash)

public:
	static class UClass* StaticClass()
	{
		BP_STATIC_CLASS_IMPL("WBP_MsgWarningPage_C")
	}
	static const class FName& StaticName()
	{
		STATIC_NAME_IMPL(L"WBP_MsgWarningPage_C")
	}
	static class UWBP_MsgWarningPage_C* GetDefaultObj()
	{
		return GetDefaultObjImpl<UWBP_MsgWarningPage_C>();
	}
};
DUMPER7_ASSERTS_UWBP_MsgWarningPage_C;

SDK_NAMESPACE_END
