#pragma once

/*
* SDK generated by Dumper-7
*
* https://github.com/Encryqed/Dumper-7
*/

// Package: WBP_GrowthRoleAttributes_Retrofit

#include "Basic.hpp"

#include "PMGame_classes.hpp"


SDK_NAMESPACE_START

// WidgetBlueprintGeneratedClass WBP_GrowthRoleAttributes_Retrofit.WBP_GrowthRoleAttributes_Retrofit_C
// 0x0020 (0x05E8 - 0x05C8)
class UWBP_GrowthRoleAttributes_Retrofit_C final : public UPMBaseUserWidget
{
public:
	class UPMImage*                               PMImage_Camp;                                      // 0x05C8(0x0008)(BlueprintVisible, ExportObject, ZeroConstructor, InstancedReference, IsPlainOldData, RepSkip, NoDestructor, PersistentInstance, HasGetValueTypeHash)
	class UPMImage*                               PMImage_RoleItem;                                  // 0x05D0(0x0008)(BlueprintVisible, ExportObject, ZeroConstructor, InstancedReference, IsPlainOldData, RepSkip, NoDestructor, PersistentInstance, HasGetValueTypeHash)
	class UPMTextBlock*                           Text_CampName;                                     // 0x05D8(0x0008)(BlueprintVisible, ExportObject, ZeroConstructor, InstancedReference, IsPlainOldData, RepSkip, NoDestructor, PersistentInstance, HasGetValueTypeHash)
	class UPMTextBlock*                           Text_RoleName;                                     // 0x05E0(0x0008)(BlueprintVisible, ExportObject, ZeroConstructor, InstancedReference, IsPlainOldData, RepSkip, NoDestructor, PersistentInstance, HasGetValueTypeHash)

public:
	static class UClass* StaticClass()
	{
		BP_STATIC_CLASS_IMPL("WBP_GrowthRoleAttributes_Retrofit_C")
	}
	static const class FName& StaticName()
	{
		STATIC_NAME_IMPL(L"WBP_GrowthRoleAttributes_Retrofit_C")
	}
	static class UWBP_GrowthRoleAttributes_Retrofit_C* GetDefaultObj()
	{
		return GetDefaultObjImpl<UWBP_GrowthRoleAttributes_Retrofit_C>();
	}
};
DUMPER7_ASSERTS_UWBP_GrowthRoleAttributes_Retrofit_C;

SDK_NAMESPACE_END
