#pragma once

/*
* SDK generated by Dumper-7
*
* https://github.com/Encryqed/Dumper-7
*/

// Package: WBP_ChatText_Pre

#include "Basic.hpp"

#include "WBP_ChatText_Pre_classes.hpp"
#include "WBP_ChatText_Pre_parameters.hpp"


SDK_NAMESPACE_START

// Function WBP_ChatText_Pre.WBP_ChatText_Pre_C.ExecuteUbergraph_WBP_ChatText_Pre
// (Final, UbergraphFunction)
// Parameters:
// int32                                   EntryPoint                                             (BlueprintVisible, BlueprintReadOnly, Parm, ZeroConstructor, IsPlainOldData, NoDestructor, HasGetValueTypeHash)

void UWBP_ChatText_Pre_C::ExecuteUbergraph_WBP_ChatText_Pre(int32 EntryPoint)
{
	static class UFunction* Func = nullptr;

	if (Func == nullptr)
		Func = Class->GetFunction("WBP_ChatText_Pre_C", "ExecuteUbergraph_WBP_ChatText_Pre");

	Params::WBP_ChatText_Pre_C_ExecuteUbergraph_WBP_ChatText_Pre Parms{};

	Parms.EntryPoint = EntryPoint;

	UObject::ProcessEvent(Func, &Parms);
}


// Function WBP_ChatText_Pre.WBP_ChatText_Pre_C.OnListItemObjectSet
// (Native, Event, Protected, BlueprintEvent)
// Parameters:
// class UObject*                          ListItemObject                                         (BlueprintVisible, BlueprintReadOnly, Parm, ZeroConstructor, IsPlainOldData, NoDestructor, HasGetValueTypeHash)

void UWBP_ChatText_Pre_C::OnListItemObjectSet(class UObject* ListItemObject)
{
	static class UFunction* Func = nullptr;

	if (Func == nullptr)
		Func = Class->GetFunction("WBP_ChatText_Pre_C", "OnListItemObjectSet");

	Params::WBP_ChatText_Pre_C_OnListItemObjectSet Parms{};

	Parms.ListItemObject = ListItemObject;

	auto Flgs = Func->FunctionFlags;
	Func->FunctionFlags |= 0x400;

	UObject::ProcessEvent(Func, &Parms);

	Func->FunctionFlags = Flgs;
}


// Function WBP_ChatText_Pre.WBP_ChatText_Pre_C.BP_OnItemSelectionChanged
// (Native, Event, Protected, BlueprintEvent)
// Parameters:
// bool                                    bIsSelected                                            (BlueprintVisible, BlueprintReadOnly, Parm, ZeroConstructor, IsPlainOldData, NoDestructor)

void UWBP_ChatText_Pre_C::BP_OnItemSelectionChanged(bool bIsSelected)
{
	static class UFunction* Func = nullptr;

	if (Func == nullptr)
		Func = Class->GetFunction("WBP_ChatText_Pre_C", "BP_OnItemSelectionChanged");

	Params::WBP_ChatText_Pre_C_BP_OnItemSelectionChanged Parms{};

	Parms.bIsSelected = bIsSelected;

	auto Flgs = Func->FunctionFlags;
	Func->FunctionFlags |= 0x400;

	UObject::ProcessEvent(Func, &Parms);

	Func->FunctionFlags = Flgs;
}


// Function WBP_ChatText_Pre.WBP_ChatText_Pre_C.BP_OnItemExpansionChanged
// (Event, Protected, BlueprintEvent)
// Parameters:
// bool                                    bIsExpanded                                            (BlueprintVisible, BlueprintReadOnly, Parm, ZeroConstructor, IsPlainOldData, NoDestructor)

void UWBP_ChatText_Pre_C::BP_OnItemExpansionChanged(bool bIsExpanded)
{
	static class UFunction* Func = nullptr;

	if (Func == nullptr)
		Func = Class->GetFunction("WBP_ChatText_Pre_C", "BP_OnItemExpansionChanged");

	Params::WBP_ChatText_Pre_C_BP_OnItemExpansionChanged Parms{};

	Parms.bIsExpanded = bIsExpanded;

	UObject::ProcessEvent(Func, &Parms);
}


// Function WBP_ChatText_Pre.WBP_ChatText_Pre_C.BP_OnEntryReleased
// (Event, Protected, BlueprintEvent)

void UWBP_ChatText_Pre_C::BP_OnEntryReleased()
{
	static class UFunction* Func = nullptr;

	if (Func == nullptr)
		Func = Class->GetFunction("WBP_ChatText_Pre_C", "BP_OnEntryReleased");

	UObject::ProcessEvent(Func, nullptr);
}


SDK_NAMESPACE_END
