#pragma once

/*
* SDK generated by Dumper-7
*
* https://github.com/Encryqed/Dumper-7
*/

// Package: WBP_BuffItem

#include "Basic.hpp"

#include "WBP_BuffItem_classes.hpp"
#include "WBP_BuffItem_parameters.hpp"


SDK_NAMESPACE_START

// Function WBP_BuffItem.WBP_BuffItem_C.ExecuteUbergraph_WBP_BuffItem
// (Final, UbergraphFunction)
// Parameters:
// int32                                   EntryPoint                                             (BlueprintVisible, BlueprintReadOnly, Parm, ZeroConstructor, IsPlainOldData, NoDestructor, HasGetValueTypeHash)

void UWBP_BuffItem_C::ExecuteUbergraph_WBP_BuffItem(int32 EntryPoint)
{
	static class UFunction* Func = nullptr;

	if (Func == nullptr)
		Func = Class->GetFunction("WBP_BuffItem_C", "ExecuteUbergraph_WBP_BuffItem");

	Params::WBP_BuffItem_C_ExecuteUbergraph_WBP_BuffItem Parms{};

	Parms.EntryPoint = EntryPoint;

	UObject::ProcessEvent(Func, &Parms);
}


// Function WBP_BuffItem.WBP_BuffItem_C.PreConstruct
// (BlueprintCosmetic, Event, Public, BlueprintEvent)
// Parameters:
// bool                                    IsDesignTime                                           (BlueprintVisible, BlueprintReadOnly, Parm, ZeroConstructor, IsPlainOldData, NoDestructor)

void UWBP_BuffItem_C::PreConstruct(bool IsDesignTime)
{
	static class UFunction* Func = nullptr;

	if (Func == nullptr)
		Func = Class->GetFunction("WBP_BuffItem_C", "PreConstruct");

	Params::WBP_BuffItem_C_PreConstruct Parms{};

	Parms.IsDesignTime = IsDesignTime;

	UObject::ProcessEvent(Func, &Parms);
}


SDK_NAMESPACE_END
