#pragma once

/*
* SDK generated by Dumper-7
*
* https://github.com/Encryqed/Dumper-7
*/

// Package: WBP_GameVoiceChatPanel

#include "Basic.hpp"

#include "PMGame_classes.hpp"


SDK_NAMESPACE_START

// WidgetBlueprintGeneratedClass WBP_GameVoiceChatPanel.WBP_GameVoiceChatPanel_C
// 0x0008 (0x0640 - 0x0638)
class UWBP_GameVoiceChatPanel_C final : public UPMUWVoiceChatPanelPC
{
public:
	class UImage*                                 Image_70;                                          // 0x0638(0x0008)(BlueprintVisible, ExportObject, ZeroConstructor, InstancedReference, IsPlainOldData, RepSkip, NoDestructor, PersistentInstance, HasGetValueTypeHash)

public:
	static class UClass* StaticClass()
	{
		BP_STATIC_CLASS_IMPL("WBP_GameVoiceChatPanel_C")
	}
	static const class FName& StaticName()
	{
		STATIC_NAME_IMPL(L"WBP_GameVoiceChatPanel_C")
	}
	static class UWBP_GameVoiceChatPanel_C* GetDefaultObj()
	{
		return GetDefaultObjImpl<UWBP_GameVoiceChatPanel_C>();
	}
};
DUMPER7_ASSERTS_UWBP_GameVoiceChatPanel_C;

SDK_NAMESPACE_END
