#pragma once

/*
* SDK generated by Dumper-7
*
* https://github.com/Encryqed/Dumper-7
*/

// Package: WBP_DynamicIcon

#include "Basic.hpp"

#include "PMGame_classes.hpp"


SDK_NAMESPACE_START

// WidgetBlueprintGeneratedClass WBP_DynamicIcon.WBP_DynamicIcon_C
// 0x0018 (0x05E0 - 0x05C8)
class UWBP_DynamicIcon_C final : public UPMBaseUserWidget
{
public:
	class UBorder*                                Border_DynamicIconSlot;                            // 0x05C8(0x0008)(BlueprintVisible, ExportObject, ZeroConstructor, InstancedReference, IsPlainOldData, RepSkip, NoDestructor, PersistentInstance, HasGetValueTypeHash)
	class UImage*                                 Image_Item;                                        // 0x05D0(0x0008)(BlueprintVisible, ExportObject, ZeroConstructor, InstancedReference, IsPlainOldData, RepSkip, NoDestructor, PersistentInstance, HasGetValueTypeHash)
	class UWidgetSwitcher*                        WidgetSwitcher_IconType;                           // 0x05D8(0x0008)(BlueprintVisible, ExportObject, ZeroConstructor, InstancedReference, IsPlainOldData, RepSkip, NoDestructor, PersistentInstance, HasGetValueTypeHash)

public:
	static class UClass* StaticClass()
	{
		BP_STATIC_CLASS_IMPL("WBP_DynamicIcon_C")
	}
	static const class FName& StaticName()
	{
		STATIC_NAME_IMPL(L"WBP_DynamicIcon_C")
	}
	static class UWBP_DynamicIcon_C* GetDefaultObj()
	{
		return GetDefaultObjImpl<UWBP_DynamicIcon_C>();
	}
};
DUMPER7_ASSERTS_UWBP_DynamicIcon_C;

SDK_NAMESPACE_END
