#pragma once

/*
* SDK generated by Dumper-7
*
* https://github.com/Encryqed/Dumper-7
*/

// Package: WBP_ChatItemBase

#include "Basic.hpp"

#include "Engine_structs.hpp"
#include "PMGame_classes.hpp"


SDK_NAMESPACE_START

// WidgetBlueprintGeneratedClass WBP_ChatItemBase.WBP_ChatItemBase_C
// 0x0008 (0x0630 - 0x0628)
class UWBP_ChatItemBase_C : public UPMBaseWidgetItem
{
public:
	struct FPointerToUberGraphFrame               UberGraphFrame;                                    // 0x0628(0x0008)(ZeroConstructor, Transient, DuplicateTransient)

public:
	void ExecuteUbergraph_WBP_ChatItemBase(int32 EntryPoint);
	void OnListItemObjectSet(class UObject* ListItemObject);
	void BP_OnItemSelectionChanged(bool bIsSelected);
	void BP_OnItemExpansionChanged(bool bIsExpanded);
	void BP_OnEntryReleased();

public:
	static class UClass* StaticClass()
	{
		BP_STATIC_CLASS_IMPL("WBP_ChatItemBase_C")
	}
	static const class FName& StaticName()
	{
		STATIC_NAME_IMPL(L"WBP_ChatItemBase_C")
	}
	static class UWBP_ChatItemBase_C* GetDefaultObj()
	{
		return GetDefaultObjImpl<UWBP_ChatItemBase_C>();
	}
};
DUMPER7_ASSERTS_UWBP_ChatItemBase_C;

SDK_NAMESPACE_END
