#pragma once

/*
* SDK generated by Dumper-7
*
* https://github.com/Encryqed/Dumper-7
*/

// Package: WBP_GrowthWakeItem_Retrofit

#include "Basic.hpp"

#include "WBP_GrowthWakeItem_Retrofit_classes.hpp"
#include "WBP_GrowthWakeItem_Retrofit_parameters.hpp"


SDK_NAMESPACE_START

// Function WBP_GrowthWakeItem_Retrofit.WBP_GrowthWakeItem_Retrofit_C.ExecuteUbergraph_WBP_GrowthWakeItem_Retrofit
// (Final, UbergraphFunction)
// Parameters:
// int32                                   EntryPoint                                             (BlueprintVisible, BlueprintReadOnly, Parm, ZeroConstructor, IsPlainOldData, NoDestructor, HasGetValueTypeHash)

void UWBP_GrowthWakeItem_Retrofit_C::ExecuteUbergraph_WBP_GrowthWakeItem_Retrofit(int32 EntryPoint)
{
	static class UFunction* Func = nullptr;

	if (Func == nullptr)
		Func = Class->GetFunction("WBP_GrowthWakeItem_Retrofit_C", "ExecuteUbergraph_WBP_GrowthWakeItem_Retrofit");

	Params::WBP_GrowthWakeItem_Retrofit_C_ExecuteUbergraph_WBP_GrowthWakeItem_Retrofit Parms{};

	Parms.EntryPoint = EntryPoint;

	UObject::ProcessEvent(Func, &Parms);
}


SDK_NAMESPACE_END
