#pragma once

/*
* SDK generated by Dumper-7
*
* https://github.com/Encryqed/Dumper-7
*/

// Package: WBP_AmmoProgressBarPanel

#include "Basic.hpp"

#include "PMGame_classes.hpp"


SDK_NAMESPACE_START

// WidgetBlueprintGeneratedClass WBP_AmmoProgressBarPanel.WBP_AmmoProgressBarPanel_C
// 0x0000 (0x0A40 - 0x0A40)
class UWBP_AmmoProgressBarPanel_C final : public UPMUWAmmoProgressBarPanelPC
{
public:
	static class UClass* StaticClass()
	{
		BP_STATIC_CLASS_IMPL("WBP_AmmoProgressBarPanel_C")
	}
	static const class FName& StaticName()
	{
		STATIC_NAME_IMPL(L"WBP_AmmoProgressBarPanel_C")
	}
	static class UWBP_AmmoProgressBarPanel_C* GetDefaultObj()
	{
		return GetDefaultObjImpl<UWBP_AmmoProgressBarPanel_C>();
	}
};
DUMPER7_ASSERTS_UWBP_AmmoProgressBarPanel_C;

SDK_NAMESPACE_END
