#pragma once

/*
* SDK generated by Dumper-7
*
* https://github.com/Encryqed/Dumper-7
*/

// Package: WBP_GameVoiceChatPage

#include "Basic.hpp"

#include "WBP_GameVoiceChatPage_classes.hpp"
#include "WBP_GameVoiceChatPage_parameters.hpp"


SDK_NAMESPACE_START

// Function WBP_GameVoiceChatPage.WBP_GameVoiceChatPage_C.ExecuteUbergraph_WBP_GameVoiceChatPage
// (Final, UbergraphFunction)
// Parameters:
// int32                                   EntryPoint                                             (BlueprintVisible, BlueprintReadOnly, Parm, ZeroConstructor, IsPlainOldData, NoDestructor, HasGetValueTypeHash)

void UWBP_GameVoiceChatPage_C::ExecuteUbergraph_WBP_GameVoiceChatPage(int32 EntryPoint)
{
	static class UFunction* Func = nullptr;

	if (Func == nullptr)
		Func = Class->GetFunction("WBP_GameVoiceChatPage_C", "ExecuteUbergraph_WBP_GameVoiceChatPage");

	Params::WBP_GameVoiceChatPage_C_ExecuteUbergraph_WBP_GameVoiceChatPage Parms{};

	Parms.EntryPoint = EntryPoint;

	UObject::ProcessEvent(Func, &Parms);
}


// Function WBP_GameVoiceChatPage.WBP_GameVoiceChatPage_C.Construct
// (BlueprintCosmetic, Event, Public, BlueprintEvent)

void UWBP_GameVoiceChatPage_C::Construct()
{
	static class UFunction* Func = nullptr;

	if (Func == nullptr)
		Func = Class->GetFunction("WBP_GameVoiceChatPage_C", "Construct");

	UObject::ProcessEvent(Func, nullptr);
}


SDK_NAMESPACE_END
