#pragma once

/*
* SDK generated by Dumper-7
*
* https://github.com/Encryqed/Dumper-7
*/

// Package: WBP_BuffEntry

#include "Basic.hpp"

#include "Engine_structs.hpp"
#include "PMGame_classes.hpp"


SDK_NAMESPACE_START

// WidgetBlueprintGeneratedClass WBP_BuffEntry.WBP_BuffEntry_C
// 0x0030 (0x05F8 - 0x05C8)
class UWBP_BuffEntry_C final : public UPMBaseUserWidget
{
public:
	struct FPointerToUberGraphFrame               UberGraphFrame;                                    // 0x05C8(0x0008)(ZeroConstructor, Transient, DuplicateTransient)
	class USizeBox*                               SizeBox_Detail;                                    // 0x05D0(0x0008)(BlueprintVisible, ExportObject, ZeroConstructor, InstancedReference, IsPlainOldData, RepSkip, NoDestructor, PersistentInstance, HasGetValueTypeHash)
	class UTextBlock*                             TextBlock_Item;                                    // 0x05D8(0x0008)(BlueprintVisible, ExportObject, ZeroConstructor, InstancedReference, IsPlainOldData, RepSkip, NoDestructor, PersistentInstance, HasGetValueTypeHash)
	class UTextBlock*                             TextBlock_Rest;                                    // 0x05E0(0x0008)(BlueprintVisible, ExportObject, ZeroConstructor, InstancedReference, IsPlainOldData, RepSkip, NoDestructor, PersistentInstance, HasGetValueTypeHash)
	class UTextBlock*                             TextBlock_Title;                                   // 0x05E8(0x0008)(BlueprintVisible, ExportObject, ZeroConstructor, InstancedReference, IsPlainOldData, RepSkip, NoDestructor, PersistentInstance, HasGetValueTypeHash)
	class UWidgetSwitcher*                        WidgetSwitcher_Entry;                              // 0x05F0(0x0008)(BlueprintVisible, ExportObject, ZeroConstructor, InstancedReference, IsPlainOldData, RepSkip, NoDestructor, PersistentInstance, HasGetValueTypeHash)

public:
	void ExecuteUbergraph_WBP_BuffEntry(int32 EntryPoint);
	void BP_OnEntryReleased();
	void BP_OnItemExpansionChanged(bool bIsExpanded);
	void OnListItemObjectSet(class UObject* ListItemObject);
	void PreConstruct(bool IsDesignTime);
	void BP_OnItemSelectionChanged(bool bIsSelected);
	void SetHeight(int32 Height);

public:
	static class UClass* StaticClass()
	{
		BP_STATIC_CLASS_IMPL("WBP_BuffEntry_C")
	}
	static const class FName& StaticName()
	{
		STATIC_NAME_IMPL(L"WBP_BuffEntry_C")
	}
	static class UWBP_BuffEntry_C* GetDefaultObj()
	{
		return GetDefaultObjImpl<UWBP_BuffEntry_C>();
	}
};
DUMPER7_ASSERTS_UWBP_BuffEntry_C;

SDK_NAMESPACE_END
