#pragma once

/*
* SDK generated by Dumper-7
*
* https://github.com/Encryqed/Dumper-7
*/

// Package: WBP_HurtTotalPanel

#include "Basic.hpp"

#include "Engine_structs.hpp"
#include "PMGame_classes.hpp"


SDK_NAMESPACE_START

// WidgetBlueprintGeneratedClass WBP_HurtTotalPanel.WBP_HurtTotalPanel_C
// 0x0010 (0x06D8 - 0x06C8)
class UWBP_HurtTotalPanel_C final : public UPMUWTotalHurtPanel
{
public:
	struct FPointerToUberGraphFrame               UberGraphFrame;                                    // 0x06C8(0x0008)(ZeroConstructor, Transient, DuplicateTransient)
	class UWidgetAnimation*                       Anim_Hidden;                                       // 0x06D0(0x0008)(BlueprintVisible, BlueprintReadOnly, ZeroConstructor, Transient, IsPlainOldData, RepSkip, NoDestructor, HasGetValueTypeHash)

public:
	void ExecuteUbergraph_WBP_HurtTotalPanel(int32 EntryPoint);
	void WidgetAnimationEvt_Anim_TotalDamage_K2Node_WidgetAnimationEvent_0();

public:
	static class UClass* StaticClass()
	{
		BP_STATIC_CLASS_IMPL("WBP_HurtTotalPanel_C")
	}
	static const class FName& StaticName()
	{
		STATIC_NAME_IMPL(L"WBP_HurtTotalPanel_C")
	}
	static class UWBP_HurtTotalPanel_C* GetDefaultObj()
	{
		return GetDefaultObjImpl<UWBP_HurtTotalPanel_C>();
	}
};
DUMPER7_ASSERTS_UWBP_HurtTotalPanel_C;

SDK_NAMESPACE_END
