#pragma once

/*
* SDK generated by Dumper-7
*
* https://github.com/Encryqed/Dumper-7
*/

// Package: WBP_ChatCommonRoles

#include "Basic.hpp"

#include "PMGame_classes.hpp"


SDK_NAMESPACE_START

// WidgetBlueprintGeneratedClass WBP_ChatCommonRoles.WBP_ChatCommonRoles_C
// 0x0008 (0x08E0 - 0x08D8)
class UWBP_ChatCommonRoles_C final : public UPMUserWidget
{
public:
	class UImage*                                 Img_Role;                                          // 0x08D8(0x0008)(BlueprintVisible, ExportObject, ZeroConstructor, InstancedReference, IsPlainOldData, RepSkip, NoDestructor, PersistentInstance, HasGetValueTypeHash)

public:
	static class UClass* StaticClass()
	{
		BP_STATIC_CLASS_IMPL("WBP_ChatCommonRoles_C")
	}
	static const class FName& StaticName()
	{
		STATIC_NAME_IMPL(L"WBP_ChatCommonRoles_C")
	}
	static class UWBP_ChatCommonRoles_C* GetDefaultObj()
	{
		return GetDefaultObjImpl<UWBP_ChatCommonRoles_C>();
	}
};
DUMPER7_ASSERTS_UWBP_ChatCommonRoles_C;

SDK_NAMESPACE_END
