#pragma once

/*
* SDK generated by Dumper-7
*
* https://github.com/Encryqed/Dumper-7
*/

// Package: WBP_SelectRoleCardIllustrationsListDeck

#include "Basic.hpp"

#include "PMGame_classes.hpp"


SDK_NAMESPACE_START

// WidgetBlueprintGeneratedClass WBP_SelectRoleCardIllustrationsListDeck.WBP_SelectRoleCardIllustrationsListDeck_C
// 0x0010 (0x05D8 - 0x05C8)
class UWBP_SelectRoleCardIllustrationsListDeck_C final : public UPMBaseUserWidget
{
public:
	class UOverlay*                               Deck;                                              // 0x05C8(0x0008)(BlueprintVisible, ExportObject, ZeroConstructor, InstancedReference, IsPlainOldData, RepSkip, NoDestructor, PersistentInstance, HasGetValueTypeHash)
	class UListView*                              ListViewDeck;                                      // 0x05D0(0x0008)(BlueprintVisible, ExportObject, ZeroConstructor, InstancedReference, IsPlainOldData, RepSkip, NoDestructor, PersistentInstance, HasGetValueTypeHash)

public:
	static class UClass* StaticClass()
	{
		BP_STATIC_CLASS_IMPL("WBP_SelectRoleCardIllustrationsListDeck_C")
	}
	static const class FName& StaticName()
	{
		STATIC_NAME_IMPL(L"WBP_SelectRoleCardIllustrationsListDeck_C")
	}
	static class UWBP_SelectRoleCardIllustrationsListDeck_C* GetDefaultObj()
	{
		return GetDefaultObjImpl<UWBP_SelectRoleCardIllustrationsListDeck_C>();
	}
};
DUMPER7_ASSERTS_UWBP_SelectRoleCardIllustrationsListDeck_C;

SDK_NAMESPACE_END
