#pragma once

/*
* SDK generated by Dumper-7
*
* https://github.com/Encryqed/Dumper-7
*/

// Package: WBP_GrowthSuperStringAttributes_Retrofit

#include "Basic.hpp"

#include "PMGame_classes.hpp"


SDK_NAMESPACE_START

// WidgetBlueprintGeneratedClass WBP_GrowthSuperStringAttributes_Retrofit.WBP_GrowthSuperStringAttributes_Retrofit_C
// 0x0048 (0x0920 - 0x08D8)
class UWBP_GrowthSuperStringAttributes_Retrofit_C final : public UPMUserWidget
{
public:
	class UWBP_GrowthLevelProgressInfo_C*         BP_LevelInfo_Armor;                                // 0x08D8(0x0008)(BlueprintVisible, ExportObject, ZeroConstructor, InstancedReference, IsPlainOldData, RepSkip, NoDestructor, PersistentInstance, HasGetValueTypeHash)
	class UWBP_GrowthLevelProgressInfo_C*         BP_LevelInfo_ArmorReg;                             // 0x08E0(0x0008)(BlueprintVisible, ExportObject, ZeroConstructor, InstancedReference, IsPlainOldData, RepSkip, NoDestructor, PersistentInstance, HasGetValueTypeHash)
	class UWBP_GrowthLevelProgressInfo_C*         BP_LevelInfo_Damage2DFactor;                       // 0x08E8(0x0008)(BlueprintVisible, ExportObject, ZeroConstructor, InstancedReference, IsPlainOldData, RepSkip, NoDestructor, PersistentInstance, HasGetValueTypeHash)
	class UWBP_GrowthLevelProgressInfo_C*         BP_LevelInfo_HealthMax;                            // 0x08F0(0x0008)(BlueprintVisible, ExportObject, ZeroConstructor, InstancedReference, IsPlainOldData, RepSkip, NoDestructor, PersistentInstance, HasGetValueTypeHash)
	class UWBP_GrowthLevelProgressInfo_C*         BP_LevelInfo_HealthReg;                            // 0x08F8(0x0008)(BlueprintVisible, ExportObject, ZeroConstructor, InstancedReference, IsPlainOldData, RepSkip, NoDestructor, PersistentInstance, HasGetValueTypeHash)
	class UWBP_GrowthLevelProgressInfo_C*         BP_LevelInfo_Speed2D;                              // 0x0900(0x0008)(BlueprintVisible, ExportObject, ZeroConstructor, InstancedReference, IsPlainOldData, RepSkip, NoDestructor, PersistentInstance, HasGetValueTypeHash)
	class UImage*                                 Image_12;                                          // 0x0908(0x0008)(BlueprintVisible, ExportObject, ZeroConstructor, InstancedReference, IsPlainOldData, RepSkip, NoDestructor, PersistentInstance, HasGetValueTypeHash)
	class UImage*                                 Image_Role;                                        // 0x0910(0x0008)(BlueprintVisible, ExportObject, ZeroConstructor, InstancedReference, IsPlainOldData, RepSkip, NoDestructor, PersistentInstance, HasGetValueTypeHash)
	class UWidgetSwitcher*                        WidgetSwitcher;                                    // 0x0918(0x0008)(BlueprintVisible, ExportObject, ZeroConstructor, InstancedReference, IsPlainOldData, RepSkip, NoDestructor, PersistentInstance, HasGetValueTypeHash)

public:
	static class UClass* StaticClass()
	{
		BP_STATIC_CLASS_IMPL("WBP_GrowthSuperStringAttributes_Retrofit_C")
	}
	static const class FName& StaticName()
	{
		STATIC_NAME_IMPL(L"WBP_GrowthSuperStringAttributes_Retrofit_C")
	}
	static class UWBP_GrowthSuperStringAttributes_Retrofit_C* GetDefaultObj()
	{
		return GetDefaultObjImpl<UWBP_GrowthSuperStringAttributes_Retrofit_C>();
	}
};
DUMPER7_ASSERTS_UWBP_GrowthSuperStringAttributes_Retrofit_C;

SDK_NAMESPACE_END
