#pragma once

/*
* SDK generated by Dumper-7
*
* https://github.com/Encryqed/Dumper-7
*/

// Package: Weapon15403001

#include "Basic.hpp"

#include "PMGame_classes.hpp"


SDK_NAMESPACE_START

// BlueprintGeneratedClass Weapon15403001.Weapon15403001_C
// 0x0000 (0x1350 - 0x1350)
class AWeapon15403001_C final : public ACyWeaponMelee
{
public:
	static class UClass* StaticClass()
	{
		BP_STATIC_CLASS_IMPL("Weapon15403001_C")
	}
	static const class FName& StaticName()
	{
		STATIC_NAME_IMPL(L"Weapon15403001_C")
	}
	static class AWeapon15403001_C* GetDefaultObj()
	{
		return GetDefaultObjImpl<AWeapon15403001_C>();
	}
};
DUMPER7_ASSERTS_AWeapon15403001_C;

SDK_NAMESPACE_END
