#pragma once

/*
* SDK generated by Dumper-7
*
* https://github.com/Encryqed/Dumper-7
*/

// Package: Weapon_X_Lilith

#include "Basic.hpp"

#include "PMGame_classes.hpp"


SDK_NAMESPACE_START

// BlueprintGeneratedClass Weapon_X_Lilith.Weapon_X_Lilith_C
// 0x0030 (0x1320 - 0x12F0)
class AWeapon_X_Lilith_C final : public ACyWeaponQuickThrowLocation
{
public:
	class UCyFAttackStateMonitor*                 CyFAttackStateMonitor;                             // 0x12F0(0x0008)(BlueprintVisible, ZeroConstructor, InstancedReference, IsPlainOldData, NonTransactional, NoDestructor, HasGetValueTypeHash)
	class UCyForceMoveComponent*                  CyForceMoveRise;                                   // 0x12F8(0x0008)(BlueprintVisible, ZeroConstructor, InstancedReference, IsPlainOldData, NonTransactional, NoDestructor, HasGetValueTypeHash)
	class UCySearchLocationComponent*             CySearchLocation;                                  // 0x1300(0x0008)(BlueprintVisible, ZeroConstructor, InstancedReference, IsPlainOldData, NonTransactional, NoDestructor, HasGetValueTypeHash)
	class UCyForceMoveComponent*                  CyForceMoveJump;                                   // 0x1308(0x0008)(BlueprintVisible, ZeroConstructor, InstancedReference, IsPlainOldData, NonTransactional, NoDestructor, HasGetValueTypeHash)
	class UCySearchTargetsComponent*              CySearchTargets;                                   // 0x1310(0x0008)(BlueprintVisible, ZeroConstructor, InstancedReference, IsPlainOldData, NonTransactional, NoDestructor, HasGetValueTypeHash)

public:
	static class UClass* StaticClass()
	{
		BP_STATIC_CLASS_IMPL("Weapon_X_Lilith_C")
	}
	static const class FName& StaticName()
	{
		STATIC_NAME_IMPL(L"Weapon_X_Lilith_C")
	}
	static class AWeapon_X_Lilith_C* GetDefaultObj()
	{
		return GetDefaultObjImpl<AWeapon_X_Lilith_C>();
	}
};
DUMPER7_ASSERTS_AWeapon_X_Lilith_C;

SDK_NAMESPACE_END
