#pragma once

/*
* SDK generated by Dumper-7
*
* https://github.com/Encryqed/Dumper-7
*/

// Package: Weapon12303001

#include "Basic.hpp"

#include "PMGame_classes.hpp"


SDK_NAMESPACE_START

// BlueprintGeneratedClass Weapon12303001.Weapon12303001_C
// 0x0020 (0x1310 - 0x12F0)
class AWeapon12303001_C final : public ACyWeaponPistol
{
public:
	class UCyFEndReloadState*                     StateEndReload;                                    // 0x12F0(0x0008)(BlueprintVisible, ZeroConstructor, InstancedReference, IsPlainOldData, NonTransactional, NoDestructor, HasGetValueTypeHash)
	class UCyFSecondStartReloadState*             StateSecondStartReload;                            // 0x12F8(0x0008)(BlueprintVisible, ZeroConstructor, InstancedReference, IsPlainOldData, NonTransactional, NoDestructor, HasGetValueTypeHash)
	class UCyFStartReloadState*                   StateStartReload;                                  // 0x1300(0x0008)(BlueprintVisible, ZeroConstructor, InstancedReference, IsPlainOldData, NonTransactional, NoDestructor, HasGetValueTypeHash)

public:
	static class UClass* StaticClass()
	{
		BP_STATIC_CLASS_IMPL("Weapon12303001_C")
	}
	static const class FName& StaticName()
	{
		STATIC_NAME_IMPL(L"Weapon12303001_C")
	}
	static class AWeapon12303001_C* GetDefaultObj()
	{
		return GetDefaultObjImpl<AWeapon12303001_C>();
	}
};
DUMPER7_ASSERTS_AWeapon12303001_C;

SDK_NAMESPACE_END
