#pragma once

/*
* SDK generated by Dumper-7
*
* https://github.com/Encryqed/Dumper-7
*/

// Package: Weapon_E_Michele

#include "Basic.hpp"

#include "PMGame_classes.hpp"


SDK_NAMESPACE_START

// BlueprintGeneratedClass Weapon_E_Michele.Weapon_E_Michele_C
// 0x0010 (0x1300 - 0x12F0)
class AWeapon_E_Michele_C final : public ACyWeaponQuickThrowLocation
{
public:
	class UCySearchTargetsComponent*              CySearchTargets;                                   // 0x12F0(0x0008)(BlueprintVisible, ZeroConstructor, InstancedReference, IsPlainOldData, NonTransactional, NoDestructor, HasGetValueTypeHash)
	class UCySearchLocationComponent*             CySearchLocation;                                  // 0x12F8(0x0008)(BlueprintVisible, ZeroConstructor, InstancedReference, IsPlainOldData, NonTransactional, NoDestructor, HasGetValueTypeHash)

public:
	static class UClass* StaticClass()
	{
		BP_STATIC_CLASS_IMPL("Weapon_E_Michele_C")
	}
	static const class FName& StaticName()
	{
		STATIC_NAME_IMPL(L"Weapon_E_Michele_C")
	}
	static class AWeapon_E_Michele_C* GetDefaultObj()
	{
		return GetDefaultObjImpl<AWeapon_E_Michele_C>();
	}
};
DUMPER7_ASSERTS_AWeapon_E_Michele_C;

SDK_NAMESPACE_END
