#pragma once

/*
* SDK generated by Dumper-7
*
* https://github.com/Encryqed/Dumper-7
*/

// Package: Weapon10000004

#include "Basic.hpp"

#include "PMGame_classes.hpp"


SDK_NAMESPACE_START

// BlueprintGeneratedClass Weapon10000004.Weapon10000004_C
// 0x0000 (0x12F0 - 0x12F0)
class AWeapon10000004_C final : public ACyWeaponTransferWall
{
public:
	static class UClass* StaticClass()
	{
		BP_STATIC_CLASS_IMPL("Weapon10000004_C")
	}
	static const class FName& StaticName()
	{
		STATIC_NAME_IMPL(L"Weapon10000004_C")
	}
	static class AWeapon10000004_C* GetDefaultObj()
	{
		return GetDefaultObjImpl<AWeapon10000004_C>();
	}
};
DUMPER7_ASSERTS_AWeapon10000004_C;

SDK_NAMESPACE_END
